import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import {createHash} from 'node:crypto';
assert.equal(process.argv.length,4,'Usage: node check-paint.mjs <media-review-ui.js> <output.json>');
const code=fs.readFileSync(process.argv[2],'utf8');const checks=[];
function fixture(){let node=null,heading=null,observer,now=0;const frames=[],timers=[],sent=[],listeners={},scrolls=[];
 const fields={disabled:false},track={value:'0'},seconds={value:'0.000000000'},body={};
 const document={body,activeElement:body,visibilityState:'visible',documentElement:{},querySelector:selector=>selector.includes('data-media-reopen-complete')?heading:node,getElementById:id=>({media_review_cursor_fields:fields,media_review_track:track,media_review_seconds:seconds}[id]),addEventListener:(type,fn)=>listeners[type]=fn};
 function element(attributes,visible=true){let top=1000;return {getAttribute:name=>attributes[name],setAttribute:(name,value)=>{attributes[name]=value},getClientRects:()=>visible?[{}]:[],getBoundingClientRect:()=>({top,bottom:top+60,left:10,right:350,width:340,height:60}),focus(){document.activeElement=this},scrollIntoView(options){scrolls.push(options);top=100},setTop:value=>{top=value}}}
 const Shiny={setInputValue:(...args)=>sent.push(JSON.parse(JSON.stringify(args)))};const window={Shiny,innerHeight:844,innerWidth:390,addEventListener:(type,fn)=>listeners[type]=fn};
 const context=vm.createContext({window,document,Shiny,Set,Map,Date:{now:()=>now},requestAnimationFrame:fn=>frames.push(fn),setTimeout:fn=>{timers.push(fn);return timers.length;},MutationObserver:class{constructor(fn){observer=fn}observe(){}}});vm.runInContext(code,context);
 return {sent,frames,document,listeners,fields,track,seconds,context,scrolls,set:(token,phase='prepare',visible=true,expected='1.000000000')=>{if(document.activeElement===node)document.activeElement=body;node=token?element({'data-media-reopen-ticket':token,'data-media-reopen-phase':phase,'data-media-reopen-track':'0','data-media-reopen-seconds':expected},visible):null;observer()},frame:()=>{const n=frames.length;for(let i=0;i<n;i++)frames.shift()()},tick:ms=>{now+=ms;const n=timers.length;for(let i=0;i<n;i++)timers.shift()()},isStatusFocused:()=>document.activeElement===node,complete:token=>{if(document.activeElement===node)document.activeElement=body;node=null;heading=element({'data-media-reopen-complete':token});observer()},isResultFocused:()=>document.activeElement===heading,scrollAway:()=>{node.setTop(1000);listeners.scroll()},scrollBack:()=>{node.setTop(100);listeners.scroll()},notify:()=>observer()};
}
function check(name,fn){fn();checks.push(name)}
check('Scoped fields disable immediately; source acknowledgement follows two visible frames',()=>{const f=fixture();f.set('one');assert.equal(f.fields.disabled,true);assert.equal(f.sent.length,0);f.frame();assert.equal(f.sent.length,0);f.frame();assert.deepEqual(f.sent[0],['media_review_reopen_ack',{token:'one',phase:'prepare',controls:{track:'0',seconds:'0.000000000'}},{priority:'event'}])});
check('Repeated mutations never acknowledge the same token and phase twice',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.set('one');f.frame();f.frame();assert.equal(f.sent.length,1)});
check('Replaced ticket gets its own two frames and old ticket cannot acknowledge',()=>{const f=fixture();f.set('old');f.frame();f.set('new');f.frame();assert.equal(f.sent.length,0);f.frame();assert.equal(f.sent.length,0);f.frame();assert.equal(f.sent[0][1].token,'new')});
check('Closing removes ticket and re-enables surviving controls without acknowledgement',()=>{const f=fixture();f.set('old');f.frame();f.set(null);f.frame();assert.equal(f.sent.length,0);assert.equal(f.fields.disabled,false)});
check('Hidden document retains lock but waits until visible for acknowledgment',()=>{const f=fixture();f.document.visibilityState='hidden';f.set('one');f.frame();f.frame();assert.equal(f.sent.length,0);assert.equal(f.fields.disabled,true);f.document.visibilityState='visible';f.listeners.visibilitychange();f.frame();f.frame();assert.equal(f.sent.length,1)});
check('Unrendered ticket cannot release source work until its layout is visible',()=>{const f=fixture();f.set('one','prepare',false);f.frame();f.frame();assert.equal(f.sent.length,0);f.set('one','prepare',true);f.frame();f.frame();assert.equal(f.sent.length,1)});
check('Verification waits for exact restored DOM controls then two frames',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.sent.length=0;f.set('one','verify');f.frame();f.frame();assert.equal(f.sent.length,0);f.seconds.value='1.000000000';f.tick(100);f.frame();assert.equal(f.sent.length,0);f.frame();assert.equal(f.sent[0][1].phase,'verify');assert.equal(f.sent[0][1].controls.seconds,'1.000000000')});
check('One ticket can separately acknowledge prepared and restored states',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.seconds.value='1.000000000';f.set('one','verify');f.frame();f.frame();assert.deepEqual(f.sent.map(x=>x[1].phase),['prepare','verify'])});
check('Unmatched control wait is bounded and returns mismatch for server refusal',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.sent.length=0;f.set('one','verify');f.tick(15001);f.frame();f.frame();assert.equal(f.sent.length,1);assert.equal(f.sent[0][1].controls.seconds,'0.000000000')});
check('A changed control between scheduled frames is reported rather than hidden',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.sent.length=0;f.seconds.value='1.000000000';f.set('one','verify');f.frame();f.seconds.value='2.000000000';f.frame();assert.equal(f.sent[0][1].controls.seconds,'2.000000000')});
check('Repeated script attachment installs only one acknowledgement system',()=>{const f=fixture();vm.runInContext(code,f.context);f.set('one');f.frame();f.frame();assert.equal(f.sent.length,1)});
check('Opening status receives focus and instant viewport scroll before either animation frame',()=>{const f=fixture();f.set('one');assert.equal(f.isStatusFocused(),true);assert.equal(f.sent.length,0);assert.equal(f.scrolls[0].behavior,'instant')});
check('Moving status outside viewport before acknowledgement stops work until visible again',()=>{const f=fixture();f.set('one');f.frame();f.scrollAway();f.frame();assert.equal(f.sent.length,0);f.scrollBack();f.frame();f.frame();assert.equal(f.sent.length,1)});
check('Only matching successful ticket hands focus to the completed result once',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.complete('one');assert.equal(f.isResultFocused(),true);assert.equal(f.fields.disabled,false);const n=f.scrolls.length;f.notify();assert.equal(f.scrolls.length,n)});
check('Unrelated completed result cannot take focus from a pending ticket',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.complete('other');assert.equal(f.isResultFocused(),false)});
check('User movement to another control is respected when results become ready',()=>{const f=fixture();f.set('one');f.frame();f.frame();const other={};f.document.activeElement=other;f.complete('one');assert.equal(f.document.activeElement,other)});
check('A superseded completed ticket never steals focus from the newer status',()=>{const f=fixture();f.set('old');f.frame();f.frame();f.set('new');f.frame();f.frame();f.complete('old');assert.equal(f.isResultFocused(),false)});
check('Intentional focus elsewhere does not strand the later verification phase offscreen',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.sent.length=0;const other={};f.document.activeElement=other;f.seconds.value='1.000000000';f.set('one','verify');f.frame();f.frame();assert.equal(f.sent.length,1);assert.equal(f.document.activeElement,other);f.complete('one');assert.equal(f.document.activeElement,other)});
check('Intentional wheel scrolling is respected without blocking later verification or stealing completion focus',()=>{const f=fixture();f.set('one');f.frame();f.frame();f.sent.length=0;f.listeners.wheel({isTrusted:true});f.seconds.value='1.000000000';const n=f.scrolls.length;f.set('one','verify');f.frame();f.frame();assert.equal(f.sent.length,1);assert.equal(f.scrolls.length,n);f.complete('one');assert.equal(f.isResultFocused(),false)});
check('Manual focus ownership stays yielded even when that control is removed and focus returns to body',()=>{const f=fixture();f.set('one');f.frame();f.frame();const other={};f.document.activeElement=other;f.listeners.focusin({target:other});f.document.activeElement=f.document.body;f.seconds.value='1.000000000';f.set('one','verify');f.frame();f.frame();assert.equal(f.sent.length,2);f.complete('one');assert.equal(f.document.activeElement,f.document.body);assert.equal(f.isResultFocused(),false)});
check('Own status focus events do not yield their ticket ownership',()=>{const f=fixture();f.set('one');f.listeners.focusin({target:f.document.activeElement});f.frame();f.frame();f.complete('one');assert.equal(f.isResultFocused(),true)});
const result={passed:true,checks,source_sha256:createHash('sha256').update(code).digest('hex'),scope:'Fake-DOM queue, phase, input-lock and bounded restoration tests only; actual browser source/paint acceptance remains required.'};
fs.writeFileSync(process.argv[3],JSON.stringify(result,null,2));console.log(JSON.stringify(result));
