source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=TRUE)
args<-commandArgs(trailingOnly=TRUE);stopifnot(length(args)==3L)
candidate<-normalizePath(args[[1]],winslash="/",mustWork=TRUE);folder<-normalizePath(args[[2]],winslash="/",mustWork=TRUE);out<-normalizePath(args[[3]],winslash="/",mustWork=TRUE)
source(file.path(candidate,"R/platform-media-review-views.R"),encoding="UTF-8")
checks<-character();check<-function(name,x){if(!isTRUE(x))stop(name,call.=FALSE);checks<<-c(checks,name);cat("PASS",name,"\n");flush.console()}
local({
 store<-brohn_open_store(file.path(folder,"workspace"));on.exit(brohn_close_store(store),add=TRUE)
 config<-brohn_read_json_file(file.path(folder,"fixture.json"));r<-brohn_get_entity(store,"audio_review",config$original$regular$audio$id)
 record<-brohn_get_entity(store,"media_review",config$original$regular$media$id);inventory<-brohn_get_entity(store,"media_review",record$body$request$catalog$id)
 before<-DBI::dbGetQuery(store$con,"SELECT * FROM entity_versions ORDER BY kind,id,revision");jobs<-DBI::dbGetQuery(store$con,"SELECT * FROM jobs ORDER BY id")
 shiny::testServer(function(input,output,session){
  state<-shiny::reactiveValues(page="report",report_id=r$body$report_id)
  api<-brohn_install_media_review(input,output,session,store,state,function(fn)fn(),function(...)NULL,function()NULL,function(fn)fn())
 },{
  session$flushReact();callbacks<-list();sent<-list();calls<-0L
  unlockBinding("onFlushed",session);session$onFlushed<-function(fun,once=FALSE){callbacks[[length(callbacks)+1L]]<<-fun;invisible(function(){})};lockBinding("onFlushed",session)
  unlockBinding("sendInputMessage",session);session$sendInputMessage<-function(id,message){sent[[length(sent)+1L]]<<-list(id=id,message=message)};lockBinding("sendInputMessage",session)
  e<-environment(api$open);original_current<-e$current;e$current<-function(){calls<<-calls+1L;original_current()}
  setup<-function(){state$page<-"report";state$report_id<-r$body$report_id;session$flushReact();shiny::isolate(api$open(.brohn_mr_ref(r),function()r));shiny::isolate(e$catalog(inventory));session$setInputs(media_review_track="0",media_review_seconds="0.000000000");callbacks<<-list();sent<<-list();calls<<-0L}
  request<-function(ref=.brohn_mr_ref(record)){session$setInputs(media_review_reopen=ref);shiny::isolate(e$reopening())}
  ack<-function(ticket,controls=ticket$controls){session$setInputs(media_review_reopen_ack=list(token=ticket$token,phase=ticket$phase,controls=controls))}
  setup();ticket<-request()
  check("Click exposes accurate scoped status before any full source resolution",calls==0L&&grepl("Opening saved media review",output$media_review_status$html,fixed=TRUE)&&grepl(ticket$token,output$media_review_status$html,fixed=TRUE)&&is.null(shiny::isolate(e$opened())))
  check("Controls have a scoped native fieldset for client lock without replacing input bindings",grepl('id="media_review_cursor_fields"',output$media_review_controls$html,fixed=TRUE))
  ack(ticket);verified<-shiny::isolate(e$reopening())
  check("Only acknowledged visible preparation runs exact original source readers",calls==1L&&identical(verified$phase,"verify")&&identical(verified$record$id,record$id)&&is.null(shiny::isolate(e$opened())))
  check("Controlled restoration has accurate verification status and no manual-edit instruction",grepl("verifying complete original files",output$media_review_status$html,fixed=TRUE)&&is.null(output$media_review_result))
  for(cb in callbacks)cb();callbacks<-list()
  check("Deferred restoration preserves original exact track and seconds",length(sent)==2L&&identical(sent[[1]]$message$value,"0")&&identical(sent[[2]]$message$value,"1.000000000"))
  session$setInputs(media_review_track="0",media_review_seconds="1.000000000")
  shiny::isolate(e$native$ready<-TRUE) # Component boundary only: actual native verification covered independently/browser next.
  ack(verified,list(track="0",seconds="1.000000000"))
  check("Matched browser and server controls open only the exact verified saved record",identical(shiny::isolate(e$opened())$id,record$id))
  shiny::isolate({e$reopening(NULL);e$resources(list())});session$flushReact();session$setInputs(media_review_seconds="1.25")
  check("Real subsequent cursor edit retains manual-change warning and source release",grepl("The cursor or track changed",output$media_review_result$html,fixed=TRUE)&&!e$native$ready&&is.null(shiny::isolate(e$resources())))
  setup();ticket<-request();shiny::isolate(e$close());ack(ticket)
  check("Closing modal fences the previous acknowledgement before source work",calls==0L&&is.null(shiny::isolate(e$reopening()))&&is.null(shiny::isolate(e$opened())))
  setup();old<-request();new<-request(.brohn_mr_ref(inventory));ack(old)
  check("Superseded ticket cannot resolve the earlier saved source",calls==0L&&identical(shiny::isolate(e$reopening())$token,new$token))
  ack(new);check("Acknowledged original inventory reopens without native frame work",calls==1L&&identical(shiny::isolate(e$catalog())$id,inventory$id)&&is.null(shiny::isolate(e$reopening())))
  setup();ticket<-request();session$setInputs(media_review_seconds="1.25");ack(ticket,list(track="0",seconds="1.25"))
  check("Real edit before painted acknowledgement refuses before full source work",calls==0L&&is.null(shiny::isolate(e$reopening()))&&grepl("cursor changed before",shiny::isolate(e$issue()),fixed=TRUE))
  setup();ticket<-request();state$report_id<-"different-report";ack(ticket)
  check("Changing report fences old acknowledgement and clears view",calls==0L&&is.null(shiny::isolate(e$reopening()))&&is.null(shiny::isolate(e$opened())))
  setup();ticket<-request();bad<-ticket;bad$token<-"wrong-token";ack(bad)
  check("Unknown acknowledgement cannot start source work",calls==0L&&identical(shiny::isolate(e$reopening())$token,ticket$token))
  setup();ticket<-request();ack(ticket);verified<-shiny::isolate(e$reopening());saved_callbacks<-callbacks;new<-request(.brohn_mr_ref(inventory));sent<-list()
  for(cb in saved_callbacks)cb()
  check("Old deferred cursor messages do not overwrite a superseding request",length(sent)==0L&&identical(shiny::isolate(e$reopening())$token,new$token))
  setup();ticket<-request();ack(ticket);verified<-shiny::isolate(e$reopening());ack(verified,list(track="0",seconds="99.000000000"))
  check("Unmatched browser restoration fails visibly without native opening",is.null(shiny::isolate(e$opened()))&&is.null(shiny::isolate(e$reopening()))&&grepl("restored cursor is not current",shiny::isolate(e$issue()),fixed=TRUE))
  setup();ticket<-request();DBI::dbBegin(store$con)
  tryCatch({DBI::dbExecute(store$con,"UPDATE entities SET project_id='feedback-revoked' WHERE kind='dataset' AND id=?",params=list(record$body$request$dataset$id));ack(ticket)
   check("Current project revocation after paint still refuses original source access",is.null(shiny::isolate(e$reopening()))&&is.null(shiny::isolate(e$opened()))&&!is.null(shiny::isolate(e$issue())))
  },finally=DBI::dbRollback(store$con))
  shiny::isolate(e$close())
 })
 check("Feedback preparation preserves all immutable versions and58 job receipts",identical(before,DBI::dbGetQuery(store$con,"SELECT * FROM entity_versions ORDER BY kind,id,revision"))&&identical(jobs,DBI::dbGetQuery(store$con,"SELECT * FROM jobs ORDER BY id")))
 brohn_write_json_file(list(passed=TRUE,checks=as.list(checks),new_jobs=0L,candidate_sha256=digest::digest(file=file.path(candidate,"R/platform-media-review-views.R"),algo="sha256"),scope="Shiny component/full original read guards; client paint mocked and native opening bypassed only for one successful state transition. Actual browser acceptance remains required."),file.path(out,"results.json"))
})
