# Synthetic metadata-only boundary tests. No participant corpus or science engine.
args<-commandArgs(TRUE);stopifnot(length(args)==2L)
repo<-normalizePath(args[[1L]],winslash="/",mustWork=TRUE);out<-args[[2L]]
stopifnot(!file.exists(out));dir.create(out,recursive=TRUE);out<-normalizePath(out,winslash="/");setwd(repo)
source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=FALSE)
for(fn in c("brohn_maxdiff_fit","brohn_maxdiff_analysis","brohn_maxdiff_plot_rows","brohn_task_score"))assign(fn,function(...)stop("Metadata resolver must never read or calculate scientific models"),envir=.GlobalEnv)
checks<-list();check<-function(name,value){if(!isTRUE(value))stop(name,call.=FALSE);checks[[length(checks)+1L]]<<-name}
reject<-function(expr)inherits(try(force(expr),silent=TRUE),"try-error")
model<-function(status,rows,available=rows)list(model_hash=brohn_hash(list(status,rows)),status=status,reason=if(status%in%c("available","estimated"))NULL else status,row_count=rows,available_count=available,unavailable_count=rows-available,panel_cost=1L)
catalog<-lapply(seq_len(3L),function(i)list(kind="exercise",key=brohn_hash(list("key",i)),index=i,exercise_id=paste0("exercise-",i),title="Repeated visible title",profile="object-case-paired-maxdiff/1.0",result_hash=brohn_hash(list("result",i)),design_hash=brohn_hash(list("design",i)),responses_hash=brohn_hash(list("responses",i)),item_count=60L,exposure_count=360L,
 counts=model(if(i==3L)"no_complete_pairs"else"available",60L,if(i==3L)0L else 60L),utilities=model(c("estimated","not_requested","unavailable")[[i]],if(i==1L)60L else 0L),compatible_adapters=list("choice-counts","choice-utilities")))
section<-list(adapter="choice-counts",selector=list(scope="all_exercises"),display=list(pages="all",page_numbers=list()))
before<-brohn_hash(catalog);resolved<-brohn_resolve_choice_report_section(section,catalog)
check("all exercises cost one panel each regardless of 50-row table pagination",resolved$panel_count==3L&&length(resolved$section$resolved_models)==3L)
selected<-section;selected$selector<-list(scope="exact_exercises",keys=list(catalog[[3L]]$key,catalog[[1L]]$key));x<-brohn_resolve_choice_report_section(selected,catalog)
check("requested keys preserve exact original source order",identical(lapply(x$section$resolved_models,`[[`,"key"),list(catalog[[1L]]$key,catalog[[3L]]$key)))
page<-section;page$display<-list(pages="selected",page_numbers=list(2L));x<-brohn_resolve_choice_report_section(page,catalog)
check("page two changes no model or chart count",x$panel_count==3L&&.brohn_rp_same(x$section$resolved_models,resolved$section$resolved_models))
utility<-section;utility$adapter<-"choice-utilities";x<-brohn_resolve_choice_report_section(utility,catalog)
check("estimated, not-requested and unavailable each retain an exact panel",x$panel_count==3L&&identical(vapply(x$section$resolved_models,`[[`,character(1),"status"),c("estimated","not_requested","unavailable")))
bad<-utility;bad$display<-list(pages="selected",page_numbers=list(2L));check("empty utility alternatives cannot claim a second numerical page",reject(brohn_resolve_choice_report_section(bad,catalog)))
bad<-catalog;bad[[1L]]$counts$panel_cost<-"1";check("string panel cost refused",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-catalog;bad[[1L]]$counts$row_count<-TRUE;check("boolean row count refused",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-catalog;bad[[1L]]$counts$unavailable_count<-1L;check("inconsistent support partition refused",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-catalog;bad[[1L]]$item_count<-61L;check("unqualified item-count bound refused",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-catalog;bad[[1L]]$counts$invented<-0L;check("unknown model support field refused",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-catalog;bad[[1L]]$invented<-0L;check("unknown catalog field refused",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-catalog;bad[[1L]]$utilities$reason<-0L;check("numeric status reason refused",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-catalog;bad[[1L]]$index<-2L;check("wrong original source ordinal refused",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-catalog;bad[[2L]]$key<-bad[[1L]]$key;check("duplicate catalog keys refused despite duplicate titles being valid",reject(brohn_resolve_choice_report_section(section,bad)))
bad<-selected;bad$selector$keys<-list(catalog[[1L]]$key,catalog[[1L]]$key);check("duplicate selected keys refused",reject(brohn_resolve_choice_report_section(bad,catalog)))
bad<-section;bad$display$page_numbers<-list(1L);check("conflicting all-page request refused",reject(brohn_resolve_choice_report_section(bad,catalog)))
bad<-section;bad$display<-list(pages="selected",page_numbers=list(0L));check("zero-based numerical page refused",reject(brohn_resolve_choice_report_section(bad,catalog)))
check("metadata resolver leaves input complete catalog unchanged",identical(before,brohn_hash(catalog)))
row<-list(participant_id="correct_test_rt_mean",name="correct_test_rt_mean",value=500,unit="ms",reason="correct_test_rt_mean");before<-brohn_hash(row)
node<-.brohn_rpt_table(list(row),"Metric collision", "choice-metric-unit",names(row),50L,FALSE,"administration")
cells<-list();visit<-function(x){if(inherits(x,"shiny.tag")){if(x$name=="td")cells[[length(cells)+1L]]<<-x;invisible(lapply(x$children,visit))}else if(is.list(x))invisible(lapply(x,visit))};visit(node)
check("only exact metric-name column gains friendly display label",sum(vapply(cells,function(x)!is.null(x$attribs[["data-saved-field"]]),logical(1)))==1L&&identical(cells[[1L]]$children[[1L]],row$participant_id)&&identical(cells[[5L]]$children[[1L]],row$reason))
check("metric label rendering preserves original row values",identical(before,brohn_hash(row)))
brohn_write_json_file(list(passed=TRUE,checks=checks,sources=stats::setNames(lapply(c("tables","tasks","choice","render"),function(n)digest::digest(file=file.path(repo,"R",paste0("platform-report-package-",n,".R")),algo="sha256")),c("tables","tasks","choice","render")),scope="Synthetic metadata resolver and table label boundary only. Scientific functions fail-fast; no source corpus, store, worker, browser or timing claim."),file.path(out,"results.json"))
cat(length(checks),"metadata and label boundary checks passed\n")

