args<-commandArgs(trailingOnly=TRUE);stopifnot(length(args)==3L)
repo<-normalizePath(args[[1L]],winslash="/",mustWork=TRUE);components<-normalizePath(args[[2L]],winslash="/",mustWork=TRUE)
out<-args[[3L]];stopifnot(!file.exists(out));dir.create(out,recursive=TRUE);out<-normalizePath(out,winslash="/")
setwd(repo);source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=FALSE)
checks<-list();failure<-NULL
check<-function(ok,label){if(!isTRUE(ok))stop(label);checks[[length(checks)+1L]]<<-list(name=label,passed=TRUE)}
refuse<-function(fn,label)check(inherits(try(fn(),silent=TRUE),"try-error"),label)
tryCatch({
 original<-file.path(components,"constant-1/result.json");a<-brohn_eda_read_json_file(original,16*1024^2)
 r<-a$recordings[[1L]];p<-a$parameters[[r$recording_id]];features<-a$features
 identity<-r[c("recording_id","segment_id","channel")];selection<-c(identity,list(start_s=.brohn_ecr_shortest(r$start_time_s),end_s=.brohn_ecr_shortest(r$end_time_s)))
 tables<-lapply(a$artifacts,function(x){con<-file(x$path,open="r",encoding="UTF-8");on.exit(close(con));lines<-readLines(con,n=2L,warn=FALSE);jsonlite::fromJSON(lines[[2L]],simplifyVector=FALSE)})
 # This model is explicitly a structural fixture. The source features/headers
 # are real component outputs; no reader or native publication is claimed.
 counts<-list(complete_sample_artifact_rows=a$artifacts[[1L]]$rows,complete_event_artifact_rows=a$artifacts[[2L]]$rows,segment_coordinate_rows=r$samples,segment_retained_coordinate_rows=r$retained_samples,segment_excluded_coordinate_rows=r$samples-r$retained_samples,selected_coordinate_rows=r$samples,selected_retained_coordinate_rows=r$retained_samples,selected_excluded_coordinate_rows=r$samples-r$retained_samples,segment_numerical_candidate_rows=0,selected_numerical_candidate_rows=0,displayed_processed_points=0)
 result<-list(schema="brohn-eda-continuous-review/1.1",status="raw_description_only",binding=list(),selection=selection,recording=r,parameters=p,features=features,unit="uS",raw_available=FALSE,counts=counts,candidates=list(),markers=list(),series=list(clean_us=list(),tonic_us=list(),phasic_us=list()),processed_components=list(),rows=list(),source_tables=tables,verification=list(),exports=lapply(seq_along(c("eda-samples.csv","eda-candidates.csv","eda-markers.csv")),function(i)list(name=c("eda-samples.csv","eda-candidates.csv","eda-markers.csv")[[i]],hash=strrep("a",64),bytes=100,rows=if(i==1L)r$samples else 0)),display_policy="Raw descriptions with unavailable processed response measures",limitations=list("Declared edge exclusions retained while processing withheld"))
 verify<-function(x).brohn_ecr_validate_constant_model(x,r,p,features,a$artifacts,selection,TRUE)
 verify(result);check(TRUE,"typed raw-description direct model preserves coordinates and withholds processed displays")
 mutate<-function(label,fn)refuse(function()verify(fn(result)),label)
 mutate("old result version cannot contain new grammar",function(x){x$schema<-"brohn-eda-continuous-review/1.0";x})
 mutate("raw description cannot be relabelled available",function(x){x$status<-"available";x})
 mutate("sample count names cannot masquerade as processed measurements",function(x){x$counts$selected_samples<-x$counts$selected_coordinate_rows;x})
 mutate("selected coordinates cannot be cropped",function(x){x$counts$selected_coordinate_rows<-10;x})
 mutate("coordinate retained/excluded totals stay exact",function(x){x$counts$selected_excluded_coordinate_rows<-0;x})
 mutate("zero numerical candidate records is structural",function(x){x$counts$segment_numerical_candidate_rows<-1;x})
 mutate("processed point count cannot become positive",function(x){x$counts$displayed_processed_points<-1;x})
 mutate("three unavailable arrays cannot become a fabricated DC trace",function(x){x$series$tonic_us<-list(list(retained=TRUE,source_rows=r$samples,points=list(list(value=0,time_s=0,source_sample_index=0))));x})
 mutate("candidate records cannot be invented",function(x){x$candidates<-list(list(type="scr"));x})
 mutate("marker records cannot be invented",function(x){x$markers<-list(list(kind="peak"));x})
 mutate("processed component membership remains empty",function(x){x$processed_components<-list("tonic_us");x})
 mutate("direct preview cannot replace complete coordinates",function(x){x$rows<-list(list(time_s=0));x})
 mutate("nullable table header is required",function(x){x$source_tables[[1L]]$columns[[3L]]$nullable<-FALSE;x})
 mutate("null retained denominator cannot become finite",function(x){x$source_tables[[1L]]$support$retained_support$response_denominator<-0;x})
 mutate("candidate table must remain empty",function(x){x$source_tables[[2L]]$expected_rows<-1;x})
 mutate("coordinate CSV count cannot be a display preview",function(x){x$exports[[1L]]$rows<-50;x})
 mutate("candidate CSV is header-only",function(x){x$exports[[2L]]$rows<-1;x})
 mutate("direct model cannot leak a private path",function(x){x$source_tables[[1L]]$path<-"private";x})
 prepared<-result;prepared$rows<-prepared$exports<-NULL;prepared$endpoint_coverage<-list(unobserved=list())
 .brohn_ecr_validate_constant_model(prepared,r,p,features,a$artifacts,selection,FALSE);check(TRUE,"prepared model keeps null-valued source and zero endpoint coverage")
 cell<-list(key=strrep("b",64),identity=identity,source_record_index=1L,original_status="descriptive_only",status="raw_description_only",reason="exact_constant_signal",selection=selection,original_default_bounds=selection[c("start_s","end_s")],requested_bounds=selection[c("start_s","end_s")],original_support=r,feature_indices=as.list(1:10),model=prepared,model_hash=brohn_eda_value_hash(prepared),coverage=list(features=10,source_record_preserved=TRUE,scientific_processing=FALSE))
 catalog<-.brohn_edd_catalog(list(schema="brohn-eda-display-evidence/0.2",source_family="continuous",cells=list(cell)))[[1L]]
 check(identical(catalog$descriptive_status,"computed")&&identical(catalog$scr_status,"unavailable")&&identical(catalog$scr_reason,"exact_constant_signal")&&is.null(catalog$descriptive_reason),"catalog separates raw descriptive support from unavailable response")
 check(!catalog$focusable&&identical(catalog$focus_reason,"exact_constant_signal")&&length(catalog$components)==0L&&catalog$marker_page_count==0&&catalog$feature_count==10&&!is.null(catalog$model_hash),"catalog offers one hashed explanatory state without false window recovery")
 check(all(vapply(catalog$numerical_page_counts$points,function(x)x==0,logical(1)))&&catalog$numerical_page_counts$candidates==0&&catalog$marker_count==0,"catalog declares zero representative pages and markers")
},error=function(e)failure<<-conditionMessage(e))
brohn_write_json_file(list(schema="brohn-constant-model-contract-tests/0.1",passed=is.null(failure),count=length(checks),checks=checks,error=failure,scope="Structural model/catalog tests using actual original component features/headers. No scientific operation, native store, reader execution or publication."),file.path(out,"results.json"))
if(!is.null(failure))stop(failure);cat("Passed",length(checks),"scoped model checks\n")
