import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import vm from 'node:vm';
import {createHash} from 'node:crypto';
const here=path.resolve(process.argv[2]),coreFile=path.resolve('www/participant/gnat-core.js');
vm.runInThisContext(await fs.readFile(coreFile,'utf8'));
const core=globalThis.BrohnGnatCore,compiled=JSON.parse(await fs.readFile(path.join(here,'compiled.json'),'utf8'));
const trials=compiled.timeline.filter(t=>t.type==='task_trial'),go=trials.find(t=>t.expected_action==='go'),nogo=trials.find(t=>t.expected_action==='nogo');
const output=path.join(here,`evidence-state-${Date.now()}`);await fs.mkdir(output);
const checks=[],cases=[];const check=(name,fn)=>{fn();checks.push(name);console.log('PASS',name);};
const key=(s,type,at,options={})=>core.transition(s,{type:'key',now:options.now??at,event_ms:at,keyType:type,code:'Space',repeat:false,trusted:true,modifiers:false,...options});
const ms=n=>Number(n.toFixed(6));
const withholding=s=>{s=core.transition(s,{type:'deadline_timer',now:ms(s.deadline_ms+1)});s=core.transition(s,{type:'deadline_frame',now:ms(s.deadline_ms+17)});return core.transition(s,{type:'seal',now:ms(s.deadline_ms+17)});};
const finish=s=>{s=core.transition(s,{type:'feedback_end',now:ms(s.feedback_start_ms+100)});const at=ms(s.feedback_start_ms+500);s=core.transition(s,{type:'visibility',now:at,visible:true,focused:true});return core.transition(s,{type:'blank_end',now:at});};
const answer=(t,at=250)=>{let s=core.create(t,100);s=key(s,'down',100+at);s=core.transition(s,{type:'seal',now:100+at+1});s=key(s,'up',100+at+2);return finish(s);};
check('All 384 original compiled trials execute without shortening',()=>{assert.equal(trials.length,384);for(const t of trials){const s=t.expected_action==='go'?answer(t):finish(withholding(core.create(t,100)));assert.equal(core.result(s).correct,true);cases.push({trial:t,result:core.result(s)});}});
check('Go first response is hit with event latency',()=>{const r=core.result(answer(go));assert.equal(r.outcome,'hit');assert.equal(r.response_ms,250);assert.equal(r.response_code,'Space');});
check('No-Go first response is false alarm',()=>{const r=core.result(answer(nogo));assert.equal(r.outcome,'false_alarm');assert.equal(r.correct,false);});
for(const t of [go,nogo])check(`Intact withholding yields ${t.expected_action==='go'?'miss':'correct_rejection'} and null key/RT`,()=>{const r=core.result(finish(withholding(core.create(t,100))));assert.equal(r.outcome,t.expected_action==='go'?'miss':'correct_rejection');assert.equal(r.response_code,null);assert.equal(r.response_ms,null);});
check('Exactly-onset response is eligible at zero measured latency',()=>assert.equal(core.result(answer(go,0)).response_ms,0));
check('Exactly-deadline key is diagnostic, never response',()=>{let s=core.create(nogo,100);s=key(s,'down',s.deadline_ms);assert.equal(s.keys[0].ignored_reason,'after_deadline');s=key(s,'up',s.deadline_ms);s=finish(withholding(s));assert.equal(core.result(s).outcome,'correct_rejection');});
check('Last fractional instant before deadline remains eligible',()=>assert.equal(core.result(answer(go,go.timeout_ms-.001)).outcome,'hit'));
check('On-time key dispatched after timer still wins before seal',()=>{let s=core.create(go,100);s=core.transition(s,{type:'deadline_timer',now:s.deadline_ms+1});s=key(s,'down',s.deadline_ms-.5,{now:s.deadline_ms+8});s=core.transition(s,{type:'deadline_frame',now:s.deadline_ms+17});s=core.transition(s,{type:'seal',now:s.deadline_ms+17});s=key(s,'up',s.deadline_ms+18);s=finish(s);assert.equal(core.result(s).response_ms,go.timeout_ms-.5);});
check('Eligible delayed key after withholding seal interrupts without revising receipt',()=>{let s=withholding(core.create(nogo,100));s=key(s,'down',s.deadline_ms-.5,{now:s.deadline_ms+18});const r=core.result(s);assert.equal(r.outcome,'interrupted');assert.equal(r.response_outcome,'correct_rejection');assert.equal(r.response_code,null);assert.equal(r.correct,null);assert.equal(r.keys[0].ignored_reason,'eligible_key_after_seal');});
check('An earlier key arriving after accepted first key interrupts',()=>{let s=core.create(go,100);s=key(s,'down',350);s=key(s,'up',351);s=key(s,'down',349,{now:352});assert.equal(core.result(s).interruption_reason,'event_clock_reversed');assert.equal(core.result(s).response_ms,250);});
check('Other key is retained without becoming a response',()=>{let s=core.create(nogo,100);s=key(s,'down',200,{code:'KeyA'});s=key(s,'up',201,{code:'KeyA'});s=finish(withholding(s));assert.equal(s.keys[0].ignored_reason,'other_key');assert.equal(core.result(s).outcome,'correct_rejection');});
for(const options of [{trusted:false},{modifiers:true}])check(`${options.trusted===false?'Untrusted':'Modified'} Space cannot answer`,()=>{let s=core.create(nogo,100);s=key(s,'down',200,options);s=key(s,'up',201,options);s=finish(withholding(s));assert.equal(core.result(s).response_ms,null);});
check('Held key repeat is diagnostic after actual first key',()=>{let s=core.create(go,100);s=key(s,'down',200);s=key(s,'down',201,{repeat:true});assert.equal(s.keys[1].ignored_reason,'key_repeat');assert.equal(s.first.event_ms,200);});
check('Repeated Space without prior down interrupts impossible key state',()=>{let s=key(core.create(go,100),'down',200,{repeat:true});assert.equal(core.result(s).interruption_reason,'impossible_space_key_state');});
check('Space release without a prior down interrupts impossible key state',()=>assert.equal(core.result(key(core.create(go,100),'up',200)).outcome,'interrupted'));
check('Held Space is refused at requested onset',()=>assert.throws(()=>core.create(go,100,['Space'])));
check('Early key before onset interrupts instead of producing withholding',()=>assert.equal(core.result(key(core.create(nogo,100),'down',99,{now:101})).interruption_reason,'anticipatory'));
check('Hidden visibility interrupts and preserves false snapshot',()=>{const r=core.result(core.transition(core.create(nogo,100),{type:'visibility',now:110,visible:false,focused:true}));assert.equal(r.correct,null);assert.equal(r.visibility.at(-1).visible,false);});
check('Lost focus during blank interrupts',()=>{let s=withholding(core.create(nogo,100));s=core.transition(s,{type:'feedback_end',now:s.feedback_start_ms+100});s=core.transition(s,{type:'visibility',now:s.feedback_start_ms+200,visible:true,focused:false});assert.equal(core.result(s).outcome,'interrupted');});
check('Withholding cannot seal on timer alone',()=>{let s=core.create(nogo,100);s=core.transition(s,{type:'deadline_timer',now:s.deadline_ms});assert.throws(()=>core.transition(s,{type:'seal',now:s.deadline_ms}));});
check('Deadline frame cannot precede timer',()=>assert.throws(()=>core.transition(core.create(nogo,100),{type:'deadline_frame',now:1200})));
check('Early deadline timer is refused',()=>assert.throws(()=>core.transition(core.create(nogo,100),{type:'deadline_timer',now:101})));
check('Short feedback is refused',()=>{const s=withholding(core.create(nogo,100));assert.throws(()=>core.transition(s,{type:'feedback_end',now:s.feedback_start_ms+99.999}));});
check('Delayed feedback requires a complete subsequent 400ms blank',()=>{let s=withholding(core.create(nogo,100));s=core.transition(s,{type:'feedback_end',now:s.feedback_start_ms+150});s=core.transition(s,{type:'visibility',now:s.feedback_start_ms+500,visible:true,focused:true});assert.throws(()=>core.transition(s,{type:'blank_end',now:s.feedback_start_ms+500}));s=core.transition(s,{type:'visibility',now:s.feedback_start_ms+550,visible:true,focused:true});assert.equal(core.transition(s,{type:'blank_end',now:s.feedback_start_ms+550}).phase,'finished');});
check('Blank cannot finish without final visibility evidence',()=>{let s=withholding(core.create(nogo,100));s=core.transition(s,{type:'feedback_end',now:s.feedback_start_ms+100});assert.throws(()=>core.transition(s,{type:'blank_end',now:s.feedback_start_ms+500}));});
check('Space held after response extends blank until released',()=>{let s=core.create(go,100);s=key(s,'down',200);s=core.transition(s,{type:'seal',now:201});s=core.transition(s,{type:'feedback_end',now:301});s=core.transition(s,{type:'visibility',now:701,visible:true,focused:true});assert.throws(()=>core.transition(s,{type:'blank_end',now:701}));s=key(s,'up',800);s=core.transition(s,{type:'visibility',now:800,visible:true,focused:true});assert.equal(core.transition(s,{type:'blank_end',now:800}).blank_end_ms,800);});
check('Finished state cannot be revised by a later key',()=>assert.throws(()=>key(answer(go),'down',2000)));
check('Unfinished state cannot manufacture a complete receipt',()=>assert.throws(()=>core.result(core.create(nogo,100))));
check('State transition leaves original observation immutable',()=>{const s=core.create(go,100),before=JSON.stringify(s);key(s,'down',200);assert.equal(JSON.stringify(s),before);});
check('Invalid runtime deadline does not alter named procedure',()=>assert.throws(()=>core.create({...go,timeout_ms:50},100)));
check('NaN, future and reversed observation clocks are refused',()=>{const s=core.create(go,100);assert.throws(()=>key(s,'down',NaN));assert.throws(()=>key(s,'down',201,{now:200}));assert.throws(()=>key(s,'down',90));});
await fs.writeFile(path.join(output,'complete-trial-results.json'),JSON.stringify(cases,null,2));
const events=[],clock=n=>({id:'browser-monotonic',unit:'ms',value:n.toFixed(6),instance_id:'gnat-pure-component-fixture',time_origin_ms:'1000000.000'});
let at=10,index=0;
const emit=(kind,data)=>events.push({type:'task_event',clock:clock(Number(data.clock.value)+.01),payload:{kind,data}});
for(const step of compiled.timeline){
  if(step.type==='task_instructions'){at+=50;emit('task_instructions',{task_id:compiled.id,step_id:step.id,block_id:step.block_id,procedure_hash:compiled.procedure_hash,clock:clock(at)});continue;}
  const start=ms(at+.01),onset=ms(start+20);at=onset;const base={task_id:compiled.id,trial_id:step.id,block_id:step.block_id,procedure_hash:compiled.procedure_hash};
  emit('task_trial_started',{...base,clock:clock(onset),held_codes:[],release_wait:{start_ms:start,end_ms:onset,held_codes:[],keys:[],visibility:[{observed_ms:start,visible:true,focused:true},{observed_ms:onset,visible:true,focused:true}]},
    timing_reference:'requestAnimationFrame_before_paint',viewport:{width:1200,height:900,device_pixel_ratio:1},stimulus_rect:{x:300,y:300,width:200,height:50},visible:true,focused:true});
  let s=core.create(step,onset);const respond=step.expected_action==='go'?index%5!==0:index%5===0;
  if(respond){s=key(s,'down',onset+200);s=core.transition(s,{type:'seal',now:onset+205});s=key(s,'up',onset+210);}else s=withholding(s);
  s=finish(s);at=s.blank_end_ms+.01;emit('task_trial_finished',{...base,...core.result(s),clock:clock(at),frame_count:100,max_frame_gap_ms:17});index++;
}
await fs.writeFile(path.join(output,'complete-replay-events.json'),JSON.stringify(events,null,2));
await fs.writeFile(path.join(output,'results.json'),JSON.stringify({passed:true,checks,original_trials:384,source_sha256:createHash('sha256').update(await fs.readFile(coreFile)).digest('hex'),scope:'Pure original state observations; not browser or physical timing qualification.'},null,2));
console.log(JSON.stringify({passed:true,checks:checks.length,output}));
