source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=TRUE)
source("R/platform-answer-session.R",encoding="UTF-8");source("R/platform-answer-session-views.R",encoding="UTF-8")
source("tests/fixtures/answer-session-source.R",encoding="UTF-8")
local({
  folder<-Sys.getenv("BROHN_ANSWER_SESSION_TEST_ROOT",tempfile("brohn-answer-session-domain-"));dir.create(folder,recursive=TRUE,showWarnings=FALSE)
  stopifnot(!file.exists(file.path(folder,"workspace","catalog.sqlite")));checks<-character()
  check<-function(label,x){if(!isTRUE(x))stop(label,call.=FALSE);checks<<-c(checks,label);cat("PASS",label,"\n")}
  rejects<-function(expr)inherits(try(force(expr),silent=TRUE),"try-error")
  check("Ordinary event labels are preserved literally in CSV",identical(.brohn_as_csv(c("run_finished","trial","step_started")),'"run_finished","trial","step_started"'))
  unsafe<-c("=1+1","+formula","@reference","\tcell","\rcell","-formula")
  check("Formula and control-leading CSV text is protected without changing JSON",identical(.brohn_as_csv(unsafe),paste0('"\'',unsafe,'"',collapse=",")))
  store<-brohn_open_store(file.path(folder,"workspace"));on.exit(brohn_close_store(store),add=TRUE);brohn_initialise_library(store)
  f<-brohn_answer_session_fixture(store);run<-brohn_run(store,f$run_id)
  original<-list(protocol=brohn_hash(run$protocol),events=brohn_hash(brohn_run_events(store,f$run_id)),run=run,receipts=brohn_rows(DBI::dbGetQuery(store$con,"SELECT * FROM delivery_receipts WHERE scope=? ORDER BY operation,operation_id",params=list(f$run_id))))
  body<-brohn_analyse_runs(list(design=f$design,runs=list(run),events=stats::setNames(list(f$journal),f$run_id)))
  body$id<-"report-original-answer-session";body$schema_version<-"brohn-report/1.0.0";body$created_at<-brohn_now()
  body$result_object<-brohn_store_object(store,bytes=charToRaw(enc2utf8(brohn_json(list(schema="brohn-analysis-output/1.0",report=body)))),media_type="application/json")
  report<-brohn_put_entity(store,"report",body$id,body);report_hash<-brohn_hash(report$body)
  jq<-brohn_queue_questionnaire_index(store,report$id,report$revision,report_hash,report$project_id)
  j<-brohn_claim_job(store,"answer-session-domain-index",300);stopifnot(j$id==jq$id)
  qi<-brohn_questionnaire_index_input(store,j);scratch<-file.path(store$root,"scratch","index-worker");dir.create(scratch,recursive=TRUE)
  qp<-brohn_analyse_questionnaire_index(qi,scratch)
  paths<-c("R/platform-publication.R",names(.brohn_qexplorer_loaded),"scripts/workers/publication.py","src/publication_guard.c")
  qo<-list(schema="brohn-analysis-output/1.0",code_identity=stats::setNames(lapply(paths,function(p)digest::digest(file=p,algo="sha256")),paths),report=qp)
  qpath<-file.path(scratch,"output.json");brohn_write_json_file(qo,qpath);qr<-brohn_publish_questionnaire_index(store,qo,scratch,j,qi,qpath)
  opened<-brohn_open_questionnaire_index(store,qr$result$questionnaire_index_id,qr$result$index_hash,report$id,report$revision,report_hash,report$project_id)
  on.exit(brohn_close_questionnaire_index(opened),add=TRUE)
  page<-brohn_questionnaire_index_page(opened$handle,"answers");row<-page$rows[[1L]]
  q<-brohn_queue_answer_session(store,opened,row$record_key,row$source_hash);input<-brohn_answer_session_input(store,q)
  check("Source pins exact report index record protocol design and complete event hash",input$binding$run_source$events_hash==f$source_hash&&input$binding$answer$record_key==row$record_key)
  check("Repeated exact session review reuses the same job",brohn_queue_answer_session(store,opened,row$record_key,row$source_hash)$id==q$id)
  check("Wrong source record hash rejects",rejects(brohn_queue_answer_session(store,opened,row$record_key,brohn_hash("wrong"))))
  questions<-brohn_questionnaire_index_page(opened$handle,"questions")
  check("Aggregate question cannot masquerade as one session",rejects(brohn_queue_answer_session(store,opened,questions$rows[[1]]$record_key,questions$rows[[1]]$source_hash)))
  for(k in c("project_id","record_hash")){
    bad<-q;bad$request[[k]]<-if(k=="project_id")"other-project"else brohn_hash("other-record")
    if(k=="project_id")check(paste("Changed",k,"rejects"),rejects(brohn_answer_session_input(store,bad)))else{
      dir<-file.path(folder,paste0("bad-",k));dir.create(dir);bi<-input;bi$binding<-bad$request;check("Worker rejects changed pinned source row",rejects(brohn_analyse_answer_session(bi,dir)))}}
  for(k in c("protocol_hash","design_hash")){bad<-q;bad$request$run_source[[k]]<-brohn_hash("another-source");check(paste("Changed",k,"rejects before read"),rejects(brohn_answer_session_input(store,bad)))}
  bad<-q;bad$request$snapshot$run$acked_sequence<-1L;check("Changed received metadata cannot inherit the answer",rejects(brohn_answer_session_input(store,bad)))
  dir<-file.path(store$root,"scratch","direct-reader");dir.create(dir);result<-brohn_analyse_answer_session(input,dir)$answer_session
  check("Complete event export reproduces independent original JSON hash",identical(digest::digest(file=file.path(dir,"artifacts/received-events.json"),algo="sha256"),f$source_hash))
  csv<-utils::read.csv(file.path(dir,"artifacts/received-event-timeline.csv"),stringsAsFactors=FALSE,check.names=FALSE)
  check("Complete CSV preserves every original event type and hash",identical(csv$event_type,vapply(f$journal,`[[`,character(1),"type"))&&identical(csv$event_sha256,vapply(f$journal,brohn_hash,character(1))))
  check("Full event count includes revisions and actual ending without duplicate responses",result$received$events==length(f$journal)&&result$verified_history_events==length(f$journal)-1L&&length(body$analysis$observations)==8L&&result$received$ending$outcome=="completed")
  check("Questionnaire commits are not invented step finish events",result$received$step_finish_count==0L&&result$assigned$steps==length(f$protocol$timeline))
  con<-DBI::dbConnect(RSQLite::SQLite(),file.path(dir,"artifacts/session-evidence.sqlite"),flags=RSQLite::SQLITE_RO)
  on.exit(DBI::dbDisconnect(con),add=TRUE);p1<-brohn_answer_session_page(con,"events");p2<-brohn_answer_session_page(con,"events",p1$next_after)
  check("Keyset pages preserve all ordered events beyond first25",length(p1$rows)==25L&&p2$rows[[1]]$sequence==26L&&length(c(p1$rows,p2$rows))==length(f$journal))
  exact<-brohn_answer_session_page(con,"events",step_id=row$step_id)
  check("Answer step filter retains received visit and edit events",length(exact$rows)==4L&&all(vapply(exact$rows,function(e)e$step_id==row$step_id,logical(1))))
  e<-exact$rows[[2]];chunk<-brohn_answer_session_event_chunk(con,e$sequence,e$event_hash);text<-chunk$text
  while(chunk$more){chunk<-brohn_answer_session_event_chunk(con,e$sequence,e$event_hash,chunk$offset+4000L);text<-paste0(text,chunk$text)}
  check("Long Unicode event chunks reconstruct exact original typed JSON",identical(text,brohn_json(f$journal[[e$sequence]])))
  check("Chunk wrong event hash and fractional offset reject",rejects(brohn_answer_session_event_chunk(con,e$sequence,brohn_hash("wrong")))&&rejects(brohn_answer_session_event_chunk(con,e$sequence,e$event_hash,1)))
  altered<-input;altered$binding$run_source$events_hash<-brohn_hash(list());adir<-file.path(folder,"changed-journal-hash");dir.create(adir)
  check("Different full journal hash cannot pass exact answer linking",rejects(brohn_analyse_answer_session(altered,adir)))
  altered<-input;altered$binding$index_context$project_id<-"other-project"
  check("Changed context cannot authorize received source",rejects(.brohn_as_authority(store,altered$binding)))
  # Actual native guarded publication and cancellation fence, without claiming a supervised child run.
  claimed<-brohn_claim_job(store,"answer-session-domain-publish",300);stopifnot(claimed$id==q$id)
  paths<-c("R/platform-publication.R",names(.brohn_answer_session_loaded),"scripts/workers/publication.py","src/publication_guard.c")
  output<-list(schema="brohn-analysis-output/1.0",code_identity=stats::setNames(lapply(paths,function(p)digest::digest(file=p,algo="sha256")),paths),report=list(answer_session=result))
  path<-file.path(dir,"output.json");brohn_write_json_file(output,path);receipt<-brohn_publish_answer_session(store,output,dir,claimed,input,path)
  saved<-brohn_answer_session_record(store,receipt$result$answer_session_id,q$request)
  check("Native guarded publication saves a derived view and successful receipt",receipt$status=="succeeded"&&saved$body$result$received$events_hash==f$source_hash)
  check("Reopen reuses complete evidence without another scoring job",brohn_queue_answer_session(store,opened,row$record_key,row$source_hash)$id==q$id&&length(brohn_list_entities(store,"report"))==1L)
  check("Original report run journal receipt and assigned protocol remain unchanged",identical(report_hash,brohn_hash(brohn_get_entity(store,"report",report$id)$body))&&identical(original$run,brohn_run(store,f$run_id))&&identical(original$events,brohn_hash(brohn_run_events(store,f$run_id)))&&identical(original$receipts,brohn_rows(DBI::dbGetQuery(store$con,"SELECT * FROM delivery_receipts WHERE scope=? ORDER BY operation,operation_id",params=list(f$run_id)))))
  # Native source identity required even when a copied report uses local-looking identifiers.
  imported<-opened;imported$record$body$binding$origin<-"imported"
  check("Imported-looking altered view cannot borrow native session authority",rejects(brohn_queue_answer_session(store,imported,row$record_key,row$source_hash)))
  check("A matching-looking absent run cannot borrow a local session",rejects(.brohn_as_snapshot(store$con,"run-absent-original","default")))
  check("The original run is unavailable outside its exact project",rejects(.brohn_as_snapshot(store$con,f$run_id,"other-project")))
  f2<-brohn_answer_session_fixture(store,n=2L,finish=FALSE)
  check("Received completion without final receipt remains unresolved until reviewed",rejects(.brohn_as_snapshot(store$con,f2$run_id,"default")))
  brohn_deployment_state(store,f2$release_id,"closed")
  review<-brohn_session_resolution_review(store,f2$release_id,f2$run_id,f2$design$id,"default")
  resolution<-brohn_resolve_session(store,f2$release_id,f2$run_id,f2$design$id,"default",review$hash,"Original synthetic missing-final-acknowledgment case.")
  recovered<-.brohn_as_snapshot(store$con,f2$run_id,"default")
  check("Separate confirmed completion stays distinct from missing original receipt",recovered$run$completion_status=="in_progress"&&length(recovered$final_receipts)==0L&&recovered$resolution$body$effective_resolution=="received_completion_confirmed"&&recovered$resolution$body$participant_ending$outcome=="completed")
  check("HTML view module loads under Windows C locale",is.function(brohn_install_answer_session))
  brohn_write_json_file(list(passed=TRUE,checks=checks,report_id=report$id,run_id=f$run_id,report_hash=report_hash,events_hash=f$source_hash,job_id=q$id,derived_id=saved$id,artifacts=result$exports),file.path(folder,"results.json"))
  cat("PASS",length(checks),"answer-session assertions; retained",folder,"\n")
})
