# Catalog-shaped original fixtures are metadata, not acquired observations or
# scientific reports. Exercise the old global-window failure and real callers.
source("R/platform-load.R", encoding = "UTF-8"); brohn_load(ui = FALSE)
local({
  checks <- 0L
  check <- function(name, value) {if (!isTRUE(value)) stop("Filtered catalog: ", name); checks <<- checks+1L}
  rejected <- function(value) inherits(try(force(value), silent = TRUE), "try-error")
  root <- .brohn_port_temp(); store <- brohn_open_store(file.path(root,"catalog")); brohn_initialise_library(store)
  on.exit({brohn_close_store(store); .brohn_port_cleanup(root)}, add = TRUE)
  old <- brohn_create_study(store,"Earliest archived target", "blank")
  old$body$archived <- TRUE; old <- brohn_put_entity(store,"study",old$id,old$body,old$revision)
  report <- list(title="Earliest source result",study_id=old$id,origin="sample",analysis=list(kind="questionnaire"),provenance=list(design=old$body))
  kinds <- c("acquisition","acquisition_discovery","header_inspection","stream_import","stream_curation","aoi_proposal")
  old_body <- list(study_id=old$id,dataset_id="old-data",source_dataset_id="old-data",stream_id="old-stream",source_hash=paste(rep("a",64),collapse=""),status="recording",review=list(status="queued"))
  brohn_store_batch(store, function() {
    brohn_put_entity(store,"report","old-report",report)
    for (kind in kinds) brohn_put_entity(store,kind,paste0("old-",kind),old_body)
    brohn_put_entity(store,"stream","old-stream",list(source_dataset_id="old-data",import_id="old-import",source_index=2))
    brohn_put_entity(store,"stream","old-stream-first",list(source_dataset_id="old-data",import_id="old-import",source_index=1))
    for (i in 1:511) {
      d <- brohn_new_design(paste("Newer study",i),"blank"); brohn_put_entity(store,"study",d$id,d)
      unrelated <- old_body; unrelated$study_id <- d$id; unrelated$dataset_id <- unrelated$source_dataset_id <- paste0("new-data-",i)
      unrelated$stream_id <- paste0("new-stream-",i); unrelated$status <- "complete"; unrelated$review$status <- "prepared"
      unrelated$source_hash <- paste(rep("b",64),collapse="")
      for (kind in kinds) brohn_put_entity(store,kind,paste0("new-",kind,"-",i),unrelated)
      r <- report; r$study_id <- d$id; brohn_put_entity(store,"report",paste0("new-report-",i),r)
    }
    for (i in 1:2001) brohn_put_entity(store,"stream",paste0("new-stream-",i),list(source_dataset_id=paste0("new-data-",i),import_id="new-import",source_index=i))
    d <- brohn_new_design("Other project private label","blank",project_id="other-project"); brohn_put_entity(store,"study",d$id,d,project_id="other-project")
    brohn_put_entity(store,"report","foreign-same-parent",report,project_id="other-project")
    nested <- report; nested$analysis$kind <- "multimodal"; brohn_put_entity(store,"report","nested-synthesis",nested)
  })
  check("prior global entity window misses original",!"old-acquisition" %in% brohn_ids(brohn_list_entities(store,"acquisition")))
  check("parent filters precede entity limit",identical(brohn_ids(brohn_acquisitions(store,old$id)),"old-acquisition"))
  check("active state precedes global history limit",identical(brohn_ids(brohn_acquisitions(store,status=c("queued","recording","attention_required"))),"old-acquisition"))
  check("queued nested review precedes global history limit",identical(brohn_ids(brohn_acquisitions(store,review_status="queued")),"old-acquisition"))
  check("discovery parent filter retains old evidence",identical(brohn_ids(brohn_lsl_discoveries(store,old$id)),"old-acquisition_discovery"))
  check("header selects parent and exact source hash",identical(brohn_ids(brohn_header_inspections(store,"old-data",old_body$source_hash)),"old-header_inspection") && !length(brohn_header_inspections(store,"old-data",paste(rep("b",64),collapse=""))))
  check("old stream import remains available",identical(brohn_ids(brohn_stream_imports(store,"old-data")),"old-stream_import"))
  check("streams filtered before2000 and returned in original source order",identical(brohn_ids(brohn_streams(store,dataset_id="old-data",import_id="old-import")),c("old-stream-first","old-stream")))
  check("old curation matches both source references",identical(brohn_ids(brohn_stream_curations(store,"old-stream","old-data")),"old-stream_curation") && !length(brohn_stream_curations(store,"new-stream-1","old-data")))
  check("study search applies query and archive before bound",identical(brohn_ids(brohn_studies(store,query="Earliest",archived=TRUE,limit=1)),old$id))
  check("active study filter excludes archived without losing its result slots",length(brohn_studies(store,project_id="default",archived=FALSE,limit=500))==500)
  choices <- brohn_study_choices(store,"default")
  check("study chooser retains oldest archived and all newer studies",length(choices)==513 && old$id %in% unname(choices) && grepl("archived",names(choices)[match(old$id,choices)],fixed=TRUE))
  check("study chooser excludes other project labels",!any(grepl("Other project",names(choices),fixed=TRUE)))
  reports <- brohn_source_report_choices(store,old$id)
  check("synthesis source chooser retains older report and excludes nested or foreign results",identical(unname(reports),"old-report"))
  old_job <- brohn_enqueue_job(store,"inspect_header",list(dataset_id="old-data"),"old-job")
  for(i in 1:111) brohn_enqueue_job(store,"inspect_header",list(dataset_id=paste0("new-data-",i)),paste0("new-job-",i))
  check("prior global job window misses original attempt",!old_job$id %in% brohn_ids(brohn_list_jobs(store)))
  check("job operation and request filters precede bound",identical(brohn_ids(brohn_list_jobs(store,request_filters=list(dataset_id="old-data"),operation="inspect_header",status="queued")),old_job$id))
  check("wrong operation and state never leak",!length(brohn_list_jobs(store,request_filters=list(dataset_id="old-data"),operation="analyse_dataset")) && !length(brohn_list_jobs(store,request_filters=list(dataset_id="old-data"),status="running")))
  check("filtered pagination has disjoint deterministic records",!any(brohn_ids(brohn_list_entities(store,"acquisition",limit=20,filters=list(status="complete"))) %in% brohn_ids(brohn_list_entities(store,"acquisition",limit=20,filters=list(status="complete"),offset=20))))
  brohn_put_entity(store,"filter-probe","typed-true",list(value=TRUE))
  brohn_put_entity(store,"filter-probe","typed-number",list(value=1))
  brohn_put_entity(store,"filter-probe","typed-text",list(value="1"))
  check("boolean and numeric states remain distinct",identical(brohn_ids(brohn_list_entities(store,"filter-probe",filters=list(value=TRUE))),"typed-true") && identical(brohn_ids(brohn_list_entities(store,"filter-probe",filters=list(value=1))),"typed-number"))
  check("text values remain distinct from numeric",identical(brohn_ids(brohn_list_entities(store,"filter-probe",filters=list(value="1"))),"typed-text"))
  check("SQL-like values are literal",!length(brohn_list_entities(store,"acquisition",filters=list(study_id="' OR 1=1 --"))))
  check("injected path rejected",rejected(brohn_list_entities(store,"acquisition",filters=stats::setNames(list("x"),"status') OR 1=1 --"))))
  check("duplicate empty missing and malformed filters rejected",rejected(brohn_list_entities(store,"acquisition",filters=list(status="a",status="b"))) && rejected(brohn_list_jobs(store,request_filters=list(dataset_id=NA_character_))) && rejected(brohn_list_entities(store,"acquisition",filters=list(status=character()))) && rejected(brohn_list_entities(store,"acquisition",offset=-1)))
  # Invoke the actual recording reservation guard after historical saturation.
  d <- brohn_create_study(store,"Reservation test","blank")
  result <- list(streams=list()); discovery <- list(study_id=d$id,status="ready",result=result,result_hash=brohn_hash(result),script_hash=.brohn_acq_hash(.brohn_acq_script()))
  brohn_put_entity(store,"acquisition_discovery","reservation-discovery",discovery)
  failure <- tryCatch(brohn_queue_acquisition(store,d$id,"reservation-discovery",list(),list(),"sample","Original fixture",list(),d$revision,TRUE),error=identity)
  check("actual reservation refuses hidden old recording before any new writer",inherits(failure,"error") && grepl("one recording at a time",conditionMessage(failure),fixed=TRUE))
  cat(sprintf("PASS: %d historical filtering, selectors and reservation checks\n",checks))
})
