source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=TRUE)
local({
  n<-0L;check<-function(ok,label){if(!isTRUE(ok))stop(label);n<<-n+1L;cat("PASS",label,"\n")};reject<-function(x)inherits(try(force(x),silent=TRUE),"try-error")
  folder<-tempfile("brohn-question-materials-");dir.create(folder);store<-brohn_open_store(file.path(folder,"source"));other<-brohn_open_store(file.path(folder,"destination"))
  on.exit({brohn_close_store(store);brohn_close_store(other)},add=TRUE);brohn_initialise_library(store);brohn_initialise_library(other)
  first<-normalizePath("examples/stimuli/sample-design-a.png",winslash="/");second<-normalizePath("examples/stimuli/sample-design-b.png",winslash="/")
  d<-brohn_new_design("Original illustrated question","survey");d$questions<-list(brohn_question("Original question","single_choice","end","q-original"));legacy<-brohn_json(d);protocol<-brohn_json(brohn_compile(d,2L))
  brohn_validate_design(d);check(identical(legacy,brohn_json(d))&&identical(protocol,brohn_json(brohn_compile(d,2L)))&&!brohn_has_question_illustrations(d),"Absent illustrations leave legacy canonical design and allocation unchanged")
  types<-c("rating","single_choice","multiple_choice","dropdown","text","long_text","number","slider","matrix","ranking","allocation","information")
  for(type in types){q<-brohn_question(paste("Original",type),type,"end",paste0("q-",gsub("_","-",type)));if(type=="matrix")q$rows<-list(list(id="row-original",label="Original row"));d$questions<-list(q)
    illustrated<-brohn_material_attach_png(store,d,"question",q$id,path=first,image_alt=paste("Exact original",type,"illustration"))
    restored<-brohn_remove_question_illustration(illustrated,q$id)
    check(identical(brohn_json(restored),brohn_json(d))&&illustrated$questions[[1]]$type==type,paste(type,"accepts optional image and removal restores all original question fields"))}
  d$questions<-list(brohn_question("Original first","single_choice","end","q-first"),brohn_question("Original second","text","end","q-second"))
  d$questions[[2]]$show_if<-list(op="equals",question_id="q-first",value=1)
  order_design<-brohn_new_design("Original section order","survey");order_design$questions<-lapply(1:4,function(i){q<-brohn_question(paste("Original order",i),"single_choice","end",paste0("q-order-",i));q$randomize_options<-TRUE;q})
  order_design$questionnaire_sections<-brohn_question_sections_new(order_design)
  for(i in seq_along(order_design$questionnaire_sections$sections[[1]]$groups))order_design$questionnaire_sections$sections[[1]]$groups[[i]]$placement<-"shuffle"
  illustrated_order<-brohn_material_attach_png(store,order_design,"question","q-order-1",path=first,image_alt="Original section image")
  procedural_order<-function(p)lapply(Filter(function(s)s$type=="question",p$timeline),function(s)list(question_id=s$question$id,options=s$question$options))
  check(all(vapply(1:6,function(i)identical(brohn_json(procedural_order(brohn_compile(order_design,i))),brohn_json(procedural_order(brohn_compile(illustrated_order,i)))),logical(1))),"Illustration preserves randomized section/group and option orders across six allocations")
  original<-d;d<-brohn_material_attach_png(store,d,"question","q-first",path=first,image_alt="First source description <literal>")
  d<-brohn_material_attach_png(store,d,"question","q-second",path=first,image_alt="Different description for the same bytes")
  image<-d$questions[[1]]$illustration;profile<-brohn_illustration_profile(d)
  check(length(profile$assets)==1L&&profile$pixels==800*600&&profile$media_bytes==file.info(first)$size&&d$questions[[2]]$illustration$image_alt!=image$image_alt,"Shared bytes have one resource budget and distinct owner descriptions")
  check(reject(brohn_material_use_text(d,"question","q-first",text="Overwrite prompt")),"Question image removal cannot overwrite question wording through passive text conversion")
  changed<-brohn_material_describe(d,"question","q-first",image_alt="Revised description")
  check(identical(changed$questions[[1]]$illustration$asset,image$asset)&&identical(changed$questions[[2]],d$questions[[2]]),"Description-only update preserves bytes and other questions")
  bad<-image;bad$image_alt<-"";check(reject(brohn_validate_illustration(bad)),"Present illustration requires a nonempty authored description")
  bad<-image;bad$asset$width<-4097;check(reject(brohn_validate_illustration(bad)),"Illustration metadata enforces the existing PNG geometry bound")
  bad<-image;bad$asset$filename<-"../private.png";check(reject(brohn_validate_illustration(bad)),"Illustration metadata rejects filesystem paths")
  bad<-image;bad$image_alt<-paste(rep("\u00e9",1001),collapse="");check(reject(brohn_validate_illustration(bad)),"Authored description bound uses UTF-8 bytes")
  bounds<-d;bounds$questions<-lapply(1:9,function(i){q<-d$questions[[1]];q$id<-paste0("q-budget-",i);q$illustration$asset$hash<-sprintf("%064d",i);q$illustration$asset$width<-4000;q$illustration$asset$height<-2000;q})
  check(reject(brohn_illustration_profile(bounds)),"Nine unique 8-million-pixel images exceed the decoded illustration profile")
  check(reject(brohn_validate_design(bounds)),"Complete design validation also enforces the aggregate illustration budget")
  bounds$questions<-bounds$questions[1:8];check(brohn_illustration_profile(bounds)$pixels==64000000,"Exactly 64 million unique pixels remains within the profile")
  bounds<-d;bounds$stimuli<-list(list(asset=list(hash=strrep("b",64),size=512*1024^2,media_type="video/mp4")))
  check(reject(brohn_illustration_profile(bounds)),"Unique illustration bytes share the existing study media byte budget")
  repeated<-brohn_new_design("Original repeated illustrated occurrence");for(i in seq_along(repeated$stimuli))repeated$stimuli[[i]]$content<-paste("Original",i)
  repeated$questions[[1]]$illustration<-image;compiled<-brohn_compile(repeated,1L)
  check(sum(vapply(compiled$timeline,function(s)identical(s$type,"question"),logical(1)))==2L&&brohn_illustration_profile(repeated)$pixels==800*600,"After-each occurrences reuse one illustration without inflating its budget")
  d$questionnaire_navigation<-brohn_questionnaire_navigation();assigned<-brohn_compile(d,2L);brohn_questionnaire_revision_context(assigned)
  augmented<-.brohn_delivery_protocol_urls(assigned,strrep("a",64));steps<-Filter(function(s)s$type=="question",augmented$timeline)
  check(identical(augmented$design,assigned$design)&&all(vapply(seq_along(steps),function(i)identical(steps[[i]]$question,Filter(function(s)s$type=="question",assigned$timeline)[[i]]$question)&&grepl(image$asset$hash,steps[[i]]$question_image_url,fixed=TRUE),logical(1))),"Transport URLs stay outside canonical questions and frozen design")
  saved<-brohn_put_entity(store,"study",d$id,d);release<-brohn_publish(store,d$id,"sample");app<-brohn_delivery_app(store)
  get<-function(hash)app$call(list(PATH_INFO=paste0("/api/assets/",release$token,"/",hash),REQUEST_METHOD="GET"))
  check(get(image$asset$hash)$status==200L&&digest::digest(file=get(image$asset$hash)$body$file,algo="sha256")==image$asset$hash,"The actual release serves exact referenced question image bytes")
  newer<-brohn_material_attach_png(store,d,"question","q-first",path=second,image_alt="Original replacement illustration");saved<-brohn_save_study(store,newer,saved$revision)
  check(get(newer$questions[[1]]$illustration$asset$hash)$status==404L&&get(image$asset$hash)$status==200L,"A replacement never widens or alters the old release capability")
  clone<-brohn_clone_study(store,d$id);template<-brohn_save_template(store,d$id);reuse<-brohn_use_template(store,template$id)
  check(identical(brohn_json(clone$body$questions[[1]]$illustration),brohn_json(newer$questions[[1]]$illustration))&&identical(brohn_json(reuse$body$questions[[2]]$illustration),brohn_json(d$questions[[2]]$illustration)),"Clone and template preserve each image and authored description")
  zip<-brohn_export_design(store,d$id,file.path(folder,"original-illustrations.brohn-study.zip"));imported<-brohn_import_design(other,zip)
  check(identical(brohn_json(imported$body$questions[[1]]$illustration),brohn_json(newer$questions[[1]]$illustration))&&file.exists(brohn_object_path(other,image$asset$hash)),"Actual cross-workspace ZIP preserves exact illustrations and complete graph")
  partial<-file.path(folder,"partial.png");writeBin(readBin(first,"raw",n=40L),partial);broken<-d;broken$id<-brohn_id("study");broken$questions<-list(broken$questions[[1]])
  broken$questions[[1]]$illustration$asset<-c(brohn_store_object(store,path=partial,media_type="image/png"),list(filename="partial.png",width=800,height=600))
  brohn_put_entity(store,"study",broken$id,broken)
  check(reject(brohn_publish(store,broken$id,"sample")),"Publication rejects header-valid but incompletely decoded PNG bytes")
  broken_zip<-brohn_export_design(store,broken$id,file.path(folder,"broken-illustrations.brohn-study.zip"));before<-length(brohn_studies(other))
  check(reject(brohn_import_design(other,broken_zip))&&length(brohn_studies(other))==before,"Portable illustration requires complete PNG decoding before catalog registration")
  report<-list(study_id=d$id,dataset_id=NULL,origin="sample",provenance=list(design=d,design_hash=brohn_hash(d)),analysis=list(kind="questionnaire",features=list(list(prompt=paste(rep("Original ",700),collapse=""))),observations=list()))
  packed<-brohn_pack_questionnaire_report(report,folder,threshold=1024);ref<-packed$analysis$artifacts[[1]];source<-brohn_questionnaire_artifact_source(report)
  check(identical(brohn_json(brohn_read_questionnaire_artifact(ref$path,ref,source)),brohn_json(report$analysis)),"Packed questionnaire artifact remains lossless with image-bearing provenance")
  changed_report<-report;changed_report$provenance$design$questions[[1]]$illustration$image_alt<-"Changed after report"
  check(reject(brohn_read_questionnaire_artifact(ref$path,ref,brohn_questionnaire_artifact_source(changed_report))),"Artifact source binding rejects substituted question illustration provenance")
  cat("PASS",n,"question illustration domain checks\n")
})
