# Portable pure metadata tests; no store, application runtime or scientific job.
args <- commandArgs(trailingOnly = TRUE)
stopifnot(length(args) == 2L)
root <- normalizePath(args[[1L]], winslash = "/", mustWork = TRUE)
out <- args[[2L]]
dir.create(out, recursive = TRUE, showWarnings = FALSE)
stopifnot(!file.exists(file.path(out, "RESULTS.json")))
source(file.path(root, "R", "platform-method-evidence.R"), encoding = "UTF-8")
results <- list(); start <- proc.time()[["elapsed"]]
save <- function(status) jsonlite::write_json(list(status = status, checks = results,
  elapsed_s = proc.time()[["elapsed"]]-start, R = R.version.string,
  jsonlite = as.character(packageVersion("jsonlite")), digest = as.character(packageVersion("digest")),
  module_sha256 = digest::digest(file = file.path(root,"R","platform-method-evidence.R"),algo="sha256"),
  registry_sha256 = digest::digest(file = file.path(root,"registry","method-evidence-0.1.json"),algo="sha256"),
  scope = "Pure evidence metadata/schema/snapshot semantics only; no scientific qualification or native work."),
  file.path(out,"RESULTS.json"),auto_unbox=TRUE,pretty=TRUE,null="null",digits=NA)
ok <- function(name, value) {
  results[[length(results)+1L]] <<- list(name=name,passed=isTRUE(value))
  save(if (isTRUE(value)) "running" else "failed")
  if (!isTRUE(value)) stop(name,call.=FALSE)
}
refuse <- function(name, expr) {
  caught <- tryCatch({force(expr);NULL},error=function(e)conditionMessage(e))
  results[[length(results)+1L]] <<- list(name=name,passed=is.character(caught),refusal=caught)
  save(if(is.character(caught))"running"else"failed")
  if(!is.character(caught)) stop(name,call.=FALSE)
}
file <- file.path(root,"registry","method-evidence-0.1.json")
hash <- digest::digest(file=file,algo="sha256")
x <- brohn_method_evidence_read(file,hash); registry <- x$registry
ok("Actual seeded registry parses and validates",length(registry$claims)==24L && length(registry$sources)==29L)
ok("All seeded claims remain screened and unresolved",all(vapply(registry$claims,function(c)identical(c$review$state,"screened")&&identical(c$review$applicability,"unresolved"),logical(1))))
ok("Metadata read hash equals exact original file hash",identical(x$ref$sha256,hash))
ok("UTF-8 exact source characters are retained",any(grepl("Mej\u00eda",vapply(registry$sources,`[[`,character(1),"authors"))))
tasks <- c("iat-gnb2003-d1/1.0","biat-nosek2014-goodfocal/1.0","aat-keyboard-cue-balanced/1.0","rt-deary-liewald-simple/1.0","rt-deary-liewald-choice/1.0","sciat-brohn-response-window-im100/1.0","gnat-brohn-single-target/1.0")
ok("All seven current exact task profiles have bounded cards",all(vapply(tasks,function(p){m<-brohn_method_evidence_cards(registry,p);m$status=="catalogued"&&length(m$cards)>0L},logical(1))))
ok("Unknown method version has explicit empty evidence",{m<-brohn_method_evidence_cards(registry,"iat-gnb2003-d1/2.0");m$status=="not_catalogued"&&length(m$cards)==0L})
ok("Unknown option cannot inherit known method evidence",length(brohn_method_evidence_cards(registry,tasks[[1]],"/unreviewed_option")$cards)==0L)
ok("Family string cannot inherit versioned evidence",length(brohn_method_evidence_find(registry,"ecg"))==0L)
ok("ECG and PPG modality-specific claims are isolated",!any(vapply(brohn_method_evidence_find(registry,"ecg-neurokit-detected-rr/1.0"),function(c)c$id=="prv-not-hrv",logical(1))))
card <- brohn_method_evidence_card(registry,"eda-relative-prominence")
ok("Source count confers only bibliography completeness",card$bibliography$distinct_publications==2L && card$qualification=="not_supported_by_this_schema" && card$review$applicability=="unresolved")
ok("Card retains exact current value and its computational role",identical(card$binding$current_value,.1)&&card$binding$current_value_role=="computational_default")
ok("Supporting text scope is retained in source cards",card$sources[[1]]$depth=="selected_sections_screened"&&grepl("3.1",card$sources[[1]]$locator,fixed=TRUE))
ok("Temperature card retains site/core/baseline limitations",{t<-brohn_method_evidence_card(registry,"temperature-duration");grepl("ambient or core",t$nonclaims[[1]],fixed=TRUE)&&t$binding$current_value_role=="computational_default"})
ok("Starter binds actual schema and constructor, not invented template version",{s<-brohn_method_evidence_card(registry,"comparison-starter-order");identical(s$method_refs,list("brohn-design/1.0.0"))&&s$binding$kind=="template_field"&&s$binding$input_scope=="brohn_new_design(template=comparison)"})
original_title <- registry$claims[[1]]$claim$title
card$title <- "Changed UI copy"
ok("Editing returned card does not mutate original registry",identical(registry$claims[[1]]$claim$title,original_title))
mutate <- function(f) {r<-registry;f(r)}
refuse("Qualified claim state is not representable",{r<-registry;r$claims[[1]]$review$state<-"qualified";brohn_method_evidence_validate(r)})
refuse("A singleton array cannot masquerade as an enum scalar",{r<-registry;r$claims[[1]]$review$state<-list("screened");brohn_method_evidence_validate(r)})
refuse("Source type must be a scalar string",{r<-registry;r$sources[[1]]$kind<-list("consensus");brohn_method_evidence_validate(r)})
refuse("Evidence source identity must be a scalar string",{r<-registry;r$claims[[1]]$evidence[[1]]$source_id<-list("boucsein-2012");brohn_method_evidence_validate(r)})
refuse("Source count cannot mark exhaustive coverage",{r<-registry;r$coverage$exhaustive<-TRUE;brohn_method_evidence_validate(r)})
refuse("Full-text state cannot replace abstract screening",{r<-registry;r$claims[[1]]$review$state<-"full_text_reviewed";brohn_method_evidence_validate(r)})
refuse("Screening cannot resolve applicability",{r<-registry;r$claims[[1]]$review$applicability<-"reviewed_with_limits";brohn_method_evidence_validate(r)})
refuse("Single source is incomplete bibliography",{r<-registry;r$claims[[1]]$evidence<-r$claims[[1]]$evidence[1];brohn_method_evidence_validate(r)})
refuse("Duplicate links to one source are not two sources",{r<-registry;r$claims[[1]]$evidence[[2]]<-r$claims[[1]]$evidence[[1]];brohn_method_evidence_validate(r)})
refuse("Publication aliases cannot inflate source count",{r<-registry;r$sources[[2]]$publication_id<-r$sources[[1]]$publication_id;brohn_method_evidence_validate(r)})
refuse("Arbitrary labels are not canonical publication IDs",{r<-registry;r$sources[[1]]$publication_id<-"second-name";brohn_method_evidence_validate(r)})
refuse("DOI URL alias cannot masquerade as another canonical ID",{r<-registry;r$sources[[2]]$publication_id<-paste0("https://doi.org/",sub("^doi:","",r$sources[[1]]$publication_id));brohn_method_evidence_validate(r)})
refuse("Uppercase DOI spelling is not canonical",{r<-registry;r$sources[[1]]$publication_id<-toupper(r$sources[[1]]$publication_id);brohn_method_evidence_validate(r)})
refuse("Bare DOI spelling is not canonical",{r<-registry;r$sources[[1]]$publication_id<-sub("^doi:","",r$sources[[1]]$publication_id);brohn_method_evidence_validate(r)})
refuse("PMID with a leading zero is not canonical",{r<-registry;r$sources[[1]]$publication_id<-"pmid:012345";brohn_method_evidence_validate(r)})
ok("Canonical IDs do not claim offline cross-identifier resolution",.brohn_me_publication_id("pmid:22680988")&&.brohn_me_publication_id("doi:10.1111/j.1469-8986.2012.01384.x"))
refuse("Unknown source cannot support a claim",{r<-registry;r$claims[[1]]$evidence[[1]]$source_id<-"absent";brohn_method_evidence_validate(r)})
refuse("Vendor documentation is not an academic source type",{r<-registry;r$sources[[1]]$kind<-"vendor_manual";brohn_method_evidence_validate(r)})
refuse("Bibliographic pointer alone cannot claim screened support",{r<-registry;r$claims[[1]]$evidence[[1]]$depth<-"metadata_only";brohn_method_evidence_validate(r)})
refuse("Supporting text locator cannot be omitted",{r<-registry;r$claims[[1]]$evidence[[1]]$locator<-NULL;brohn_method_evidence_validate(r)})
refuse("Limits cannot be omitted",{r<-registry;r$claims[[1]]$evidence[[1]]$limits<-NULL;brohn_method_evidence_validate(r)})
refuse("Independence cannot be inferred from source count",{r<-registry;r$claims[[1]]$independence$status<-"qualified_by_count";brohn_method_evidence_validate(r)})
refuse("Duplicate exact method/option binding is rejected",{r<-registry;c<-r$claims[[1]];c$id<-"duplicate-option";r$claims[[length(r$claims)+1L]]<-c;brohn_method_evidence_validate(r)})
refuse("Unknown fields cannot smuggle an approval badge",{r<-registry;r$claims[[1]]$approved<-TRUE;brohn_method_evidence_validate(r)})
refuse("Computational setting cannot be labelled academic recommendation",{r<-registry;r$claims[[1]]$binding$current_value_role<-"scientifically_recommended";brohn_method_evidence_validate(r)})
refuse("Required researcher value cannot acquire a fake default",{r<-registry;r$claims[[3]]$binding$current_value<-0.05;brohn_method_evidence_validate(r)})
refuse("Unversioned method alias is refused",{r<-registry;r$claims[[1]]$method_refs<-list("eda-current");brohn_method_evidence_validate(r)})
refuse("Changed science must retain version gate",{r<-registry;r$claims[[1]]$release_gate$scientific_change_requires_new_recipe<-FALSE;brohn_method_evidence_validate(r)})
refuse("Classed values cannot change validation semantics",{r<-registry;r$claims[[1]]$binding$current_value<-structure(.1,class="custom");brohn_method_evidence_validate(r)})
refuse("Pairlists are not JSON containers",{r<-registry;r$claims[[1]]$binding$current_value<-pairlist(a=1);brohn_method_evidence_validate(r)})
refuse("Reference-semantic values are refused",{r<-registry;r$claims[[1]]$binding$current_value<-new.env();brohn_method_evidence_validate(r)})
refuse("Complex values are refused",{r<-registry;r$claims[[1]]$binding$current_value<-1+2i;brohn_method_evidence_validate(r)})
refuse("NaN is not evidence null",{r<-registry;r$claims[[1]]$binding$current_value<-NaN;brohn_method_evidence_validate(r)})
refuse("Unsupported record is not silently carded",brohn_method_evidence_card(registry,"unreviewed-claim"))
selected <- list("cardiac-pnn50-definition","eda-relative-prominence")
snap <- brohn_method_evidence_snapshot(file,hash,selected)
reopened <- brohn_method_evidence_reopen(snap)
ok("Historical reopen retains explicit selection order",identical(lapply(reopened$claims,`[[`,"id"),selected))
ok("Historical reopen retains complete selected claims",identical(reopened$claims[[2]],registry$claims[[1]]))
ok("Historical bibliography is exact, deduplicated and scoped",length(reopened$sources)==4L && identical(reopened$registry_ref,x$ref))
refuse("Freezing requires exact hash",brohn_method_evidence_snapshot(file,NULL,selected))
refuse("Wrong source bytes cannot be frozen",brohn_method_evidence_snapshot(file,paste(rep("0",64),collapse=""),selected))
refuse("Unknown claim cannot be frozen",brohn_method_evidence_snapshot(file,hash,list("absent")))
refuse("Duplicated selected claims cannot be frozen",brohn_method_evidence_snapshot(file,hash,list(selected[[1]],selected[[1]])))
refuse("Historical revision identity cannot be relabelled",{s<-snap;s$registry_ref$revision<-"next";brohn_method_evidence_reopen(s)})
refuse("Whitespace mutation still changes historical bytes",{s<-snap;s$registry_text<-paste0(s$registry_text,"\n");brohn_method_evidence_reopen(s)})
refuse("Selected unknown claim cannot appear on reopen",{s<-snap;s$selected_claim_ids<-list("absent");brohn_method_evidence_reopen(s)})
tmp <- file.path(out,"owned-fixtures");dir.create(tmp,showWarnings=FALSE)
write_raw <- function(name,bytes){p<-file.path(tmp,name);con<-file(p,"wb");writeBin(bytes,con);close(con);p}
bad_utf <- write_raw("invalid-utf8.json",as.raw(c(123,34,120,34,58,34,192,175,34,125)))
refuse("Invalid UTF-8 is refused before parsing",brohn_method_evidence_read(bad_utf))
nul <- write_raw("nul.json",c(charToRaw("{}"),as.raw(0)))
refuse("Embedded NUL is refused",brohn_method_evidence_read(nul))
dup <- sub('"schema":', '"schema":"forged","schema":',x$text,fixed=TRUE)
dup_path <- write_raw("duplicate-key.json",charToRaw(dup))
refuse("Duplicate JSON member names are refused",brohn_method_evidence_read(dup_path))
bom <- write_raw("bom.json",c(as.raw(c(239,187,191)),charToRaw(x$text)))
refuse("UTF-8 BOM is explicitly refused",brohn_method_evidence_read(bom))
large <- write_raw("oversize.json",charToRaw(paste(rep(" ",2L*1024L*1024L+1L),collapse="")))
refuse("Oversized registry is refused",brohn_method_evidence_read(large))
snapshot_json <- jsonlite::toJSON(snap,auto_unbox=TRUE,null="null",digits=NA,pretty=TRUE)
transport <- jsonlite::fromJSON(snapshot_json,simplifyVector=FALSE)
ok("Snapshot JSON transport preserves exact UTF-8 registry bytes",identical(charToRaw(transport$registry_text),charToRaw(x$text))&&identical(brohn_method_evidence_reopen(transport),reopened))
copy <- write_raw("current-copy.json",charToRaw(x$text))
next_text <- sub('"revision": "0.1.0-screened"','"revision": "0.2.0-screened"',x$text,fixed=TRUE)
write_raw("current-copy.json",charToRaw(next_text))
ok("Historical reopen has no dependency on current registry file",identical(brohn_method_evidence_reopen(snap),reopened)&&brohn_method_evidence_read(copy)$ref$revision=="0.2.0-screened")
refuse("Current file change is refused at the original hash",brohn_method_evidence_read(copy,hash))
ok("Original registry file remains byte-identical",identical(digest::digest(file=file,algo="sha256"),hash))
save("passed")
cat(length(results),"pure metadata checks passed in",round(proc.time()[["elapsed"]]-start,3),"seconds\n")
