# The original upload owner is killed after the isolated worker acquired its own
# native guard, during full-source hashing. Only original generated bytes exist.
source("R/platform-load.R");brohn_load(ui=FALSE);source("R/platform-ingestion.R")
local({
  root<-tempfile("brohn-ingestion-handoff-");dir.create(root);root<-normalizePath(root,winslash="/")
  store<-brohn_open_store(file.path(root,"workspace"));brohn_initialise_library(store)
  children<-list();checks<-0L
  on.exit({
    for(child in children)if(child$is_alive()){child$kill_tree();child$wait(2000)}
    brohn_close_store(store)
    actual<-normalizePath(root,winslash="/",mustWork=FALSE)
    stopifnot(startsWith(tolower(actual),paste0(tolower(normalizePath(tempdir(),winslash="/")),"/")),startsWith(basename(actual),"brohn-ingestion-handoff-"))
    unlink(actual,recursive=TRUE,force=TRUE)
  },add=TRUE)
  check<-function(name,ok){if(!isTRUE(ok))stop("Intake handoff QA: ",name);checks<<-checks+1L}
  ready_path<-file.path(root,"owner-ready.json")
  owner<-processx::process$new(brohn_rscript(),c("--vanilla","tests/fixtures/platform-ingestion-child.R","owner",store$root,ready_path,as.character(512*1024^2)),
    env=c("current",R_LIBS_USER=paste(.libPaths(),collapse=.Platform$path.sep)),stdout="|",stderr="|",cleanup_tree=TRUE,windows_hide_window=TRUE)
  children<-c(children,list(owner));deadline<-as.numeric(Sys.time())+30
  while(!file.exists(ready_path)){if(!owner$is_alive()||as.numeric(Sys.time())>deadline)stop(owner$read_all_error());owner$wait(10)}
  ready<-brohn_read_json_file(ready_path);record<-brohn_get_entity(store,"ingestion",ready$id)
  expected_hash<-digest::digest(file=record$body$source_snapshot$path,algo="sha256")
  job<-brohn_claim_job(store,"independent-handoff-worker",60);input<-brohn_ingestion_input(store,job)
  scratch<-file.path(store$root,"scratch","original-handoff");dir.create(scratch,recursive=TRUE)
  request<-file.path(scratch,"request.json");output<-file.path(scratch,"output.json");brohn_write_json_file(input,request)
  worker<-processx::process$new(brohn_rscript(),c("--vanilla","tests/fixtures/platform-ingestion-child.R","analyse",request,scratch,output),
    env=c("current",R_LIBS_USER=paste(.libPaths(),collapse=.Platform$path.sep)),stdout="|",stderr="|",cleanup_tree=TRUE,windows_hide_window=TRUE)
  children<-c(children,list(worker));deadline<-as.numeric(Sys.time())+20
  while(!file.exists(file.path(scratch,"ingestion-hashing.json"))){if(!worker$is_alive()||as.numeric(Sys.time())>deadline)stop(worker$read_all_error());Sys.sleep(.001)}
  check("worker owns the source while hashing is still active",worker$is_alive()&&!file.exists(file.path(scratch,"ingestion-preview.json")))
  owner$kill_tree();owner$wait(2000)
  check("only the original owner exits during child hashing",!owner$is_alive()&&worker$is_alive())
  check("worker native guard still rejects same-size source writes",suppressWarnings(inherits(try({con<-file(record$body$source_snapshot$path,"r+b");close(con)},silent=TRUE),"try-error")))
  worker$wait(30000)
  if(worker$get_exit_status()!=0L)stop(worker$read_all_error())
  result<-brohn_read_json_file(output)
  check("independent worker finishes with the original full hash",identical(result$report$ingestion$source$hash,expected_hash))
  # After the worker closes, the expected SHA is now known. Publication must
  # reject modifications rather than infer integrity from the dead owner.
  path<-record$body$source_snapshot$path
  con<-file(path,"r+b");writeBin(as.raw(255L),con);close(con)
  check("known-hash publication refuses a same-size post-worker mutation",inherits(try(brohn_publish_ingestion(store,result,scratch,job,input,output),silent=TRUE),"try-error")&&
    is.null(brohn_get_entity(store,"dataset",paste0("dataset-",record$id))))
  check("failed publication retains original incoming bytes",file.exists(path)&&file.info(path)$size==512*1024^2)
  cat(checks," actual owner-to-worker handoff checks passed\n",sep="")
})
