source("R/platform-load.R",encoding="UTF-8");brohn_load()
local({
  root<-Sys.getenv("BROHN_INTERVAL_REUSE_QA",tempfile("brohn-interval-reuse-"));dir.create(root,recursive=TRUE,showWarnings=FALSE)
  root<-normalizePath(root,winslash="/",mustWork=TRUE)
  processx::run(brohn_rscript(),c("tests/fixtures/researcher-interval-reuse.R","setup",root,"unknown"),windows_hide_window=TRUE,timeout=300000)
  config<-brohn_read_json_file(file.path(root,"fixture.json"));store<-brohn_open_store(config$workspace);on.exit(brohn_close_store(store))
  checks<-0L;check<-function(label,value){if(!isTRUE(value))stop("Interval reuse QA: ",label);checks<<-checks+1L}
  rejects<-function(expr)inherits(try(force(expr),silent=TRUE),"try-error")
  source<-brohn_signal_annotations(store,config$records$original$annotations_id);target<-brohn_get_entity(store,"signal_view",config$records$target$catalog_id)
  preview<-function(a=0,b=10,s=source,catalog=target,title="Mapped windows")brohn_preview_signal_interval_reuse(store,s$id,s$revision,brohn_hash(s$body),
    catalog$id,catalog$revision,brohn_hash(catalog$body),"segment-1",title,a,b,"Original zero and target ten are the declared matching fixture event.")
  before<-length(brohn_list_entities(store,"signal_annotations"));p<-preview()
  check("preview writes no annotations or scores",length(brohn_list_entities(store,"signal_annotations"))==before&&length(brohn_list_entities(store,"signal_windows"))==0)
  check("every target boundary follows independent +10 translation",identical(vapply(p$intervals,`[[`,numeric(1),"start_s"),c(10,13))&&identical(vapply(p$intervals,`[[`,numeric(1),"end_s"),c(13,16)))
  check("own clocks and target person remain distinct",p$source$table$coordinates$source_time_origin=="99999999999999999"&&p$target$table$coordinates$source_time_origin=="10000000000000003"&&p$target$table$identity$group$participant_id=="target-person")
  check("translation is declared and not verified synchronization",p$mapping$offset_s==10&&identical(p$mapping$synchronization_verified,FALSE))
  negative<-preview(20,3);fractional<-preview(1.25,2.75)
  check("negative and fractional anchors preserve known durations",negative$intervals[[1]]$start_s==-17&&fractional$intervals[[2]]$start_s==4.5&&fractional$intervals[[2]]$end_s-fractional$intervals[[2]]$start_s==3)
  check("out-of-range boundaries are shown without clamping",negative$intervals[[1]]$extent=="outside_observed_extent"&&p$intervals[[2]]$end_s==16&&p$intervals[[2]]$extent=="extends_beyond_observed_extent")
  check("nonfinite or precision-losing mappings rejected",rejects(preview(0,Inf))&&rejects(preview(0,1e20)))
  precise<-brohn_create_signal_annotations(store,config$records$original$catalog_id,"segment-1","Precision and overlap source")
  precise<-brohn_save_signal_interval(store,precise$id,1L,paste0("Baseline ",intToUtf8(956)),"baseline",1,5,"Original Unicode label")
  precise<-brohn_save_signal_interval(store,precise$id,2L,"Overlapping window","task",2.25,5.25,"")
  identity<-preview(1e16,1e16,s=precise)
  check("equal huge anchors preserve both boundaries exactly",identity$mapping$offset_s==0&&identity$intervals[[1]]$start_s==1&&identity$intervals[[1]]$end_s==5&&identity$intervals[[2]]$start_s==2.25)
  check("unrepresentable offset or boundary rejected despite preserved duration",rejects(preview(1,1e16,s=precise))&&rejects(preview(0,1e16,s=precise)))
  overlap<-preview(0,10,s=precise)
  check("Unicode labels and intentional overlap survive translation",identical(overlap$intervals[[1]]$label,precise$body$intervals[[1]]$label)&&overlap$intervals[[2]]$start_s==12.25&&overlap$intervals[[1]]$end_s==15)
  unknown<-brohn_get_entity(store,"signal_view",config$records$unknown$catalog_id)
  unknown_preview<-preview(catalog=unknown)
  check("actual all-missing target coordinates retain unknown extent",all(vapply(unknown_preview$intervals,function(i)i$extent=="unknown_target_extent",logical(1))))
  forged<-p;forged$intervals[[1]]$end_s<-12
  check("altered preview rejected even with recomputed supplied digest",rejects(brohn_apply_signal_interval_reuse(store,forged,brohn_hash(forged))))
  check("wrong preview digest rejected",rejects(brohn_apply_signal_interval_reuse(store,p,paste(rep("a",64),collapse=""))))
  applied<-brohn_apply_signal_interval_reuse(store,p,brohn_hash(p))
  check("apply creates fresh set and window identities",applied$id!=source$id&&applied$revision==1L&&!any(brohn_ids(applied$body$intervals)%in%brohn_ids(source$body$intervals)))
  check("target origin and identity bind the new set",applied$body$origin=="imported"&&applied$body$report_id==config$records$target$report_id&&applied$body$table$identity$group$session_id=="target-session")
  check("copy retains exact original revision and mapping provenance",applied$body$reuse$source$annotation$hash==brohn_hash(source$body)&&applied$body$reuse$preview_hash==brohn_hash(p)&&applied$body$reuse$intervals[[1]]$source_interval_id==source$body$intervals[[1]]$id)
  check("no source computed scores or review approvals copied",!any(c("summary","analysis","reviewed","approved","participant_id","session_id")%in%names(applied$body)))
  queued<-brohn_queue_signal_windows(store,applied$id,1L,brohn_hash(applied$body),list("measure"));claim<-brohn_claim_job(store,"interval-reuse-qa",90)
  stopifnot(identical(queued$id,claim$id));brohn_process_job(store,claim,timeout_seconds=90);done<-brohn_get_job(store,queued$id)
  if(done$status!="succeeded")stop(brohn_json(done$error));summary<-brohn_get_entity(store,"signal_windows",done$result$signal_windows_id);rows<-summary$body$summary$summaries
  check("actual supervised calculation reads only new target values",identical(vapply(rows,`[[`,numeric(1),"mean"),c(0,40))&&rows[[2]]$standard_deviation_sample==20)
  check("target zero missing excluded support remain distinct",rows[[1]]$eligible_rows==1&&rows[[1]]$missing_value_rows==1&&rows[[1]]$excluded_support_rows==1&&is.null(rows[[1]]$standard_deviation_sample))
  check("target summary uses its own person and clock",summary$body$summary$table$identity$group$participant_id=="target-person"&&summary$body$summary$table$coordinates$source_time_origin=="10000000000000003")
  absent<-brohn_apply_signal_interval_reuse(store,negative,brohn_hash(negative))
  empty_job<-brohn_queue_signal_windows(store,absent$id,1L,brohn_hash(absent$body),list("measure"));empty_claim<-brohn_claim_job(store,"interval-reuse-empty",90)
  stopifnot(identical(empty_job$id,empty_claim$id));brohn_process_job(store,empty_claim,timeout_seconds=90);empty_done<-brohn_get_job(store,empty_job$id)
  if(empty_done$status!="succeeded")stop(brohn_json(empty_done$error));empty<-brohn_get_entity(store,"signal_windows",empty_done$result$signal_windows_id)$body$summary$summaries
  check("actual outside-target summaries retain null rather than invented zero",all(vapply(empty,function(r)r$status=="no_eligible_samples"&&r$selected_rows==0&&r$eligible_rows==0&&is.null(r$mean)&&is.null(r$standard_deviation_sample),logical(1))))
  frozen<-brohn_hash(summary$body);current<-brohn_save_signal_interval(store,source$id,source$revision,"Before changed","baseline",0,2,"Source edited after preview",source$body$intervals[[1]]$id)
  check("source edit after preview prevents delayed apply",rejects(brohn_apply_signal_interval_reuse(store,p,brohn_hash(p))))
  old<-preview(s=source);old_applied<-brohn_apply_signal_interval_reuse(store,old,brohn_hash(old))
  check("explicitly reviewed historical source version remains reusable",old_applied$body$reuse$source$annotation$revision==3L&&old_applied$body$intervals[[1]]$end_s==13)
  stale_target<-preview(s=current);changed<-target$body;changed$title<-"Updated catalog metadata"
  brohn_put_entity(store,"signal_view",target$id,changed,expected_revision=target$revision)
  check("target catalog edit after preview prevents delayed apply",rejects(brohn_apply_signal_interval_reuse(store,stale_target,brohn_hash(stale_target))))
  target<-brohn_get_entity(store,"signal_view",target$id)
  foreign<-brohn_put_entity(store,"signal_view","foreign-catalog",target$body,project_id="foreign-project")
  check("foreign target cannot receive this project's intervals",rejects(preview(s=current,catalog=foreign)))
  project<-brohn_project(store,"default");closed<-project$body;closed$archived<-TRUE
  brohn_put_entity(store,"project","default",closed,expected_revision=project$revision)
  check("project revocation prevents reuse",rejects(preview(s=current)))
  brohn_put_entity(store,"project","default",project$body,expected_revision=project$revision+1L)
  check("original and target scientific reports unchanged",brohn_hash(brohn_get_entity(store,"report",config$records$original$report_id)$body)==config$records$original$report_hash&&brohn_hash(brohn_get_entity(store,"report",config$records$target$report_id)$body)==config$records$target$report_hash&&brohn_hash(brohn_get_entity(store,"signal_windows",summary$id)$body)==frozen)
  brohn_close_store(store);store<-brohn_open_store(config$workspace)
  check("reopen preserves target source and exact reuse provenance",brohn_hash(brohn_signal_annotations(store,applied$id)$body)==brohn_hash(applied$body))
  brohn_write_json_file(list(passed=TRUE,checks=checks,fixture=config,applied_id=applied$id,summary_id=summary$id),file.path(root,"acceptance.json"))
  cat(checks," interval reuse checks passed; evidence ",root,"\n",sep="")
})
