source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=TRUE)
source("R/platform-task-plots.R");source("R/platform-task-plot-views.R")
source("tests/fixtures/original-task-plots-store.R")
local({
  n<-0L;check<-function(ok,label){if(!isTRUE(ok))stop(label,call.=FALSE);n<<-n+1L;cat("PASS",label,"\n")}
  rejects<-function(expr)inherits(try(force(expr),silent=TRUE),"try-error")
  edge<-brohn_task_plot_selection(list(kind="trials",rows=lapply(c(0,1,1+1e-9,20),function(x)list(first_response_ms=x))))
  check(edge$bins[[1L]]$count==2L&&edge$bins[[2L]]$count==1L&&edge$bins[[20L]]$count==1L,"Exact histogram boundaries do not fuzz a just-above-edge value into the preceding bin")
  store<-brohn_open_store(tempfile("brohn-task-plots-"));on.exit(brohn_close_store(store),add=TRUE);brohn_initialise_library(store)
  f<-brohn_original_task_plot_fixture(store)
  open<-function(r)brohn_task_plot_report(store,r$id,r$revision,brohn_hash(r$body),r$project_id)
  load<-function(r,id=NULL){o<-open(r);brohn_task_plot_load(store,o,brohn_default(id,o$catalog[[1L]]$id))}
  for(name in names(f$imported)){
    r<-f$imported[[name]];m<-load(r);a<-r$body$analysis$task_attempts[[1L]];v<-brohn_task_plot_selection(m)
    check(length(m$rows)==length(a$trial_audit)&&length(v$values)==length(a$trial_audit),paste(name,"every frozen position is plotted, including unscored positions"))
    check(sum(vapply(v$bins,`[[`,numeric(1),"count"))==v$available,paste(name,"distribution accounts for all selected original values"))
    check(identical(lapply(m$rows,`[[`,"first_response_ms_source"),lapply(a$responses,`[[`,"first_response_ms_source")),paste(name,"original latency lexemes survive without display rounding"))
    html<-as.character(.brohn_tp_view_ui(v));check(grepl('role="img"',html,fixed=TRUE)&&!grepl("<script",html,fixed=TRUE),paste(name,"accessible figure and numerical source render"))
  }
  m<-load(f$imported$iat);v<-brohn_task_plot_selection(m);final<-brohn_task_plot_selection(m,"final_correct_ms")
  check(any(v$values!=final$values,na.rm=TRUE),"First-response and final-correct latency remain independently selectable")
  check(length(brohn_task_plot_selection(m,scope="scored")$rows)<length(m$rows),"Explicit scored-position filter preserves complete original source separately")
  truncated<-f$imported$iat$body$analysis$task_attempts[[1L]];truncated$trial_audit<-head(truncated$trial_audit,50L);truncated$responses<-head(truncated$responses,50L)
  check(rejects(brohn_task_plot_attempt(truncated)),"A truncated fifty-row trial preview cannot produce a complete chronology")
  m<-load(f$partial);v<-brohn_task_plot_selection(m,scope="scored")
  check(v$available==1L&&v$missing==39L&&v$values[[1L]]==500,"One correct and39 omissions are not40 zero-valued latencies")
  m<-load(f$incomplete);check(tail(m$rows,1L)[[1L]]$derived_missing&&is.null(tail(m$rows,1L)[[1L]]$first_response_ms),"Absent source row retains its expected position and missing reason")
  check(grepl("definition is unknown",as.character(.brohn_tp_view_ui(brohn_task_plot_selection(load(f$unknown)))),fixed=TRUE),"Unknown timing is explicitly disclosed beside declared numbers")
  m<-load(f$cohort,"metric:correct_test_rt_sd");v<-brohn_task_plot_selection(m)
  check(length(m$rows)==3L&&v$available==2L&&v$missing==1L&&m$summary$contributing_person_count==2L,"Cohort SD dots use metric-specific people; unsupported partial person remains present")
  m<-load(f$cohort,"metric:correct_test_rt_mean")
  check(m$summary$mean==168&&length(m$rows)==3L&&m$rows[[1L]]$value==1,"Repeats remain one saved person value; no trial/session pooled average is invented")
  check(brohn_task_plot_selection(m)$measure=="correct_test_rt_mean","Person exports name the actual cohort metric instead of a trial latency")
  bad<-f$cohort$body$analysis;bad$per_person<-bad$per_person[-1L]
  check(rejects(brohn_task_plot_people(bad,"correct_test_rt_mean")),"A truncated person array cannot masquerade as a complete cohort plot")
  m<-load(f$native);v<-brohn_task_plot_selection(m,scope="scored")
  check(length(m$rows)==48L&&v$available==1L&&v$missing==39L&&m$evidence_level=="brohn_journal_replayed","Native source opens complete replayed journal with exact report binding")
  bad<-f$native$body;bad$provenance$runs[[1L]]$events_hash<-brohn_hash("different events");r<-f$publish(bad)
  check(rejects(load(r)),"A report with mismatched journal identity cannot display another source")
  # A packed preview must never be used as trial data or hide native sources.
  packed<-f$native$body;packed$analysis<-list(schema="brohn-questionnaire-report-preview/1.0",kind="questionnaire",task_scores=list())
  check(identical(.brohn_tp_catalog(packed),.brohn_tp_catalog(f$native$body)),"Native catalog is independent of bounded questionnaire task-score previews")
  view<-brohn_task_plot_selection(load(f$imported$iat));path<-tempfile(fileext=".csv");brohn_task_plot_csv(view,path);data<-brohn_read_table(path,"csv",20000L)
  check(nrow(data)==length(view$rows)&&identical(brohn_hash(brohn_parse(data$exact_record_json[[nrow(data)]])),brohn_hash(tail(view$rows,1L)[[1L]])),"CSV includes every selected trial plus exact typed final source row")
  check(identical(brohn_hash(brohn_task_plot_export(view)$complete_source$rows),brohn_hash(view$model$rows)),"JSON export retains all source rows independently of selected filters")
  server<-function(input,output,session){state<-shiny::reactiveValues(page="report",report_id=f$imported$iat$id,error=NULL)
    attempt<-function(fn,...)tryCatch(fn(),error=function(e){state$error<-conditionMessage(e);NULL})
    plots<-brohn_install_task_plots(input,output,session,store,state,attempt,function(fn)fn())}
  shiny::testServer(server,{
    r<-f$imported$iat;cmd<-list(report_id=r$id,revision=r$revision,report_hash=brohn_hash(r$body),project_id=r$project_id)
    session$setInputs(open_task_plots=cmd);session$setInputs(task_plot_prepare_ack=plots$pending()$token);check(!is.null(plots$opened()),"Explicit report action opens verified complete-source catalog")
    session$setInputs(task_plot_catalog_identity=cmd$report_hash,task_plot_source=plots$opened()$catalog[[1L]]$id,task_plot_load=1L)
    session$setInputs(task_plot_prepare_ack=plots$pending()$token)
    if(!is.null(state$error))stop(state$error)
    m<-plots$model();session$setInputs(task_plot_identity=brohn_hash(list(m$report_hash,m$id,m$source_hash)),task_plot_measure="first_response_ms",task_plot_scope="all",task_plot_page=2L)
    check(length(plots$selected()$rows)==length(m$rows)&&grepl("Page 2",output$task_plot_view$html,fixed=TRUE),"Table paging leaves full chart source intact")
    state$unrelated_refresh<-1L;session$flushReact();check(input$task_plot_page==2L&&identical(plots$model()$source_hash,m$source_hash),"Unrelated refresh preserves source and table state")
    session$setInputs(task_plot_identity="stale");check(inherits(try(plots$selected(),silent=TRUE),"try-error"),"Earlier source controls cannot act on the current model")
    state$page<-"home";session$flushReact();check(is.null(plots$model())&&is.null(plots$opened()),"Leaving report clears its complete source and plot state")
    state$page<-"report";session$setInputs(open_task_plots=cmd);session$setInputs(task_plot_prepare_ack=plots$pending()$token);session$flushReact()
    p<-brohn_project(store,r$project_id);p$body$archived<-TRUE;brohn_put_entity(store,"project",p$id,p$body,expected_revision=p$revision,project_id=p$id)
    check(rejects(plots$guard())&&is.null(plots$model())&&is.null(plots$opened()),"Project authority loss clears source and model immediately when checked")
  })
  cat("PASS",n,"complete task plot and Shiny checks\n")
})
