# Independent configuration/access policy boundaries. No fake identity headers
# here are a substitute for the separate actual OIDC browser integration.
source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=FALSE)
source("R/platform-hosted-profile.R",encoding="UTF-8")
local({
  args<-commandArgs(trailingOnly=TRUE);folder<-normalizePath(if(length(args))args[[1L]]else tempfile("brohn-hosted-domain-"),winslash="/",mustWork=FALSE)
  stopifnot(startsWith(basename(folder),"brohn-hosted-domain-"),!dir.exists(folder));dir.create(folder,recursive=TRUE)
  store<-brohn_open_store(file.path(folder,"workspace"));on.exit(brohn_close_store(store),add=TRUE);brohn_initialise_library(store)
  checks<-character();check<-function(label,ok){stopifnot(isTRUE(ok));checks<<-c(checks,label);cat("PASS",label,"\n")};rejects<-function(x)inherits(try(force(x),silent=TRUE),"try-error")
  secret<-brohn_token();secret_file<-file.path(folder,"edge.secret");writeChar(secret,secret_file,eos=NULL,useBytes=TRUE)
  rev_file<-file.path(folder,"revocations.json");rev<-list(schema="brohn-hosted-revocations/1.0",subjects=list(),not_before=0);brohn_write_json_file(rev,rev_file)
  raw<-list(schema="brohn-hosted-profile/1.0",id="original-local-test",mode="local_oidc_fixture",workspace_root=store$root,workspace_id=store$workspace_id,project_id="default",researcher_origin="https://localhost:3911",participant_origin="https://localhost:3912",issuer="http://127.0.0.1:3913/realms/brohn",allowed_groups=list("researchers"),edge_secret_file=secret_file,revocations_file=rev_file,session_seconds=600,enrollment_seconds=60,upload_seconds=120,resource_seconds=120,researcher_port=3914,participant_port=3915,oauth_port=3916)
  p<-brohn_validate_hosted_profile(raw);now<-as.numeric(Sys.time())
  req<-list(HTTP_HOST="localhost:3911",HTTP_X_FORWARDED_PROTO="https",HTTP_X_BROHN_EDGE=secret,HTTP_X_FORWARDED_USER="original-subject",HTTP_X_FORWARDED_GROUPS="researchers",HTTP_ORIGIN=p$researcher_origin)
  ctx<-brohn_hosted_context(req,p,now);bound<-brohn_hosted_bind_store(store,p,ctx)
  check("Valid one-team profile binds exact workspace and stable OIDC identity",identical(brohn_hosted_actor(bound)$subject,"original-subject"))
  check("Local mode and native operator stores remain unbound",is.null(brohn_hosted_profile(""))&&is.null(brohn_hosted_context(list(),NULL))&&brohn_hosted_require_session(store))
  for(key in c("HTTP_X_BROHN_EDGE","HTTP_X_FORWARDED_USER","HTTP_X_FORWARDED_GROUPS","HTTP_HOST","HTTP_X_FORWARDED_PROTO","HTTP_ORIGIN")) {
    bad<-req;bad[[key]]<-if(key=="HTTP_X_FORWARDED_USER")"ambiguous subject"else"forged";check(paste("Invalid",key,"refused"),rejects(brohn_hosted_context(bad,p)))
  }
  check("Missing verified identity refused",rejects(brohn_hosted_context(list(),p)))
  check("Absolute researcher lease expires at exact boundary",rejects(.brohn_hosted_context_valid(ctx,p,now+600)))
  rev$subjects<-list(ctx$subject);brohn_write_json_file(rev,rev_file);check("Operator subject revocation invalidates existing context",rejects(brohn_hosted_require_session(bound)))
  rev$subjects<-list();rev$not_before<-now+1;brohn_write_json_file(rev,rev_file);check("Operator epoch revocation invalidates existing context",rejects(brohn_hosted_require_session(bound)))
  rev$not_before<-0;brohn_write_json_file(rev,rev_file)
  for(action in c("server_folder_import","backup","resume_workspace"))check(paste("Remote",action,"requires operator"),rejects(brohn_hosted_require_action(bound,action)))
  check("Foreign project refused",rejects(brohn_hosted_require_project(bound,"foreign")))
  bad<-p;bad$workspace_id<-"other";check("Restored/foreign workspace identity refused",rejects(brohn_hosted_bind_store(store,bad,ctx)))
  bad<-raw;bad$participant_origin<-bad$researcher_origin;check("Shared researcher/participant origin refused",rejects(brohn_validate_hosted_profile(bad)))
  bad<-raw;bad$mode<-"isolated_team";check("Local IdP fixture cannot masquerade as public deployment",rejects(brohn_validate_hosted_profile(bad)))
  bad<-raw;bad$issuer<-"https://user:password@example.test/realm";check("Issuer credentials refused",rejects(brohn_validate_hosted_profile(bad)))
  bad<-raw;bad$unknown<-TRUE;check("Unknown security settings refused",rejects(brohn_validate_hosted_profile(bad)))
  participant<-brohn_hosted_bind_store(store,p,participant=TRUE)
  rreq<-req;rreq$HTTP_HOST<-"localhost:3912";rreq$HTTP_ORIGIN<-p$participant_origin
  check("Participant edge accepts exact independent origin",brohn_hosted_participant_request(participant,rreq))
  check("Researcher origin cannot call participant service",rejects(brohn_hosted_participant_request(participant,req)))
  brohn_hosted_register_release(bound,"release-original",now)
  brohn_hosted_register_run(participant,"run-original","release-original",now+30)
  check("Enrollment expiry exact boundary refuses new starts",rejects(brohn_hosted_require_release(participant,"release-original","enroll",now+60)))
  check("Admitted upload survives enrollment expiry",brohn_hosted_require_run(participant,"run-original",now+61))
  check("Upload expiry exact boundary refuses late receipt",rejects(brohn_hosted_require_run(participant,"run-original",now+150)))
  check("Materials have separate exact resource deadline",brohn_hosted_require_release(participant,"release-original","resource",now+179)&&rejects(brohn_hosted_require_release(participant,"release-original","resource",now+180)))
  brohn_hosted_revoke(bound,"release","release-original",now+40)
  check("Release revocation stops entry while admitted uploads retain policy",rejects(brohn_hosted_require_release(participant,"release-original","entry",now+41))&&brohn_hosted_require_run(participant,"run-original",now+41))
  brohn_hosted_revoke(bound,"run","run-original",now+42)
  check("Individual run revocation stops uploads",rejects(brohn_hosted_require_run(participant,"run-original",now+43)))
  check("Unadmitted local runs/releases cannot inherit hosted access",rejects(brohn_hosted_require_run(participant,"absent",now))&&rejects(brohn_hosted_require_release(participant,"absent","entry",now)))
  check("Audit attribution contains stable identity without credentials",!grepl(secret,brohn_json(brohn_hosted_actor(bound)),fixed=TRUE)&&identical(brohn_hosted_actor(bound)$issuer,p$issuer))
  brohn_write_json_file(list(schema="brohn-hosted-domain-acceptance/1.0",passed=TRUE,checks=as.list(checks),limits=list("Direct policy tests; actual proxy, OIDC, browser and worker proof is separate.")),file.path(folder,"results.json"))
})
