source("R/platform-load.R", encoding = "UTF-8"); brohn_load()
local({
  checks <- 0L
  check <- function(name, value) {if (!isTRUE(value)) stop(paste("Signal QA failed:", name), call. = FALSE); checks <<- checks+1L}
  rejects <- function(expr) inherits(try(force(expr), silent = TRUE), "try-error")
  root <- tempfile("brohn-signal-qa-"); dir.create(root); root <- normalizePath(root, winslash = "/")
  store <- brohn_open_store(file.path(root, "workspace")); brohn_initialise_library(store)
  on.exit({brohn_close_store(store); actual <- normalizePath(root, winslash = "/", mustWork = FALSE)
    stopifnot(startsWith(tolower(actual), paste0(tolower(normalizePath(tempdir(), winslash = "/")), "/")), startsWith(basename(actual), "brohn-signal-qa-"))
    unlink(actual, recursive = TRUE, force = TRUE)}, add = TRUE)
  fixture <- paste("import importlib.util,json,sys; from pathlib import Path",
    "s=importlib.util.spec_from_file_location('preview_test','tests/workers/signal_preview.py'); m=importlib.util.module_from_spec(s); s.loader.exec_module(m)",
    "p=m.Preview(); p.root=Path(sys.argv[1]); request=p.artifact([p.table([5,1,None,100,4,8,2],retained=[True,True,True,False,True,True,True])])",
    "(p.root/'fixture.json').write_text(json.dumps(request),encoding='utf-8')", sep = "\n")
  processx::run(brohn_python_profile("eda"), c("-c", fixture, root), windows_hide_window = TRUE)
  fixture <- brohn_read_json_file(file.path(root, "fixture.json")); a <- fixture$artifact
  object <- brohn_store_object(store, path = a$path, media_type = "application/x-ndjson")
  id <- brohn_id("report"); body <- list(id = id, title = "Original support fixture", origin = "sample", status = "Available",
    analysis = list(artifacts = list(c(list(kind = a$kind), object, a[c("schema", "tables", "rows", "provenance_sha256", "complete")])), artifact_verification = fixture$verification_receipt))
  report <- brohn_put_entity(store, "report", id, body, expected_revision = 0L, project_id = "default")
  original_hash <- brohn_hash(report$body)
  run_job <- function(job) {
    force(job)
    claimed <- brohn_claim_job(store, "signal-qa", lease_seconds = 60)
    stopifnot(identical(claimed$id, job$id)); brohn_process_job(store, claimed, timeout_seconds = 60)
    finished <- brohn_get_job(store, job$id)
    if (!identical(finished$status, "succeeded")) stop(brohn_json(finished$error))
    brohn_get_entity(store, "signal_view", finished$result$signal_view_id)
  }
  catalog_job <- brohn_queue_signal_view(store, id, a$kind)
  check("catalog requests deduplicate exact report and artifact", brohn_queue_signal_view(store, id, a$kind)$id == catalog_job$id)
  catalog <- run_job(catalog_job); d <- catalog$body$view$tables[[1L]]
  check("actual queued catalog reports complete table metadata", d$rows == 7 && d$identity$channel == "eda" && identical(as.numeric(unlist(d$coordinate_range)), c(0,6)))
  check("native origin string stays exact", identical(d$coordinates$source_time_origin, "99999999999999999"))
  check("catalog has explicit complete pagination", catalog$body$view$pagination$total_tables == 1 && is.null(catalog$body$view$pagination$next_offset))
  check("view has loaded code and artifact reader hashes", all(c("R/platform-signal.R", "scripts/workers/signal_preview.py", "scripts/workers/physiology_artifacts.py") %in% names(catalog$body$processing$code_hashes)))
  choice <- fixture$selection
  preview <- run_job(brohn_queue_signal_view(store, id, a$kind, choice, max_bins = 1L)); v <- preview$body$view
  check("full source row count survives bounded view", v$full_range$rows == 7 && v$selected_range$eligible_value_rows == 5)
  check("missing and excluded support stays separate", v$selected_range$missing_value_rows == 1 && v$selected_range$excluded_retention_rows == 1)
  check("excluded large value does not alter eligible extrema", identical(as.numeric(unlist(v$selected_range$eligible_value_range)), c(1,8)) && identical(as.numeric(unlist(v$selected_range$observed_value_range)), c(1,100)))
  check("gap breaks a one-bin view into two fragments", length(v$fragments) == 2 && v$quality$envelope_rows == 5)
  check("R roundtrip preserves first min max last support order", identical(unlist(lapply(v$envelopes, function(b) vapply(b$points, `[[`, numeric(1), "y")), use.names = FALSE), c(5,1,4,8,2)))
  svg <- as.character(brohn_signal_svg(v))
  check("SVG draws two distinct lines, not a line through missing support", lengths(regmatches(svg, gregexpr("<polyline", svg, fixed = TRUE))) == 2L)
  check("chart exposes title description and coordinate units", grepl('role="img"', svg, fixed = TRUE) && grepl("eligible observations", svg, fixed = TRUE) && grepl("Time (s)", svg, fixed = TRUE))
  check("numeric support accompanies plotted envelopes", grepl("Exact source and selected signal support", as.character(brohn_signal_plot_ui(preview)), fixed = TRUE))
  ranged <- choice; ranged$range <- list(4,6)
  bounded <- run_job(brohn_queue_signal_view(store,id,a$kind,ranged,max_bins=1L))
  check("inclusive range does not replace full denominator", bounded$body$view$selected_range$rows == 3 && bounded$body$view$full_range$rows == 7 && identical(as.numeric(unlist(bounded$body$view$selected_range$eligible_value_range)), c(2,8)))
  empty <- choice; empty$range <- list(10,20)
  unavailable <- run_job(brohn_queue_signal_view(store,id,a$kind,empty))
  check("empty range has no invented SVG or zero score", unavailable$body$view$status == "empty_range" && is.null(brohn_signal_svg(unavailable$body$view)) && grepl("No eligible observations",as.character(brohn_signal_plot_ui(unavailable)),fixed=TRUE))
  reversed <- choice; reversed$range <- list(2,1)
  check("invalid ranges fail before queueing", rejects(brohn_queue_signal_view(store,id,a$kind,reversed)))
  forged <- choice; forged$table_ids <- list("not-in-the-source")
  bad <- brohn_queue_signal_view(store,id,a$kind,forged); claim <- brohn_claim_job(store,"signal-qa",lease_seconds=60); brohn_process_job(store,claim,timeout_seconds=60)
  check("invented table is an explicit failed view", brohn_get_job(store,bad$id)$status == "failed" && grepl("absent",brohn_get_job(store,bad$id)$error$message,fixed=TRUE))
  check("original scientific report stays byte-identical", identical(brohn_hash(brohn_get_entity(store,"report",id)$body),original_hash) && length(brohn_list_entities(store,"report")) == 1L)
  check("saved view never leaks private worker paths", !grepl(root,brohn_json(preview$body),fixed=TRUE) && !grepl('"path"',brohn_json(preview$body),fixed=TRUE))
  download <- file.path(root,"download.json"); brohn_copy_object_download(store,preview$body$result_object$hash,download)
  check("download preserves saved view bytes", digest::digest(file=download,algo="sha256") == preview$body$result_object$hash)
  fence_choice <- choice; fence_choice$range <- list(0,2)
  fence_job <- brohn_queue_signal_view(store,id,a$kind,fence_choice); fence <- brohn_claim_job(store,"signal-qa",lease_seconds=60)
  input <- brohn_signal_input(store,fence); scratch <- file.path(root,"fence"); dir.create(scratch)
  out <- list(report=brohn_analyse_signal(input,scratch),code_identity=list()); path <- file.path(scratch,"output.json"); brohn_write_json_file(out,path)
  before <- length(brohn_list_entities(store,"signal_view")); wrong <- input; wrong$report_hash <- "wrong"
  check("fenced publication rejects substituted report", rejects(brohn_publish_signal_view(store,out,scratch,fence,wrong,path)))
  stale <- fence; stale$token <- "stale"; check("stale lease cannot publish view", rejects(brohn_publish_signal_view(store,out,scratch,stale,input,path)))
  invisible(brohn_cancel_job(store,fence$id)); check("cancelled view cannot publish", rejects(brohn_publish_signal_view(store,out,scratch,fence,input,path)) && length(brohn_list_entities(store,"signal_view")) == before)
  server <- function(input,output,session) {
    state <- shiny::reactiveValues(page="report",report_id=id,error=NULL,status=NULL)
    attempt <- function(fn) tryCatch(fn(),error=function(e) {state$error <- conditionMessage(e);NULL})
    message <- function(text) state$status <- text
    brohn_install_signal_server(input,output,session,store,state,attempt,message,function(fn) fn())
  }
  shiny::testServer(server,{
    session$flushReact()
    session$setInputs(open_signal_catalog=list(report_id=id,report_hash=original_hash,kind=a$kind)); session$flushReact()
    check("actual explorer action shows saved catalog", grepl("Choose a signal view",output$signal_catalog$html,fixed=TRUE))
    session$setInputs(signal_form_identity=paste(id,catalog$id,sep=":"),signal_table=d$table_id);session$flushReact()
    check("typed table drives actual measure choices", grepl("measure (uS)",output$signal_measure_controls$html,fixed=TRUE))
    session$setInputs(signal_measure_identity=paste(catalog$id,d$table_id,sep=":"),signal_measure="measure",signal_full_range=TRUE,create_signal_preview=1L)
    pending <- brohn_queue_signal_view(store,id,a$kind,choice); actual <- run_job(pending)
    session$flushReact(); session$elapse(1200); session$flushReact()
    check("actual preview UI shows immutable plot and full support",grepl("Processed signal chart",output$signal_plot$html,fixed=TRUE) && grepl("original origin: 99999999999999999",output$signal_plot$html,fixed=TRUE))
    check("real Shiny JSON download reproduces saved view",digest::digest(file=output$signal_json_download,algo="sha256")==actual$body$result_object$hash)
    check("real Shiny SVG download is accessible vector content",grepl('<svg',paste(readLines(output$signal_svg_download,warn=FALSE),collapse=""),fixed=TRUE))
    session$setInputs(signal_measure_identity="old-table",create_signal_preview=2L)
    check("stale table controls cannot queue a different signal",grepl("Wait for this recording",state$error,fixed=TRUE))
    state$report_id <- "unavailable-report";session$flushReact()
    session$setInputs(open_signal_catalog=list(report_id=id,report_hash=original_hash,kind=a$kind))
    check("stale report commands are rejected",grepl("Reopen this report",state$error,fixed=TRUE))
  })
  check("all derived views leave full source bytes intact",digest::digest(file=brohn_object_path(store,object$hash),algo="sha256")==object$hash)
  brohn_close_store(store); store <- brohn_open_store(file.path(root,"workspace"))
  check("saved plot survives workspace reopen", identical(brohn_hash(brohn_get_entity(store,"signal_view",preview$id)$body),brohn_hash(preview$body)))
  cat(sprintf("PASS: %d processed-signal R checks (actual worker, provenance, extrema, support, fencing, Shiny, downloads, restart)\n",checks))
})
