for(module in c("platform-core","platform-store","platform-methods","platform-library","platform-question-flow","platform-shell","platform-data-views","platform-question-flow-views","platform-app"))
  source(paste0("R/",module,".R"),encoding="UTF-8")
local({
  checks <- 0L
  check <- function(name,value) {if(!isTRUE(value)) stop(paste("Question-flow QA failed:",name),call.=FALSE); checks <<- checks+1L}
  rejected <- function(expr) inherits(try(force(expr),silent=TRUE),"try-error")
  d <- brohn_new_design("Original compound question-flow fixture")
  d$stimuli <- lapply(d$stimuli,function(s) {s$content <- "Original fictional stimulus for flow testing"; s})
  q1 <- brohn_question("Choose a typed code","single_choice","before","q-one")
  q1$options <- list(list(id="number-one",label="Numeric one",value=1),list(id="text-one",label="Text one",value="1"),
    list(id="false",label="Boolean false",value=FALSE),list(id="zero",label="Numeric zero",value=0))
  q2 <- brohn_question("Choose multiple typed codes","multiple_choice","before","q-two"); q2$options <- q1$options
  q3 <- brohn_question("Give an explicit number","number","before","q-three")
  q4 <- brohn_question("Describe this stimulus","text","after_each","q-four")
  q5 <- brohn_question("Explain your response","long_text","end","q-five")
  d$questions <- list(q1,q2,q3,q4,q5); brohn_validate_design(d)
  check("end questions cannot refer to stimulus-specific answers",identical(brohn_ids(brohn_flow_earlier(d,q5$id)),c(q1$id,q2$id,q3$id)))
  check("first question has no earlier answers",length(brohn_flow_earlier(d,q1$id))==0L)
  false <- brohn_flow_condition(q1,"equals","option","false")
  string <- brohn_flow_condition(q2,"contains","option","text-one")
  greater <- brohn_flow_condition(q3,"greater","typed",value_type="number",value=4)
  zero <- brohn_flow_condition(q2,"contains","option","zero")
  rule <- list(op="and",rules=list(false,list(op="or",rules=list(string,greater)),list(op="not",rule=zero)))
  designed <- brohn_flow_set_question(d,q5$id,rule)
  check("typed boolean and string option values survive authoring",identical(false$value,FALSE) && identical(string$value,"1"))
  check("compound rule evaluates actual nested logic",brohn_rule(rule,list("q-one"=FALSE,"q-two"=list("1",1),"q-three"=3)))
  check("typed zero exclusion works inside not",!brohn_rule(rule,list("q-one"=FALSE,"q-two"=list("1",0),"q-three"=3)))
  check("contains does not coerce number to text",!brohn_rule(rule,list("q-one"=FALSE,"q-two"=list(1),"q-three"=3)))
  check("contains does not coerce false to zero",!brohn_rule(zero,list("q-two"=list(FALSE,"0"))))
  check("contains preserves mixed nested matrix answer types",brohn_rule(zero,list("q-two"=list(row1=list(0),row2=NULL))) &&
    !brohn_rule(zero,list("q-two"=list(row1=list("0"),row2=FALSE))))
  near <- list(op="equals",question_id=q3$id,value=1)
  check("numeric equality is exact like the browser",!brohn_rule(near,list("q-three"=1+1e-10)) && brohn_rule(near,list("q-three"=1L)))
  check("not_equals retains missing-answer behavior",!brohn_rule(list(op="not_equals",question_id=q3$id,value=1),list()))
  check("text and numeric scalar equality stay distinct",!brohn_rule(near,list("q-three"="1")))
  check("boolean and numeric scalar equality stay distinct",!brohn_rule(false,list("q-one"=0)))
  check("threshold cannot be boolean or text",rejected(brohn_flow_condition(q3,"greater","typed",value_type="text",value="4")))
  check("new scalar comparison cannot target a vector answer",rejected(brohn_flow_condition(q2,"equals","typed",value_type="number",value=1)))
  imported_scalar <- list(op="equals",question_id=q2$id,value=1)
  check("unsupported imported comparison is preserved when untouched",identical(brohn_flow_condition(q2,"equals","typed",value_type="number",value=1,existing=imported_scalar),imported_scalar))
  check("editing imported incompatible comparison requires meaningful operation",rejected(brohn_flow_condition(q2,"equals","typed",value_type="number",value=2,existing=imported_scalar)))
  check("unavailable answer cannot be referenced",rejected(brohn_flow_set_question(d,q5$id,list(op="answered",question_id=q4$id))))
  check("readable summary includes labels and explicit types",grepl("Boolean false",brohn_flow_summary(rule,d$questions),fixed=TRUE) && grepl("(text)",brohn_flow_summary(rule,d$questions),fixed=TRUE))
  moved <- brohn_flow_move(rule,c(2L,2L),-1L)
  check("keyboard reorder preserves condition identities",identical(moved$rules[[2]]$rules[[1]],greater) && identical(moved$rules[[2]]$rules[[2]],string))
  removed <- brohn_flow_remove(rule,c(3L,1L))
  check("removing a sole negated child removes its empty wrapper",identical(removed$rules,rule$rules[1:2]))
  check("removing the root restores always-show",is.null(brohn_flow_remove(rule,integer())))
  check("not wraps the selected subtree without dropping children",identical(brohn_flow_kind(rule,"not")$rule,rule))
  check("and-to-or keeps its ordered children",identical(brohn_flow_kind(rule,"or")$rules,rule$rules))
  check("compiler retains executable compound AST",identical(Filter(function(s) identical(s$question$id,q5$id),brohn_compile(designed)$timeline)[[1L]]$question$show_if,rule))
  ranking <- brohn_question("Rank options","ranking","before","q-ranking")
  ranked <- brohn_flow_condition(ranking,"contains","option",ranking$options[[1]]$id)
  check("ranking membership uses recorded option identities",identical(ranked$value,ranking$options[[1]]$id))
  hostile <- designed; hostile$questions[[1]]$prompt <- "<script>original()</script>"
  check("logic summary HTML escapes researcher text",!grepl("<script>",as.character(brohn_question_logic_summary_ui(hostile,hostile$questions[[5]])),fixed=TRUE))

  root <- tempfile("brohn-flow-qa-"); dir.create(root); root <- normalizePath(root,winslash="/")
  store <- brohn_open_store(file.path(root,"workspace")); brohn_initialise_library(store)
  on.exit({brohn_close_store(store); actual <- normalizePath(root,winslash="/",mustWork=FALSE)
    stopifnot(startsWith(tolower(actual),paste0(tolower(normalizePath(tempdir(),winslash="/")),"/")),grepl("^brohn-flow-qa-",basename(actual)))
    unlink(actual,recursive=TRUE,force=TRUE)},add=TRUE)
  saved <- brohn_put_entity(store,"study",designed$id,designed,project_id=designed$project_id)
  server <- function(input,output,session) {
    current <- new.env(parent=emptyenv()); current$study <- saved
    state <- shiny::reactiveValues(page="study",stage="Questions",error=NULL,status=NULL)
    attempt <- function(fn) {state$error <- NULL; tryCatch(fn(),error=function(e) {state$error <- conditionMessage(e); NULL})}
    capture <- function() invisible(NULL)
    update_study <- function(design) current$study <- brohn_save_study(store,design,current$study$revision)
    message <- function(text) state$status <- text
    api <- brohn_install_question_flow_server(input,output,session,current,state,capture,update_study,attempt,message)
  }
  shiny::testServer(server,{
    session$setInputs(question_flow_open=q5$id)
    session$flushReact(); context <- api$context()
    check("actual Shiny tree displays imported all/any/not rules",grepl("All conditions",output$question_flow_tree$html,fixed=TRUE) &&
      grepl("Any condition",output$question_flow_tree$html,fixed=TRUE) && grepl("Move down",output$question_flow_tree$html,fixed=TRUE))
    session$setInputs(flow_select=list(editor_id=context$editor_id,version=context$version,path=list(2L,2L)))
    session$flushReact()
    session$setInputs(flow_node_identity=api$node_identity(),flow_kind="condition",flow_question=q3$id,flow_leaf_op="greater",
      flow_value_source="typed",flow_value_type="number",flow_number=5,flow_apply=1L)
    check("editing a threshold changes only the draft",is.null(state$error) && brohn_flow_get(api$draft(),c(2L,2L))$value==5 && current$study$revision==saved$revision)
    session$setInputs(save_question_flow=list(editor_id=api$context()$editor_id))
    check("Save publishes edited compound rule to one study revision",is.null(state$error) && current$study$revision==saved$revision+1L && current$study$body$questions[[5]]$show_if$rules[[2]]$rules[[2]]$value==5)
    session$setInputs(question_flow_open=q5$id); session$flushReact(); context <- api$context()
    session$setInputs(flow_add=list(editor_id=context$editor_id,version=context$version))
    session$flushReact()
    session$setInputs(flow_node_identity=api$node_identity(),flow_kind="condition",flow_question=q1$id,flow_leaf_op="equals",
      flow_value_source="option",flow_option="false",flow_value_type="number",flow_number=0)
    session$setInputs(save_question_flow=list(editor_id=api$context()$editor_id))
    check("Save includes the current unapplied condition with its typed option code",is.null(state$error) && length(current$study$body$questions[[5]]$show_if$rules)==4L &&
      identical(current$study$body$questions[[5]]$show_if$rules[[4]]$value,FALSE))
    session$setInputs(question_flow_open=q5$id); session$flushReact(); context <- api$context(); before <- brohn_hash(current$study$body)
    session$setInputs(flow_clear=list(editor_id=context$editor_id,version=context$version))
    session$setInputs(cancel_question_flow=list(editor_id=context$editor_id))
    check("Cancel discards cleared-rule draft and disables later saves",identical(before,brohn_hash(current$study$body)) && !api$context()$active)
    session$setInputs(save_question_flow=list(editor_id=context$editor_id))
    check("late Save after Cancel cannot alter a study",!is.null(state$error) && identical(before,brohn_hash(current$study$body)))
    session$setInputs(question_flow_open=q5$id); session$flushReact(); context <- api$context()
    session$setInputs(flow_move=list(editor_id=context$editor_id,version=context$version,path=list(4L),direction=-1L))
    check("actual ordered-tree command moves a condition",is.null(state$error) && identical(api$draft()$rules[[3]]$value,FALSE))
    session$setInputs(flow_remove=list(editor_id=context$editor_id,version=context$version,path=list(1L)))
    check("stale tree command cannot address a newly moved draft",grepl("draft changed",state$error,fixed=TRUE) && length(api$draft()$rules)==4L)
    changed <- current$study$body; changed$questions[[3]]$prompt <- "New wording while editor was open"; update_study(changed)
    session$setInputs(save_question_flow=list(editor_id=api$context()$editor_id))
    check("concurrent question edits block stale rule publication",grepl("study changed",state$error,fixed=TRUE) && current$study$body$questions[[3]]$prompt==changed$questions[[3]]$prompt)
    current$study <- brohn_archive_study(store,current$study$id,TRUE,current$study$revision)
    session$setInputs(question_flow_open=q5$id)
    check("archived studies reject display-logic editing",grepl("Restore",state$error,fixed=TRUE))
  })
  cat(sprintf("PASS: %d question flow assertions (typed rules, scope boundaries, compiler preservation, real Shiny draft/save/reorder/cancel)\n",checks))
})
