# Actual launcher/doctor failures must precede workspace creation or job claims.
source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=FALSE)
source("scripts/doctor.R",encoding="UTF-8")
source("scripts/runtime-dependencies.R",encoding="UTF-8")
local({
  if(.Platform$OS.type!="windows")stop("This readiness qualification requires Windows.")
  checks<-0L
  check<-function(name,ok){if(!isTRUE(ok))stop("Publication readiness QA: ",name,call.=FALSE);checks<<-checks+1L}
  failure<-function(expr)tryCatch({force(expr);NULL},error=function(e)conditionMessage(e))
  root<-tempfile("brohn-publication-readiness-");dir.create(root);root<-normalizePath(root,winslash="/")
  prior<-Sys.getenv(c("BROHN_PUBLICATION_NATIVE_MANIFEST","BROHN_PUBLICATION_PYTHON"),unset=NA_character_)
  on.exit({
    for(key in names(prior))if(is.na(prior[[key]]))Sys.unsetenv(key)else do.call(Sys.setenv,setNames(list(prior[[key]]),key))
    actual<-normalizePath(root,winslash="/",mustWork=FALSE)
    stopifnot(identical(dirname(actual),normalizePath(tempdir(),winslash="/")),startsWith(basename(actual),"brohn-publication-readiness-"))
    unlink(actual,recursive=TRUE,force=TRUE)
  },add=TRUE)
  project<-normalizePath(".",winslash="/");library<-normalizePath(.libPaths()[[1]],winslash="/")
  manifest_path<-normalizePath(Sys.getenv("BROHN_PUBLICATION_NATIVE_MANIFEST","../../work/tooling/brohn-native/publication-guard.json"),winslash="/",mustWork=TRUE)
  manifest<-jsonlite::fromJSON(manifest_path,simplifyVector=FALSE)
  rscript<-file.path(R.home("bin"),"Rscript.exe")
  baseline<-brohn_doctor_publication(project)
  check("prepared guard and actual bounded Python process are ready",baseline$status=="ready" && isTRUE(baseline$required) && isTRUE(baseline$native_seal) && baseline$python_probe$platform=="nt" && baseline$python_probe$pointer_bytes==8L)
  check("build identity includes exact R ABI headers and compiler closure",identical(baseline$native_build$build_key,manifest$build_key) && length(manifest$build_inputs$r_headers)>5L && length(manifest$build_inputs$compiler_distribution)>5L && identical(manifest$build_inputs$r_dll_sha256,digest::digest(file=file.path(R.home("bin"),"R.dll"),algo="sha256")))
  check("missing core reports publication uninspected",brohn_doctor_publication(project,FALSE)$status=="not_checked")
  absent<-file.path(root,"absent-native.json")
  Sys.setenv(BROHN_PUBLICATION_NATIVE_MANIFEST=absent)
  missing<-brohn_doctor_publication(project)
  check("explicit missing native manifest never borrows prepared fallback",missing$status=="not_ready" && missing$component=="native_guard" && grepl("build-publication-guard",missing$action,fixed=TRUE))
  fresh<-file.path(root,"must-not-create-workspace")
  message<-failure(brohn_start_services(fresh,3948L))
  check("service startup fails before creating workspace or child services",!is.null(message) && grepl("Report publication is not ready",message,fixed=TRUE) && !dir.exists(fresh))
  message<-failure(brohn_require_runtime(project,library))
  check("default launcher gives actionable publisher failure",!is.null(message) && grepl("report publisher needs attention",message,fixed=TRUE) && grepl("build-publication-guard",message,fixed=TRUE))
  store<-brohn_open_store(file.path(root,"queued-workspace"));on.exit(brohn_close_store(store),add=TRUE)
  queued<-brohn_enqueue_job(store,"original-no-claim-fixture",list(origin="sample"),"readiness-fixture")
  snapshot<-brohn_get_job(store,queued$id)
  worker<-processx::run(rscript,c("--vanilla","scripts/run-worker.R","--root",store$root,"--once"),
    env=c("current",R_LIBS_USER=library,BROHN_PUBLICATION_NATIVE_MANIFEST=absent),timeout=30,error_on_status=FALSE,cleanup_tree=TRUE,windows_hide_window=TRUE)
  check("actual worker rejects missing guard before claiming saved job",worker$status!=0L && grepl("Report publication is not ready",worker$stderr,fixed=TRUE) && identical(snapshot,brohn_get_job(store,queued$id)))
  machine<-processx::run(rscript,c("--vanilla","scripts/doctor.R","--library",library,"--profiles","none","--json"),
    env=c("current",R_LIBS_USER=library,BROHN_PUBLICATION_NATIVE_MANIFEST=absent),timeout=60,error_on_status=FALSE,cleanup_tree=TRUE,windows_hide_window=TRUE)
  report<-jsonlite::fromJSON(machine$stdout,simplifyVector=FALSE)
  check("actual doctor returns nonzero structured mandatory publisher status",machine$status==1L && report$core$status=="ready" && report$status=="not_ready" && report$publication$status=="not_ready" && isTRUE(report$publication$required))
  altered_path<-file.path(root,"altered-native.json")
  altered<-function(key,value){m<-manifest;m[[key]]<-value;jsonlite::write_json(m,altered_path,auto_unbox=TRUE,pretty=TRUE,null="null",digits=NA);Sys.setenv(BROHN_PUBLICATION_NATIVE_MANIFEST=altered_path);brohn_doctor_publication(project)}
  check("another R runtime cannot reuse guard manifest",altered("r_version","0.0.0")$component=="native_guard")
  check("another architecture cannot reuse guard manifest",altered("architecture","original-wrong-arch")$component=="native_guard")
  check("changed C source identity cannot reuse guard manifest",altered("source_sha256",paste(rep("0",64),collapse=""))$component=="native_guard")
  m<-manifest;m$build_inputs$compiler_sha256<-paste(rep("0",64),collapse="")
  jsonlite::write_json(m,altered_path,auto_unbox=TRUE,pretty=TRUE,null="null",digits=NA)
  check("altered compiler build identity cannot reuse existing DLL",brohn_doctor_publication(project)$component=="native_guard")
  Sys.setenv(BROHN_PUBLICATION_NATIVE_MANIFEST=manifest_path,BROHN_PUBLICATION_PYTHON=file.path(root,"missing-python.exe"))
  python_missing<-brohn_doctor_publication(project)
  check("Python failure offers Python configuration without compiler rebuild",python_missing$status=="not_ready" && python_missing$component=="publication_python" && grepl("BROHN_PUBLICATION_PYTHON",python_missing$action,fixed=TRUE) && !grepl("build-publication",python_missing$action,fixed=TRUE))
  Sys.setenv(BROHN_PUBLICATION_PYTHON=rscript)
  invalid<-brohn_doctor_publication(project)
  check("existing non-Python executable cannot report ready",invalid$status=="not_ready" && invalid$component=="publication_python")
  Sys.setenv(BROHN_PUBLICATION_PYTHON=baseline$python)
  check("correcting exact dependencies restores readiness",brohn_doctor_publication(project)$status=="ready")
  check("read-only probes leave queued job unchanged",identical(snapshot,brohn_get_job(store,queued$id)))
  cat(sprintf("PASS: %d publication readiness checks; actual doctor and worker failure paths, exact build identity, no claims or implicit restore.\n",checks))
})
