source("R/platform-core.R");source("R/platform-publication.R")
local({
  root<-tempfile("brohn-native-build-qa-");dir.create(root);root<-normalizePath(root,winslash="/")
  old_python<-Sys.getenv("BROHN_PUBLICATION_PYTHON",unset=NA_character_);old_manifest<-Sys.getenv("BROHN_PUBLICATION_NATIVE_MANIFEST",unset=NA_character_)
  on.exit({
    if(is.na(old_python))Sys.unsetenv("BROHN_PUBLICATION_PYTHON") else Sys.setenv(BROHN_PUBLICATION_PYTHON=old_python)
    if(is.na(old_manifest))Sys.unsetenv("BROHN_PUBLICATION_NATIVE_MANIFEST") else Sys.setenv(BROHN_PUBLICATION_NATIVE_MANIFEST=old_manifest)
    actual<-normalizePath(root,winslash="/",mustWork=FALSE)
    stopifnot(identical(dirname(actual),normalizePath(tempdir(),winslash="/")),startsWith(basename(actual),"brohn-native-build-qa-"))
    unlink(actual,recursive=TRUE,force=TRUE)
  },add=TRUE)
  checks<-0L;check<-function(name,value){if(!isTRUE(value))stop("Native build QA: ",name);checks<<-checks+1L}
  ready<-brohn_publication_readiness()
  check("actual native DLL and Windows Python pass bounded probe",isTRUE(ready$ready)&&isTRUE(ready$native_seal)&&grepl("^3\\.",ready$python_version))
  Sys.setenv(BROHN_PUBLICATION_NATIVE_MANIFEST=file.path(root,"absent.json"))
  failed<-brohn_publication_readiness()
  check("missing native build has explicit compiler recovery",!failed$ready&&failed$component=="native_guard"&&grepl("build-publication-guard",failed$action))
  if(is.na(old_manifest))Sys.unsetenv("BROHN_PUBLICATION_NATIVE_MANIFEST") else Sys.setenv(BROHN_PUBLICATION_NATIVE_MANIFEST=old_manifest)
  fake<-file.path(root,"not-python.exe");writeLines("Original non-executable fixture",fake);Sys.setenv(BROHN_PUBLICATION_PYTHON=fake)
  failed<-brohn_publication_readiness()
  check("existing non-executable Python does not pass readiness",!failed$ready&&failed$component=="publication_python"&&grepl("BROHN_PUBLICATION_PYTHON",failed$action))
  if(is.na(old_python))Sys.unsetenv("BROHN_PUBLICATION_PYTHON") else Sys.setenv(BROHN_PUBLICATION_PYTHON=old_python)
  compiler_root<-file.path(root,"compiler");dir.create(compiler_root)
  original_compiler<-normalizePath("../../work/tooling/tinycc-0.9.27/tcc",winslash="/")
  stopifnot(all(file.copy(list.files(original_compiler,full.names=TRUE,all.files=TRUE,no..=TRUE),compiler_root,recursive=TRUE)))
  compiler<-file.path(compiler_root,"tcc.exe");output<-file.path(root,"build")
  build<-function(executable=compiler,destination=output)processx::run(file.path(R.home("bin"),"Rscript.exe"),c("--vanilla","scripts/build-publication-guard.R",executable,destination),
    env=c("current",R_LIBS_USER=paste(.libPaths(),collapse=.Platform$path.sep)),timeout=90,error_on_status=FALSE,cleanup_tree=TRUE,windows_hide_window=TRUE)
  first<-build();check("actual fresh build compiles and validates symbols",first$status==0L&&!isTRUE(first$timeout))
  a<-jsonlite::fromJSON(file.path(output,"publication-guard.json"),simplifyVector=FALSE);target<-file.path(output,a$dll);stamp<-file.info(target)$mtime
  second<-build();b<-jsonlite::fromJSON(file.path(output,"publication-guard.json"),simplifyVector=FALSE)
  check("matching full build inputs reuse the existing exact DLL",second$status==0L&&identical(a,b)&&identical(file.info(target)$mtime,stamp))
  writeLines("Original compiler context revision",file.path(compiler_root,"original-build-context.txt"))
  third<-build();c<-jsonlite::fromJSON(file.path(output,"publication-guard.json"),simplifyVector=FALSE)
  check("compiler distribution changes receive a distinct build identity",third$status==0L&&c$build_key!=a$build_key&&c$dll!=a$dll&&file.exists(target))
  check("build identity retains exact R ABI and header inventory",length(c$build_inputs$r_headers)>10L&&identical(c$build_inputs$r_dll_sha256,digest::digest(file=file.path(R.home("bin"),"R.dll"),algo="sha256")))
  # An original deliberately failing compiler creates a partial -o file, then
  # exits nonzero. Only its private pending directory may contain those bytes.
  failing_root<-file.path(root,"failing-compiler");dir.create(failing_root)
  stub<-file.path(failing_root,"original.c")
  writeLines('#include <stdio.h>\nint main(int argc,char **argv){int i;for(i=1;i<argc;i++)if(argv[i][0]==\'-\'&&argv[i][1]==\'o\'){FILE*f=fopen(argv[i]+2,"wb");if(f){fputs("original partial DLL",f);fclose(f);}}return 7;}',stub)
  stub_exe<-file.path(failing_root,"original-failing-compiler.exe")
  compile<-processx::run(compiler,c(stub,paste0("-o",stub_exe)),timeout=10,error_on_status=FALSE,windows_hide_window=TRUE)
  stopifnot(compile$status==0L)
  failed_output<-file.path(root,"failed-build");failed<-build(stub_exe,failed_output)
  check("failing compiler cannot publish a partial final DLL or manifest",failed$status!=0L&&!file.exists(file.path(failed_output,"publication-guard.json"))&&
    !length(list.files(failed_output,pattern="\\.dll$",recursive=TRUE)))
  check("failed native build removes its exact private pending directory",!length(list.files(failed_output,all.files=TRUE,no..=TRUE)))
  damaged<-file.path(output,c$dll);writeLines("Original deliberate corrupted local build",damaged)
  rejected<-build()
  check("existing damaged build cannot be relabelled or silently reused",rejected$status!=0L&&identical(jsonlite::fromJSON(file.path(output,"publication-guard.json"),simplifyVector=FALSE),c))
  cat("Native publication build and readiness:",checks,"checks passed.\n")
})
