# Synthetic saved-observation contract only; actual Windows storage/publication.
# No model inference, camera, participant or physiological qualification.
source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=FALSE)
source("R/platform-vision-explorer.R",encoding="UTF-8")
args<-commandArgs(trailingOnly=TRUE);stopifnot(length(args)==1L,!dir.exists(args[[1]]))
local({
  folder<-normalizePath(args[[1]],winslash="/",mustWork=FALSE);dir.create(folder,recursive=TRUE)
  store<-brohn_open_store(file.path(folder,"workspace"));brohn_initialise_library(store);views<-list();checks<-character()
  on.exit({for(v in views)try(brohn_close_vision_index(v),silent=TRUE);brohn_close_store(store)})
  check<-function(ok,label){if(!isTRUE(ok))stop(label);checks<<-c(checks,label);cat("PASS",label,"\n");flush.console()}
  rejected<-function(expression)inherits(tryCatch({force(expression);NULL},error=identity),"error")
  source_dir<-file.path(folder,"original");dir.create(source_dir)
  code<-paste("import importlib.util,sys,json;from pathlib import Path;spec=importlib.util.spec_from_file_location('oracle','tests/workers/vision_explorer.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);p=Path(sys.argv[1]);r=m.fixture(p);(p/'fixture.json').write_text(json.dumps(r))")
  processx::run(.brohn_publication_python(),c("-B","-c",code,source_dir),windows_hide_window=TRUE)
  f<-brohn_read_json_file(file.path(source_dir,"fixture.json"));asset<-brohn_store_object(store,bytes=charToRaw("Original synthetic source identity, not decoded video"),media_type="video/mp4")
  artifact<-brohn_store_object(store,path=f$artifact_path,media_type="application/x-ndjson")
  d<-list(id="dataset-original-vision",modality="video",origin="sample",source=c(asset,list(format="mp4",filename="original-synthetic.mp4")),metadata=list(origin_statement="Independent synthetic saved-observation storage fixture",profile="face_geometry_v1"))
  dataset<-brohn_put_entity(store,"dataset",d$id,d,project_id="default")
  body<-list(id="report-original-vision",dataset_id=d$id,origin="sample",title="Original synthetic geometry artifact",provenance=brohn_analysis_provenance(d,dataset$revision),
    analysis=list(schema="brohn-vision-result/1.0",kind="video",source=list(sha256=asset$hash,bytes=asset$size),parameters=f$parameters,engine=f$engine,
      quality=c(f$quality,list(pts_validated=TRUE,identity_tracking=FALSE)),artifacts=list(c(list(kind="vision-observations"),artifact))))
  body$result_object<-brohn_store_object(store,bytes=charToRaw(enc2utf8(brohn_json(list(schema="brohn-analysis-output/1.0",report=body)))),media_type="application/json")
  report<-brohn_put_entity(store,"report",body$id,body,project_id="default");hash<-brohn_hash(body)
  queue<-function(rebuild=FALSE)brohn_queue_vision_index(store,report$id,report$revision,hash,"default",rebuild)
  prepare<-function(rebuild=FALSE){q<-queue(rebuild);j<-brohn_claim_job(store,"original-vision-storage",300);stopifnot(identical(q$id,j$id));input<-brohn_vision_index_input(store,j)
    scratch<-file.path(store$root,"scratch",paste0(j$id,"-attempt-",j$attempt));dir.create(scratch,recursive=TRUE);value<-brohn_analyse_vision_index(input,scratch)
    paths<-c("R/platform-publication.R",names(.brohn_vexplorer_loaded),"scripts/workers/publication.py","src/publication_guard.c")
    output<-list(schema="brohn-analysis-output/1.0",code_identity=stats::setNames(lapply(paths,function(p)digest::digest(file=p,algo="sha256")),paths),report=value)
    path<-file.path(scratch,"output.json");brohn_write_json_file(output,path);list(job=j,input=input,scratch=scratch,output=output,path=path)}
  publish<-function(p)brohn_publish_vision_index(store,p$output,p$scratch,p$job,p$input,p$path)
  open_view<-function(receipt){v<-brohn_open_vision_index(store,receipt$result$vision_index_id,receipt$result$index_hash,report$id,report$revision,hash,"default");views[[length(views)+1L]]<<-v;v}
  first<-prepare();receipt<-publish(first);v<-open_view(receipt)
  check(identical(receipt$status,"succeeded")&&identical(v$record$body$processing$publication$mode,"staged-windows-parent-read-seal/1.0"),"Actual staged native publication saves a completed source-bound index")
  page<-brohn_vision_index_read(store,v,"page",list(metric="face.blendshape.jawOpen",limit=2L));detail<-brohn_vision_index_read(store,v,"detail",list(frame_index=5L))
  check(page$total==7&&page$rows[[1]]$value_text=="2.500000000000000000e-1"&&detail$observation$face$landmarks[[1]]$z=="-0.125","Actual R/child reader preserves original numeric lexemes and native detail")
  second<-brohn_vision_index_read(store,v,"page",list(metric="face.blendshape.jawOpen",limit=2L,cursor=page$next_cursor))
  check(second$rows[[1]]$frame_index==7L,"Source-bound cursor reads the next complete frame page")
  check(rejected(brohn_vision_index_read(store,v,"page",list(metric="face.lip_separation_image_width",cursor=page$next_cursor))),"Cursor cannot cross metric selections")
  plotted<-brohn_vision_index_read(store,v,"plot",list(channel="face",metric="face.blendshape.jawOpen"))
  check(length(plotted$fragments)==2L&&plotted$support$metric_valid_time_s_text=="0.2000","Plot preserves absent/invalid gaps and exact adjacent support")
  altered<-v;altered$context$report_hash<-paste(rep("b",64),collapse="")
  check(rejected(brohn_vision_index_read(store,altered,"catalog")),"Public context tampering cannot change retained read authority")
  altered<-v;altered$record$body$manifest$frames<-8L
  check(rejected(brohn_vision_index_read(store,altered,"catalog")),"Public record tampering cannot change retained read authority")
  check(identical(queue()$id,first$job$id),"Identical prepare reuses the completed frozen request")
  paths<-vapply(v$authority$guards,function(g)g$path,character(1));probe<-function(path){p<-processx::run(.brohn_publication_python(),c("-B","-c","import sys;f=open(sys.argv[1],'r+b');f.close()",path),error_on_status=FALSE,windows_hide_window=TRUE);p$status}
  # Registered objects have a read-only attribute too. Remove it before the
  # before/during/after controls, so the native sharing seal is actually tested.
  brohn_close_vision_index(v);for(path in paths)Sys.chmod(path,"0666")
  check(all(vapply(paths,probe,integer(1))==0L),"Writable control succeeds before any native read guard")
  v<-open_view(receipt);check(all(vapply(paths,probe,integer(1))!=0L),"Native guards deny writes to index and retained sources during read")
  check(rejected(brohn_check_vision_index_context(store,v,report$id,report$revision,hash,"another-project")),"A different project cannot read this opened source")
  brohn_close_vision_index(v);check(all(vapply(paths,probe,integer(1))==0L),"Native guards release every owned file on close")
  check(rejected(brohn_vision_index_read(store,v,"catalog")),"Closed retained authority cannot be used again")
  begin_view<-function()brohn_begin_vision_index_open(store,receipt$result$vision_index_id,receipt$result$index_hash,report$id,report$revision,hash,"default")
  pending<-begin_view()
  check(rejected(brohn_vision_index_read(store,pending$opened,"catalog")),"Pending background verification cannot read the index")
  brohn_cancel_vision_index_open(pending)
  check(all(vapply(paths,probe,integer(1))==0L)&&rejected(brohn_poll_vision_index_open(store,pending)),"Cancelled background verification releases guards and cannot be adopted")
  pending<-begin_view();pending$process$wait(120000);adopted<-brohn_poll_vision_index_open(store,pending);views[[length(views)+1L]]<-adopted
  check(isTRUE(adopted$authority$verified)&&brohn_vision_index_read(store,adopted,"catalog")$manifest$frames==7L,"Successful asynchronous verification adopts a fresh qualified view")
  check(rejected(brohn_vision_index_read(store,pending$opened,"catalog")),"The original pending handle remains unqualified after adoption")
  brohn_cancel_vision_index_open(pending)
  check(rejected(brohn_poll_vision_index_open(store,pending))&&brohn_vision_index_read(store,adopted,"catalog")$manifest$frames==7L&&all(vapply(paths,probe,integer(1))!=0L),"Cancel or duplicate poll after adoption cannot close the active view")
  brohn_close_vision_index(adopted)
  reopened<-open_view(receipt);check(brohn_vision_index_read(store,reopened,"catalog")$manifest$frames==7L,"Saved completed index reopens from original publication receipts")
  brohn_close_vision_index(reopened)
  cancelled<-prepare(TRUE);brohn_cancel_job(store,cancelled$job$id)
  check(rejected(publish(cancelled))&&brohn_get_job(store,cancelled$job$id)$status=="cancelled","Cancelled build cannot publish its prepared index")
  rebuilt<-prepare(TRUE);new_receipt<-publish(rebuilt)
  check(new_receipt$result$vision_index_id!=receipt$result$vision_index_id&&identical(new_receipt$result$artifact_hash,receipt$result$artifact_hash),"Explicit rebuild keeps a new receipt and reuses identical immutable index bytes")
  check(identical(brohn_hash(brohn_get_entity(store,"report",report$id)$body),hash),"Browsing, cancellation and rebuild preserve the original report")
  brohn_write_json_file(list(checks=checks,qualification="synthetic artifact plus actual native storage, no inference",workspace=store$root),file.path(folder,"results.json"))
  cat("PASS",length(checks),"vision explorer storage checks\n")
})
