# Domain contracts use a direct native result; actual guarded jobs are separate.
source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=TRUE)
source("R/platform-audio-extraction.R",encoding="UTF-8");source("R/platform-audio-extraction-views.R",encoding="UTF-8")
args<-commandArgs(trailingOnly=TRUE);stopifnot(length(args)<=1L)
folder<-if(length(args))args[[1L]]else tempfile("brohn-audio-extraction-domain-")
stopifnot(startsWith(basename(folder),"brohn-audio-extraction-domain-"))
if(!length(args))stopifnot(dir.create(folder))
folder<-normalizePath(folder,winslash="/",mustWork=TRUE)
checks<-character();check<-function(label,x){if(!isTRUE(x))brohn_write_json_file(list(passed=FALSE,failed=label,checks=as.list(checks)),file.path(folder,"failure.json"));stopifnot(isTRUE(x));checks<<-c(checks,label);cat("PASS",label,"\n")}
rejects<-function(expr)inherits(try(force(expr),silent=TRUE),"try-error")
local({
  media<-file.path(folder,"media");dir.create(media);python<-brohn_python_profile("audio")
  processx::run(python,c("tests/fixtures/audio-extraction-media.py",media),timeout=120,windows_hide_window=TRUE)
  originals<-brohn_read_json_file(file.path(media,"media.json"))$hashes
  store<-brohn_open_store(file.path(folder,"workspace"));on.exit(brohn_close_store(store),add=TRUE);brohn_initialise_library(store)
  d<-brohn_ingest_dataset(store,file.path(media,"multiple.mkv"),"Original multi-track video","video",origin="sample")
  ref<-.brohn_ax_ref(d);source<-brohn_audio_extraction_source(store,d$id,d$revision,ref$hash,d$project_id)
  check("Unmapped standalone video retains its exact source and absent study",is.null(source$dataset$body$study_id)&&length(source$source_refs)==1L)
  check("Source hash and foreign project substitutions fail",rejects(brohn_audio_extraction_source(store,d$id,d$revision,paste(rep("0",64),collapse=""),d$project_id))&&rejects(brohn_audio_extraction_source(store,d$id,d$revision,ref$hash,"foreign")))
  request<-brohn_prepare_audio_extraction(store,d$id,d$revision,ref$hash,d$project_id);job<-list(operation="audio_tracks",request=request)
  input<-brohn_audio_extraction_input(store,job);scratch<-file.path(folder,"inspect");dir.create(scratch)
  result<-brohn_analyse_audio_extraction(input,scratch)$audio_extraction
  check("Actual native inventory contains both original audio streams and no derived data",identical(vapply(result$tracks,function(t)as.numeric(t$stream_index),numeric(1)),c(1,2))&&length(result$artifacts)==0L)
  save_result<-function(id,request,result,artifacts=list(),derived_id=NULL){body<-list(schema="brohn-saved-audio-extraction/1.0",id=id,parent_dataset_id=request$dataset$id,
    derived_dataset_id=derived_id,study_id=request$study_id,origin=request$origin,request=request,result=result,artifacts=artifacts,created_at=brohn_now(),processing=list(origin="domain_fixture_not_saved_worker"))
    body$result_object<-brohn_store_object(store,bytes=charToRaw(brohn_json(body)),media_type="application/json");brohn_put_entity(store,"audio_extraction",id,body,project_id=request$project_id)}
  catalog<-save_result("audio-extraction-job-domain-catalog",request,result)
  req<-brohn_prepare_audio_extraction(store,d$id,d$revision,ref$hash,d$project_id,"audio_extract",.brohn_ax_ref(catalog),2)
  extract<-list(operation="audio_extract",request=req);actual<-brohn_audio_extraction_input(store,extract)
  check("Explicit second stream and exact saved inventory are bound",actual$binding$selection$stream_index==2L&&length(actual$source_objects)==2L)
  check("Missing/non-audio stream cannot be selected",rejects(brohn_prepare_audio_extraction(store,d$id,d$revision,ref$hash,d$project_id,"audio_extract",.brohn_ax_ref(catalog),0)))
  for(field in c("origin","source_hash")){bad<-extract;bad$request[[field]]<-"changed";check(paste("Substituted",field,"fails current source preparation"),rejects(brohn_audio_extraction_input(store,bad)))}
  outdir<-file.path(folder,"extract");dir.create(outdir);native<-brohn_analyse_audio_extraction(actual,outdir)$audio_extraction
  oracle<-processx::run(python,c("tests/fixtures/audio-extraction-media.py",media,"--verify",file.path(outdir,"artifacts","audio.wav")),timeout=30,windows_hide_window=TRUE)
  check("All 288000 decoded values independently equal original PCM16 bytes",brohn_parse(oracle$stdout)$passed&&native$recording$samples_per_channel==144000)
  ledger<-utils::read.csv(file.path(outdir,"artifacts","audio-frames.csv"),colClasses="character")
  check("Complete frame ledger preserves contiguous original sample support",as.numeric(ledger$start_sample[[1]])==0&&tail(as.numeric(ledger$end_sample_exclusive),1)==144000&&all(head(ledger$end_sample_exclusive,-1)==tail(ledger$start_sample,-1)))
  for(field in c("channel_mixing","resampling","gap_filling")){bad<-native;bad$recording[[field]]<-"changed";check(paste("Returned",field,"change fails validation"),rejects(brohn_validate_audio_extraction(bad,actual)))}
  bad<-native;bad$recording$samples_per_channel<-10;check("Invented sample duration/count fails validation",rejects(brohn_validate_audio_extraction(bad,actual)))
  objects<-lapply(native$artifacts,function(a)c(list(kind=a$kind),brohn_store_object(store,path=file.path(outdir,"artifacts",a$path),media_type=if(a$kind=="decoded-audio")"audio/wav"else"text/csv")))
  derived_id<-"dataset-audio-extraction-job-domain-derived";r<-save_result("audio-extraction-job-domain-derived",req,native,objects,derived_id)
  body<-list(schema_version="brohn-dataset/1.0.0",id=derived_id,title="Original derived domain contract",modality="audio",origin="sample",study_id=NULL,
    source=c(objects[[1]][c("hash","size","media_type")],list(filename="decoded-audio.wav",format="wav")),columns=list(),preview=list(),metadata=list(unit="FS"),status="needs_mapping",data_revision=1L,notes="",
    source_provenance=list(imported_at=brohn_now(),source_hash=objects[[1]]$hash,acquisition="video_audio_extraction",extraction=.brohn_ax_ref(r),parent_dataset=req$dataset,
      parent_source_hash=req$source_hash,camera=NULL,recording=native$recording,artifacts=objects,timing_alignment="not_established",physically_qualified=FALSE))
  derived<-brohn_put_entity(store,"dataset",derived_id,body,project_id=d$project_id);lineage<-brohn_audio_extraction_lineage(store,derived,TRUE)
  check("Derived audio exposes immutable JSON lineage and complete source refs",.brohn_sv_same(lineage$binding$parent_dataset,req$dataset)&&length(lineage$source_refs)==5L)
  bad<-derived;bad$body$source_provenance$acquisition<-NULL;check("Derived audio cannot strip its acquisition marker",rejects(brohn_audio_extraction_lineage(store,bad)))
  bad<-derived;bad$body$source_provenance<-list(source_hash=body$source$hash);check("Derived audio cannot erase all parent lineage",rejects(brohn_audio_extraction_lineage(store,bad)))
  bad<-derived;bad$body$study_id<-"invented-study";check("Derived audio cannot substitute a study association",rejects(brohn_audio_extraction_lineage(store,bad)))
  bad<-derived;bad$body$source_provenance$extraction$id<-catalog$id;check("A mapping cannot inject another parent publication",rejects(brohn_audio_extraction_lineage(store,bad)))
  ordinary<-brohn_ingest_dataset(store,file.path(media,"original.wav"),"Ordinary original WAV","audio",origin="sample")
  check("Ordinary WAV retains its existing behavior",is.null(brohn_audio_extraction_lineage(store,ordinary)))
  mapping<-list(unit="FS",channel_index=1L,origin_statement="Original synthetic video audio for domain acceptance, with full extraction ledger.")
  study<-brohn_create_study(store,"Another sample study")
  before<-brohn_get_entity(store,"dataset",derived$id)
  denied<-rejects(brohn_curate_dataset(store,derived$id,mapping,derived$revision,study_id=study$id))
  after<-brohn_get_entity(store,"dataset",derived$id)
  check("Invalid derived-study relinking fails before saving any mapping or revision",denied&&identical(before,after))
  mapped<-brohn_curate_dataset(store,derived$id,mapping,derived$revision)
  check("Legitimate metadata and channel mapping preserve the exact parent study",mapped$revision==derived$revision+1L&&is.null(mapped$body$study_id)&&identical(mapped$body$metadata$channel_index,1L))
  queued<-brohn_queue_dataset(store,mapped$id);generic<-brohn_job_input(store,queued)
  check("Normal acoustic queue/input retain exact derivation binding after mapping",.brohn_sv_same(generic$derived_audio_lineage,lineage)&&.brohn_sv_same(queued$request$derived_audio_lineage,lineage))
  substitute<-queued;substitute$request$derived_audio_lineage$binding$parent_source_hash<-paste(rep("0",64),collapse="")
  check("Generic acoustic input refuses substituted parent lineage",rejects(brohn_job_input(store,substitute)))
  DBI::dbExecute(store$con,"UPDATE entities SET project_id='foreign' WHERE kind='dataset' AND id=?",params=list(d$id))
  moved<-rejects(brohn_audio_extraction_lineage(store,derived));queued_moved<-rejects(brohn_job_input(store,queued));DBI::dbExecute(store$con,"UPDATE entities SET project_id=? WHERE kind='dataset' AND id=?",params=list(d$project_id,d$id))
  check("Warm derived lineage refuses a moved original source",moved)
  check("Already queued acoustic work refuses subsequently moved source authority",queued_moved)
  DBI::dbExecute(store$con,"UPDATE entities SET project_id='foreign' WHERE kind='dataset' AND id=?",params=list(d$id))
  before<-brohn_get_entity(store,"dataset",mapped$id)
  denied<-rejects(brohn_curate_dataset(store,mapped$id,mapping,mapped$revision))
  after<-brohn_get_entity(store,"dataset",mapped$id)
  DBI::dbExecute(store$con,"UPDATE entities SET project_id=? WHERE kind='dataset' AND id=?",params=list(d$project_id,d$id))
  check("Revoked parent authority refuses remapping before any saved mutation",denied&&identical(before,after))
  updated<-d$body;updated$notes<-"A current source revision was saved.";brohn_put_entity(store,"dataset",d$id,updated,d$revision,d$project_id)
  check("Queued stale selection fails while historical same-byte lineage remains inspectable",rejects(brohn_audio_extraction_input(store,job))&&!is.null(brohn_audio_extraction_lineage(store,derived)))
  fake<-brohn_ingest_dataset(store,file.path(media,"lossless.mkv"),"Invalid camera lineage","video",origin="sample")
  fake$body$source_provenance$acquisition<-"browser_camera";fake$body$source_provenance$capture_id<-"camera-unavailable"
  fake<-brohn_put_entity(store,"dataset",fake$id,fake$body,fake$revision,fake$project_id)
  check("Unbacked camera claims cannot substitute real consent and assembled audio",rejects(brohn_audio_extraction_source(store,fake$id,fake$revision,.brohn_sv_hash(fake$body),fake$project_id)))
  check("Original external media remain byte-identical",all(vapply(names(originals),function(name)identical(digest::digest(file=file.path(media,name),algo="sha256"),originals[[name]]),logical(1))))
  brohn_write_json_file(list(passed=TRUE,checks=as.list(checks),code_hashes=.brohn_audio_extraction_loaded,scope="Direct native outputs and explicit domain fixture publications, not an actual saved-job/browser claim."),file.path(folder,"results.json"));cat(length(checks),"audio extraction domain checks passed\n")
})
