# Original, isolated lifecycle fixtures. Real start/finish receipts; no claim of
# observed people or scientific accuracy. Browser coverage runs real analysis.
source("R/platform-load.R",encoding="UTF-8");brohn_load(ui=FALSE)
source("R/platform-collection-history.R")
local({
  checks<-character();check<-function(label,x){stopifnot(isTRUE(x));checks<<-c(checks,label);cat("PASS",label,"\n")}
  rejects<-function(x)inherits(try(force(x),silent=TRUE),"try-error")
  folder<-Sys.getenv("BROHN_COLLECTION_TEST_ROOT",tempfile("brohn-collection-domain-"));dir.create(folder,recursive=TRUE,showWarnings=FALSE)
  stopifnot(startsWith(basename(folder),"brohn-collection-"),!file.exists(file.path(folder,"workspace","catalog.sqlite")))
  store<-brohn_open_store(file.path(folder,"workspace"));on.exit(brohn_close_store(store),add=TRUE);brohn_initialise_library(store)
  study<-brohn_create_study(store,"Original closure example","survey");d<-study$body;d$questions<-list(brohn_question("Original response","text","end","closure-question"));study<-brohn_save_study(store,d,study$revision)
  check("Empty new study has no closed collection history",brohn_collection_page(store,study$id,"default")$total==0)
  release<-brohn_publish(store,study$id,"sample")
  check("Open release cannot be finalized",rejects(brohn_collection_review(store,release$id,study$id,"default")))
  check("Foreign study cannot inspect release",rejects(brohn_collection_review(store,release$id,"another-study","default")))
  start<-.brohn_delivery_start(store,release$token,list(consented=TRUE,client_id="original-client",participant_alias="PRIVATE_ALIAS",operation_id="original-start"))
  brohn_deployment_state(store,release$id,"closed");review<-brohn_collection_review(store,release$id,study$id,"default")
  check("Closing recruitment preserves in-flight session and blocks finalization",!review$ready&&length(review$blockers)==1L&&brohn_run(store,start$run_id)$completion_status=="in_progress")
  check("Unresolved session cannot be frozen",rejects(brohn_finalize_collection(store,release$id,study$id,"default",review$hash)))
  check("Closed release refuses new starts",rejects(.brohn_delivery_start(store,release$token,list(consented=TRUE,client_id="second-client",operation_id="second-start"))))
  .brohn_delivery_finish(store,start$run_id,start$access_token,list(outcome="withdrawn",final_sequence=0,operation_id="original-withdraw"))
  ready<-brohn_collection_review(store,release$id,study$id,"default")
  check("Saved withdrawal is distinct and does not invent a response report",ready$ready&&ready$counts$withdrawn==1&&ready$counts$completed==0&&length(ready$inventory$reports)==0)
  check("Changed terminal state refuses stale review",rejects(brohn_finalize_collection(store,release$id,study$id,"default",review$hash)))
  job<-brohn_enqueue_job(store,"analyse_run",list(run_id=start$run_id),"original-blocker")
  pending<-brohn_collection_review(store,release$id,study$id,"default")
  check("Queued linked processing blocks finalization",!pending$ready&&any(vapply(pending$blockers,function(x)x$kind=="job",logical(1))))
  brohn_cancel_job(store,job$id)
  cancelled<-brohn_collection_review(store,release$id,study$id,"default")
  check("Cancellation is unresolved, not silently discarded",!cancelled$ready&&any(grepl("successful retry",vapply(cancelled$blockers,`[[`,character(1),"text"))))
  # A second release avoids weakening the failed-job policy for the first one.
  next_release<-brohn_publish(store,study$id,"sample");brohn_deployment_state(store,next_release$id,"closed")
  empty<-brohn_collection_review(store,next_release$id,study$id,"default")
  record<-brohn_finalize_collection(store,next_release$id,study$id,"default",empty$hash);hash<-brohn_hash(record$body)
  check("Zero-start closed release freezes an explicit empty inventory",record$revision==1&&record$body$counts$started==0)
  check("Repeat finalization is idempotent",identical(hash,brohn_hash(brohn_finalize_collection(store,next_release$id,study$id,"default",empty$hash)$body)))
  check("Collection contains no participant or release credentials",!any(vapply(c(start$access_token,release$token,next_release$token,"PRIVATE_ALIAS"),grepl,logical(1),x=brohn_json(record$body),fixed=TRUE)))
  check("Unknown report cannot be navigated from a collection",rejects(brohn_collection_report(store,record,"unrelated-report")))
  d<-study$body;d$questions[[1L]]$prompt<-"Changed current draft";study<-brohn_save_study(store,d,study$revision)
  copy<-brohn_clone_study(store,study$id,"Clone pinned collection",revision=record$body$release$design_revision)
  check("Clone uses released revision and no sessions",copy$body$questions[[1L]]$prompt=="Original response"&&length(brohn_runs(store,copy$id))==0)
  later<-brohn_publish(store,study$id,"sample")
  check("New release preserves old closure and snapshot",later$status=="open"&&brohn_deployment(store,next_release$id)$status=="closed"&&identical(hash,brohn_hash(brohn_collection_record(store,next_release$id,study$id,"default")$body)))
  check("History is release-scoped and paginated",brohn_collection_page(store,study$id,"default",0,1)$total==2&&length(brohn_collection_page(store,study$id,"default",1,1)$records)==1)
  backup<-brohn_backup_workspace(store,file.path(folder,"backup"));restored<-brohn_restore_workspace(backup$path,file.path(folder,"restored"))
  restored_store<-brohn_open_store(file.path(folder,"restored"));on.exit(brohn_close_store(restored_store),add=TRUE)
  check("Backup restore preserves finalized manifest and closes new recruitment",identical(hash,brohn_hash(brohn_collection_record(restored_store,next_release$id,study$id,"default")$body))&&brohn_deployment(restored_store,later$id)$status=="closed")
  check("Restored workspace remains paused",brohn_workspace_execution_status(restored_store)$paused)
  brohn_write_json_file(list(passed=TRUE,checks=as.list(checks),collection_hash=hash,scope="Original synthetic starts and withdrawal; zero-start final manifest; no model or participant claims."),file.path(folder,"results.json"))
  cat(length(checks),"collection lifecycle checks passed;",folder,"\n")
})
