for (module in c("study", "comparison", "presentation", "records", "json", "storage", "assets", "aois", "drafts", "protocol", "protocol-storage"))
  source(paste0("R/", module, ".R"))
local({
  directory <- tempfile("protocol-storage-")
  dir.create(directory)
  on.exit(unlink(directory, recursive = TRUE), add = TRUE)
  rejected <- function(expr) inherits(try(expr, silent = TRUE), "try-error")
  bytes <- function(path) readBin(path, "raw", n = draft_size_limit + 1)
  bundle <- create_draft("sample")
  protocol <- create_protocol(bundle)
  path <- file.path(directory, "snapshot.json")
  save_protocol(protocol, path)
  original <- bytes(path)
  stopifnot(identical(protocol_to_json(read_protocol(path)), protocol_to_json(protocol)))
  Sys.setFileTime(path, as.POSIXct("2020-01-01", tz = "UTC"))
  modified <- file.info(path)$mtime
  save_protocol(protocol, path)
  stopifnot(identical(bytes(path), original), identical(file.info(path)$mtime, modified))
  revised <- revise_draft(bundle, "Later draft", TRUE)
  stopifnot(rejected(save_protocol(create_protocol(revised), path)), identical(bytes(path), original))
  dir.create(paste0(path, ".lock"))
  stopifnot(rejected(save_protocol(protocol, path)), identical(bytes(path), original))
  unlink(paste0(path, ".lock"), recursive = TRUE)
  stopifnot(rejected(read_protocol(path, max_bytes = length(original) - 1)))
  broken <- file.path(directory, "broken.json")
  for (raw in list(raw(), as.raw(c(123, 0, 125)), as.raw(c(0xff, 0xfe)), charToRaw("not JSON"))) {
    writeBin(raw, broken)
    stopifnot(rejected(read_protocol(broken)), rejected(save_protocol(protocol, broken)), identical(bytes(broken), raw))
  }
  draft_path <- file.path(directory, "draft.json")
  save_bundle(bundle, draft_path)
  stopifnot(is.null(open_draft_protocol(bundle, draft_path)))
  first <- save_draft_protocol(bundle, draft_path)
  snapshot_path <- file.path(paste0(draft_path, ".protocols"), paste0(first$content_sha256, ".json"))
  first_bytes <- bytes(snapshot_path)
  stopifnot(identical(open_draft_protocol(bundle, draft_path)$content_sha256, first$content_sha256),
    is.null(open_draft_protocol(revised, draft_path)))
  second <- save_draft_protocol(revised, draft_path)
  stopifnot(first$content_sha256 != second$content_sha256,
    length(list.files(paste0(draft_path, ".protocols"), pattern = "\\.json$")) == 2,
    identical(bytes(snapshot_path), first_bytes))
  corrupt <- read_protocol(snapshot_path)
  corrupt$content_sha256 <- strrep("0", 64)
  .write_draft_bytes(.protocol_encode(corrupt), snapshot_path)
  stopifnot(rejected(open_draft_protocol(bundle, draft_path)))
})
cat("PASS: protocol persistence, idempotence, corruption, bounds and retained revisions\n")
