// Actual researcher UI -> Chrome MediaRecorder -> authenticated R -> decoder/model.
// Original generated imagery, real service transport; deliberately interrupted ACK/offline cases.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const output=path.resolve('../../work/test-runs/brohn-camera-ui-evidence');await fs.mkdir(output,{recursive:true});
const workspace=path.resolve('../../work/test-runs/brohn-connected-02'),configFile=path.join(output,'records.json');
const movie=path.join(output,'original-colour-pattern-320x240.y4m'),width=320,height=240,frames=[Buffer.from(`YUV4MPEG2 W${width} H${height} F15:1 Ip A1:1 C420jpeg\n`)];
for(let f=0;f<150;f++){const y=Buffer.alloc(width*height),u=Buffer.alloc(width*height/4,96+f%40),v=Buffer.alloc(width*height/4,160-f%40);for(let i=0;i<y.length;i++)y[i]=32+((i+f*7)%190);frames.push(Buffer.from('FRAME\n'),y,u,v);}await fs.writeFile(movie,Buffer.concat(frames));
const browser=await chromium.launch({channel:'chrome',headless:true,args:['--use-fake-device-for-media-stream',`--use-file-for-fake-video-capture=${movie}`]});
const context=await browser.newContext({viewport:{width:1440,height:1080}}),page=await context.newPage(),checks=[],errors=[],violations=[],visits=[];
page.on('pageerror',e=>errors.push(e.message));let activePage=page,config={origin:'original_generated_y4m'};
const sha=bytes=>createHash('sha256').update(bytes).digest('hex');
const check=(ok,label)=>{assert.ok(ok,label);checks.push(label);console.log(`PASS ${label}`);};
const stage=name=>page.getByRole('button',{name,exact:true}).click();
async function download(p,label,name){const link=p.getByRole('link',{name:label,exact:true});await expect(link).toHaveAttribute('href',/session\/.*download\//);const pending=p.waitForEvent('download');await link.click();const d=await pending;assert.equal(await d.failure(),null);const file=path.join(output,name);await d.saveAs(file);return file;}
function portable(file){const r=spawnSync(path.resolve('../../work/tooling/methods-venv/Scripts/python.exe'),['-c',"import sys,zipfile; print(zipfile.ZipFile(sys.argv[1]).read('design.json').decode('utf-8'))",file],{encoding:'utf8',windowsHide:true});assert.equal(r.status,0,r.stderr);return JSON.parse(r.stdout);}
async function inspect(){await fs.writeFile(configFile,JSON.stringify(config,null,2));const r=spawnSync(path.resolve('../../work/native-r/bin/Rscript.exe'),['--vanilla','tests/fixtures/researcher-camera-inspect.R',workspace,configFile],{encoding:'utf8',windowsHide:true,env:{...process.env,R_LIBS_USER:path.resolve('../../work/r-library-brohn'),R_USER:path.resolve('../../work'),LC_ALL:'C'}});assert.equal(r.status,0,r.stderr||r.stdout);config=JSON.parse(await fs.readFile(configFile,'utf8'));return config;}
async function select(p,id,label){const input=p.locator(`#${id}-selectized`);await input.click();await input.fill(label);await p.locator('.selectize-dropdown:visible .option').filter({hasText:label}).click();}
async function axe(p,label,narrow=false){await p.setViewportSize(narrow?{width:390,height:844}:{width:1440,height:1080});await p.waitForFunction(()=>!document.documentElement.classList.contains('shiny-busy')&&![...document.querySelectorAll('.recalculating')].some(e=>e.getClientRects().length));await expect(p.locator('.shiny-output-error:visible')).toHaveCount(0);const a=(await new AxeBuilder({page:p}).analyze()).violations;await fs.writeFile(path.join(output,`${label}-axe.json`),JSON.stringify(a,null,2));await p.screenshot({path:path.join(output,`${label}.png`),fullPage:true});await p.screenshot({path:path.join(output,`${label}-viewport.png`)});if(a.length)violations.push({label,rules:a.map(v=>v.id)});check(a.length===0,`${label}: no automated accessibility violations`);check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${label}: no page overflow`);await p.setViewportSize({width:1280,height:900});}
async function localCamera(p){return p.evaluate(async()=>{const db=await new Promise((resolve,reject)=>{const r=indexedDB.open('brohn-camera-journal');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise((resolve,reject)=>{const tx=db.transaction(['segments','chunks'],'readonly'),s=tx.objectStore('segments').getAll(),c=tx.objectStore('chunks').getAll();tx.oncomplete=()=>resolve({segments:s.result,chunks:c.result.map(x=>({sequence:x.sequence,size:x.size,capture_id:x.capture_id,sha256:x.sha256}))});tx.onerror=()=>reject(tx.error);});}finally{db.close();}});}
async function participant(url,alias,{denied=false,lostAck=false}={}){
 const pc=await browser.newContext({viewport:{width:1280,height:900}});if(!denied)await pc.grantPermissions(['camera'],{origin:'http://127.0.0.1:3852'});
 await pc.addInitScript(()=>{window.cameraPermissionCalls=0;window.observedCameraTracks=[];const original=navigator.mediaDevices?.getUserMedia.bind(navigator.mediaDevices);if(original)navigator.mediaDevices.getUserMedia=async(...args)=>{cameraPermissionCalls++;const stream=await original(...args);observedCameraTracks.push(...stream.getTracks());return stream;};});
 const p=await pc.newPage();activePage=p;p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());const calls={start:[],chunk:[],finish:[],lostAck:false};
 if(denied){const cdp=await pc.newCDPSession(p);const {targetInfo}=await cdp.send('Target.getTargetInfo');await cdp.send('Browser.setPermission',{permission:{name:'camera'},setting:'denied',origin:'http://127.0.0.1:3852',browserContextId:targetInfo.browserContextId});await cdp.detach();}
 p.on('request',r=>{if(r.method()!=='POST')return;for(const kind of ['start','chunk','finish'])if(r.url().includes(`/api/camera_${kind}/`))calls[kind].push(r.postDataJSON());});
 if(lostAck)await p.route('**/api/camera_chunk/**',async route=>{if(!calls.lostAck){const response=await route.fetch();assert.equal(response.status(),200);calls.lostAck=true;await route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:{message:'Original QA: accepted camera bytes but lost acknowledgement'}})});}else await route.continue();});
 await p.goto(url);check(await p.evaluate(()=>cameraPermissionCalls)===0,`${alias}: opening study requests no camera permission`);await p.getByLabel('Participant alias (required)',{exact:true}).fill(alias);await p.getByLabel('I have read the study information and agree to take part.',{exact:true}).check();const pending=p.waitForResponse(r=>r.url().includes('/api/start/')&&r.request().method()==='POST');await p.getByRole('button',{name:'Start study',exact:true}).click();const session=await(await pending).json();assert.ok(session.run_id);await p.getByRole('heading',{name:'Camera setup',exact:true}).waitFor();check(await p.evaluate(()=>cameraPermissionCalls)===0,`${alias}: general study consent does not invoke camera permission`);const visit={pc,p,calls,session,alias};visits.push(visit);return visit;
}
async function enable(visit){const {p}=visit;await p.getByLabel('I agree to the camera recording described above.',{exact:true}).check();await p.getByRole('button',{name:'Enable camera',exact:true}).click();await p.getByRole('button',{name:'Begin study',exact:true}).waitFor();check(await p.evaluate(()=>cameraPermissionCalls===1&&observedCameraTracks.length===1&&observedCameraTracks[0].kind==='video'),'Camera positioning uses one real browser video track and no microphone');await axe(p,`${visit.alias}-camera-positioning-narrow`,true);await p.getByRole('button',{name:'Begin study',exact:true}).click();await p.getByRole('button',{name:'Begin',exact:true}).click();}
async function questions(visit,{offline=false,reload=false}={}){
 const {p,pc,session,calls}=visit;for(const [i,step]of session.protocol.timeline.filter(s=>s.type==='question').entries()){
  await p.getByRole('heading',{name:step.question.prompt,exact:true}).waitFor();
  if(i===0&&(offline||reload)){
   await expect.poll(()=>calls.chunk.length,{timeout:15000}).toBeGreaterThanOrEqual(2);
   if(reload){const before=await localCamera(p);visit.beforeReload=before;await p.reload();await p.getByRole('heading',{name:'The study was interrupted.',exact:true}).waitFor({timeout:45000});return;}
   await pc.setOffline(true);await p.waitForTimeout(1800);const pending=await localCamera(p);check(pending.chunks.length>0&&pending.segments[0].total_bytes>pending.segments[0].acked_bytes,'Offline recording retains pending camera bytes in its separate local journal');await pc.setOffline(false);
  }
  const option=step.question.options.find(o=>o.value===4);assert.ok(option);await p.getByRole('radio',{name:option.label,exact:true}).check();await p.getByRole('button',{name:'Continue',exact:true}).click();
 }
 await p.getByRole('heading',{name:'Thank you. Your responses are saved.',exact:true}).waitFor({timeout:45000});
}
async function settled(runId,{geometry=false}={}){let result;await expect.poll(async()=>{await inspect();result=config.runs.find(x=>x.run.id===runId);const needed=result?.jobs.filter(j=>['assemble_capture','analyse_dataset'].includes(j.operation))||[];return !!result?.publication&&needed.every(j=>!['queued','running'].includes(j.status))&&(!geometry||needed.some(j=>j.operation==='analyse_dataset'));},{timeout:180000,intervals:[1000,2000,4000]}).toBe(true);return result;}
try{
 await page.goto('http://127.0.0.1:3851/');await stage('Explore a practice design');const title=`Original camera UI ${Date.now()}`;await page.getByLabel('Study name',{exact:true}).fill(title);for(const id of ['stimulus_duration_1','stimulus_duration_2','baseline_ms','fixation_ms'])await page.locator(`#${id}`).fill('100');await stage('Set up camera recording');await page.getByLabel('Request camera recording in this study',{exact:true}).check();await stage('Save recording settings');await expect(page.locator('#platform_error')).toContainText(/retention|storage/i);check(true,'Camera authoring requires explicit storage/access/retention text');
 const consent='Original generated camera QA: record the synthetic camera stream during this controlled packaging study.';const retention='Original synthetic QA only. Stored in this local Brohn workspace, accessible to the developer researcher, retained with these test records. No person is recorded.';
 await page.getByLabel('Explain the recording to participants',{exact:true}).fill(consent);await page.getByLabel('Explain storage, access and retention to participants',{exact:true}).fill(retention);await page.getByText('Recording limits',{exact:true}).click();for(const[id,value]of [['camera_policy_width','320'],['camera_policy_height','240'],['camera_policy_rate','15'],['camera_policy_duration','60'],['camera_policy_size','16']])await page.locator(`#${id}`).fill(value);await select(page,'camera_policy_analysis','Keep the recording for review');await axe(page,'camera-policy-editor');await axe(page,'camera-policy-editor-narrow',true);await stage('Save recording settings');await expect(page.getByRole('dialog')).toHaveCount(0);
 const optional=portable(await download(page,'Export design','optional-camera.brohn-study.zip'));config.study_id=optional.id;config.title=title;assert.equal(optional.camera.required,false);assert.equal(optional.camera.audio,false);assert.equal(optional.camera.consent_text,consent);assert.equal(optional.camera.retention_text,retention);check(optional.camera.width===320&&optional.camera.height===240&&optional.camera.frame_rate===15&&optional.camera.analysis_profile==='none','Actual design export preserves camera settings, separate consent and original retention statement');
 await stage('Collect');await page.getByLabel('Require a researcher-issued participant code to link repeat sessions',{exact:true}).check();await stage('Release participant study');await page.getByRole('link',{name:'Open participant study',exact:true}).first().waitFor();const optionalUrl=await page.getByRole('link',{name:'Open participant study',exact:true}).first().getAttribute('href');
 const declined=await participant(optionalUrl,'ORIGINAL-CAMERA-DECLINED');await axe(declined.p,'optional-camera-setup-narrow',true);await declined.p.getByRole('button',{name:'Continue without camera',exact:true}).click();await declined.p.getByRole('button',{name:'Begin',exact:true}).click();await questions(declined);check(await declined.p.evaluate(()=>cameraPermissionCalls)===0&&declined.calls.start.length===1&&declined.calls.start[0].consented===false&&declined.calls.chunk.length===0,'Explicit optional decline completes the study without camera permission, bytes or implicit consent');await declined.pc.close();
 activePage=page;await page.bringToFront();await stage('Plan');await stage('Set up camera recording');await page.getByLabel('Recording is required to complete this study',{exact:true}).check();await select(page,'camera_policy_analysis','Automatically process local face geometry');await stage('Save recording settings');await expect(page.getByRole('dialog')).toHaveCount(0);const required=portable(await download(page,'Export design','required-camera.brohn-study.zip'));assert.equal(required.camera.required,true);await stage('Collect');await page.getByLabel('Require a researcher-issued participant code to link repeat sessions',{exact:true}).check();await stage('Release participant study');await expect(page.getByRole('link',{name:'Open participant study',exact:true})).toHaveCount(2);const requiredUrl=(await page.getByRole('link',{name:'Open participant study',exact:true}).evaluateAll(xs=>xs.map(x=>x.href))).find(url=>url!==optionalUrl);assert.ok(requiredUrl);
 const complete=await participant(requiredUrl,'ORIGINAL-CAMERA-COMPLETE',{lostAck:true});assert.deepEqual(complete.session.protocol.design.camera,required.camera);await complete.p.getByRole('button',{name:'Enable camera',exact:true}).click();await expect(complete.p.locator('#error')).toContainText('Confirm your agreement');check(await complete.p.evaluate(()=>cameraPermissionCalls)===0,'Camera permission is refused until the separate recording agreement is affirmative');await enable(complete);await questions(complete,{offline:true});
 const firstChunk=complete.calls.chunk[0],duplicate=complete.calls.chunk.filter(c=>c.sequence===firstChunk.sequence);check(complete.calls.lostAck&&duplicate.length>=2&&duplicate.every(c=>JSON.stringify(c)===JSON.stringify(firstChunk)),'A real-R accepted chunk with a lost ACK retries identical bytes and observation content');check(complete.calls.finish.length>=1&&complete.calls.finish.every(f=>f.outcome==='completed'&&f.container_complete),'The recorder stops before an immutable completed camera ending is delivered');check(await complete.p.evaluate(()=>observedCameraTracks.every(t=>t.readyState==='ended')),'Completed study releases every observed camera track');const journal=await localCamera(complete.p);check(journal.chunks.length===0&&journal.segments.length===0,'Final study receipt clears acknowledged camera journals only after saving');await complete.pc.close();
 const decoded=await settled(complete.session.run_id,{geometry:true});check(decoded.run.completion_status==='completed'&&decoded.run.transfer_status==='saved'&&decoded.camera_completion.eligible,'Durable run completion requires the saved camera receipt and full browser-step coverage');check(decoded.capture.start.study_id===required.id&&decoded.capture.start.design_hash===complete.session.protocol.design_hash&&decoded.capture.start.protocol_hash===decoded.protocol_hash&&decoded.dataset.body.origin==='pilot'&&decoded.run.origin==='pilot','Camera publication pins the exact frozen study, protocol, run and explicitly selected pilot source origin');
 check(decoded.publication.body.assembly.decoder.decoded&&decoded.publication.body.assembly.decoder.supported&&decoded.publication.body.assembly.decoder.video_frames>0,'Actual supervised decoder reads the completed browser WebM and preserves decoded frame counts');check(decoded.dataset.body.source_provenance.timing_alignment==='not_established'&&decoded.dataset.body.source_provenance.physically_qualified===false,'A decoded browser recording does not claim encoded-frame alignment or physical camera qualification');
 const uniqueChunks=[...new Map(complete.calls.chunk.map(c=>[c.sequence,c])).values()].sort((a,b)=>a.sequence-b.sequence),bytes=Buffer.concat(uniqueChunks.map(c=>Buffer.from(c.data_base64,'base64')));check(sha(bytes)===decoded.dataset.body.source.hash&&bytes.length===decoded.capture.total_bytes&&decoded.chunks.length===uniqueChunks.length,'Published source hash and byte count exactly match original received recorder chunks without duplicate ACK bytes');
 check(decoded.observations.flatMap(o=>o.frames).some(f=>f.phase==='active_response')&&decoded.observations.every(o=>o.clock_instance_id===decoded.capture.start.request.clock.instance_id),'Full callback observations retain the original browser instance and explicit active-response context');
 const geometryJob=decoded.jobs.find(j=>j.operation==='analyse_dataset');check(geometryJob?.status==='succeeded'&&decoded.reports.length===1,'Completed camera policy queues and completes the actual registered local geometry model once');check(decoded.reports[0].body.analysis.status==='insufficient_support'&&decoded.reports[0].body.analysis.quality.channels.face.valid_frames===0&&decoded.reports[0].body.analysis.observations.every(o=>o.face.state==='absent'&&o.face.geometry===null&&o.face.blendshapes===null),'Original non-face imagery yields explicit absent-face support without invented geometry or emotion scores');config.completed_run_id=complete.session.run_id;config.completed_dataset_id=decoded.dataset.id;
 const denied=await participant(requiredUrl,'ORIGINAL-CAMERA-DENIED',{denied:true});check(await denied.p.getByRole('button',{name:'Continue without camera',exact:true}).count()===0,'Required-camera setup has no unsupported continue-without-recording path');await denied.p.getByLabel('I agree to the camera recording described above.',{exact:true}).check();await denied.p.getByRole('button',{name:'Enable camera',exact:true}).click();await expect(denied.p.locator('#error')).toContainText(/denied|permission|not allowed/i);check(await denied.p.getByRole('button',{name:'Begin study',exact:true}).count()===0&&await denied.p.evaluate(()=>cameraPermissionCalls)===1,'Browser permission denial cannot begin a required recording study');await axe(denied.p,'required-camera-denied-narrow',true);await denied.p.getByRole('button',{name:'Stop study',exact:true}).click();await denied.p.getByRole('heading',{name:'You have stopped the study.',exact:true}).waitFor();await denied.pc.close();
 const resumed=await participant(requiredUrl,'ORIGINAL-CAMERA-RELOAD');await enable(resumed);await questions(resumed,{reload:true});check(await resumed.p.evaluate(()=>cameraPermissionCalls)===0,'Reload recovery does not request a new camera or splice a replacement recorder');await resumed.pc.close();const partial=await settled(resumed.session.run_id);check(partial.run.completion_status==='interrupted'&&partial.capture.status==='interrupted'&&!partial.capture.final.container_complete&&!partial.camera_completion.eligible,'Reload preserves partial recording and run as interrupted rather than completed coverage');assert.deepEqual(partial.capture.final.clock,partial.capture.start.request.clock);check(partial.capture.final.reason==='page_reload_recording_end_unobserved'&&!partial.publication.body.assembly.recording_end_observed,'Reload retains the original start-clock sentinel without inventing an observed ending');check(partial.capture.total_bytes>0&&partial.jobs.filter(j=>j.operation==='analyse_dataset').length===0,'Partial camera bytes remain a source without automatic geometry scoring');
 await inspect();const declineRecord=config.runs.find(r=>r.run.id===declined.session.run_id),denyRecord=config.runs.find(r=>r.run.id===denied.session.run_id);check(declineRecord.capture.status==='declined'&&declineRecord.capture.total_bytes===0&&declineRecord.run.completion_status==='completed'&&declineRecord.run.protocol.design.camera.required===false,'Old optional release retains its exact declined policy after the draft becomes required');check(denyRecord.run.completion_status==='withdrawn'&&denyRecord.capture===null&&!denyRecord.camera_completion.eligible,'Denied required setup is retained as withdrawn with missing camera coverage');
 activePage=page;await page.bringToFront();await stage('Data library');await page.getByLabel('Search datasets',{exact:true}).fill(decoded.dataset.body.title);await page.locator(`[data-brohn-event="open_dataset"][data-brohn-value='"${decoded.dataset.id}"']`).click();await page.getByRole('heading',{name:'Participant camera recording',exact:true}).waitFor();
 for(const artifact of decoded.publication.body.artifacts){const label={'camera-recording':'Original camera recording (WebM)','camera-observations':'Chunk clocks and frame callbacks (JSONL)','camera-decoded-frames':'Decoded frames and native timestamps (JSON)','camera-manifest':'Capture and transfer manifest (JSON)'}[artifact.kind];await select(page,'camera_dataset_artifact',label);const file=await download(page,'Download recording artifact',`${artifact.kind}.${artifact.kind==='camera-recording'?'webm':artifact.kind==='camera-observations'?'jsonl':'json'}`);check(sha(await fs.readFile(file))===artifact.hash,`${artifact.kind}: actual researcher download matches the immutable complete artifact`);if(artifact.kind==='camera-manifest'){const manifest=JSON.parse(await fs.readFile(file,'utf8'));assert.deepEqual(manifest.policy,required.camera);check(true,'Standalone manifest preserves the exact frozen consent, retention, requirements and processing policy');assert.deepEqual(manifest.study,Object.fromEntries(['study_id','study_revision','deployment_id','design_hash','protocol_hash'].map(k=>[k,decoded.capture.start[k]])));assert.deepEqual(manifest.participant,Object.fromEntries(['participant_id','participant_alias_supplied'].map(k=>[k,decoded.capture.start[k]])));check(true,'Standalone manifest retains exact study/revision/protocol and declared participant references');}}
 await axe(page,'camera-dataset');await axe(page,'camera-dataset-narrow',true);await page.locator(`[data-brohn-event="open_report"][data-brohn-value='"${decoded.reports[0].id}"']`).click();const geometryReport=JSON.parse(await fs.readFile(await download(page,'JSON + provenance','camera-geometry-report.json'),'utf8'));assert.deepEqual(geometryReport,decoded.reports[0].body);const geometryArtifact=geometryReport.analysis.artifacts.find(a=>a.kind==='vision-observations');assert.ok(geometryArtifact);const geometryFile=await download(page,'Download complete artifact','camera-complete-face-observations.jsonl');const geometryBytes=await fs.readFile(geometryFile);check(sha(geometryBytes)===geometryArtifact.hash,'Actual geometry report downloads the complete immutable per-frame model artifact');const geometryRows=geometryBytes.toString('utf8').trim().split(/\r?\n/).map(line=>JSON.parse(line));check(geometryRows.length===geometryReport.analysis.quality.analysed_frames&&geometryRows.every(r=>r.face.state==='absent'&&r.face.landmarks===null&&r.face.blendshapes===null),'Full model artifact retains every analysed absent-face frame with null landmarks and blendshapes');await axe(page,'camera-geometry-report-narrow',true);check(errors.length===0,`No browser exceptions: ${errors.join(';')}`);check(violations.length===0,'All camera consent/source accessibility scans are clear');await fs.writeFile(path.join(output,'results.json'),JSON.stringify({origin:'original_generated_y4m',checks,study_id:config.study_id,run_ids:visits.map(v=>v.session.run_id),dataset_id:decoded.dataset.id,geometry_report_id:decoded.reports[0].id},null,2));console.log(JSON.stringify({checks:checks.length,output}));
}catch(error){await activePage.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});await fs.writeFile(path.join(output,'failure.json'),JSON.stringify({error:error.stack,checks,errors,violations,study_id:config.study_id,visits:visits.map(v=>({alias:v.alias,run_id:v.session.run_id,camera_starts:v.calls.start,camera_finishes:v.calls.finish,chunk_sequences:v.calls.chunk.map(c=>c.sequence)})),text:await activePage.locator('body').innerText().catch(()=>'(closed)')},null,2));if(config.study_id)await inspect().catch(()=>{});throw error;}finally{await browser.close();}
