// Actual saved fNIRS software-phantom outputs -> plot, exact rows and complete CSV.
// No scientific analysis rerun or device/brain-response qualification.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {spawn,spawnSync} from 'node:child_process';
import {chromium,expect as baseExpect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';
const expect=baseExpect.configure({timeout:30000});
const folder=path.resolve(process.argv[2]),reference=path.resolve(process.argv[3]);
assert.ok(path.basename(folder).startsWith('brohn-fnirs-browser-'));
await fs.mkdir(folder,{recursive:true});const output=path.join(folder,`browser-${Date.now()}`);await fs.mkdir(output);
const r=path.resolve('../../work/native-r/bin/Rscript.exe'),helper='tests/fixtures/researcher-fnirs.R';
const env={...process.env,R_LIBS_USER:path.resolve('../../work/r-library-brohn-restore'),LC_ALL:'C',BROHN_PUBLICATION_PYTHON:path.resolve('../../work/tooling/methods-venv/Scripts/python.exe')};
function runR(mode){const p=spawnSync(r,['--vanilla',helper,mode,folder,reference],{env,windowsHide:true,encoding:'utf8',timeout:300000});assert.equal(p.status,0,p.stderr||p.stdout);}
if(!process.argv.includes('--reuse-fixture'))runR('setup');
await fs.rm(path.join(folder,'stop.request'),{force:true});const config=JSON.parse(await fs.readFile(path.join(folder,'fixture.json'),'utf8'));
const sourceFiles=['R/platform-signal-values.R','R/platform-signal-value-views.R','R/platform-signal-views.R','R/platform-jobs.R','scripts/analysis-worker.R','scripts/workers/signal_values.py','scripts/workers/signal_preview.py','scripts/workers/physiology_artifacts.py'];
const hashFiles=async()=>Object.fromEntries(await Promise.all(sourceFiles.map(async file=>[file,createHash('sha256').update(await fs.readFile(file)).digest('hex')])));
const sourceHashes=await hashFiles(),oracles={};
for(const [name,report] of Object.entries(config.reports)){
  const bytes=await fs.readFile(report.artifact_path);assert.equal(createHash('sha256').update(bytes).digest('hex'),report.artifact.hash);
  const tables={};for(const line of bytes.toString('utf8').trim().split(/\r?\n/)){const item=JSON.parse(line);if(item.type==='table')tables[item.table_id]={declaration:item,rows:[]};else if(item.type==='rows'){assert.equal(tables[item.table_id].rows.length,item.offset);tables[item.table_id].rows.push(...item.rows);}}
  for(const table of Object.values(tables))assert.equal(table.rows.length,table.declaration.expected_rows);
  oracles[name]=tables;
}
const checks=[],scans=[],children=[],errors=[],selections=[];let log='';
const check=(value,label)=>{assert.ok(value,label);checks.push(label);console.log('PASS',label);};
const browser=await chromium.launch({channel:'chrome',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1080},acceptDownloads:true}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));
async function idle(){await page.waitForFunction(()=>!document.documentElement.classList.contains('shiny-busy')&&![...document.querySelectorAll('.recalculating')].some(e=>e.getClientRects().length),null,{timeout:120000});await expect(page.locator('.shiny-output-error:visible')).toHaveCount(0);}
async function open(name){const report=config.reports[name];await page.getByRole('button',{name:'Data library',exact:true}).click();await page.getByLabel('Search datasets',{exact:true}).fill(report.title);await page.locator(`[data-brohn-event="open_dataset"][data-brohn-value='"${report.dataset_id}"']`).click();await page.locator(`[data-brohn-event="open_report"][data-brohn-value='"${report.report_id}"']`).click();await idle();await page.getByRole('button',{name:'Explore signal traces and spectra',exact:true}).click();await page.getByRole('button',{name:'Show exact values',exact:true}).waitFor({timeout:180000});await expect(page.locator('#signal_form_identity')).toHaveValue(new RegExp('^'+report.report_id+':'),{timeout:180000});await idle();}
async function select(id,value){if(await page.locator('#'+id).inputValue()===value)return;const control=page.getByRole('button',{name:'Show exact values',exact:true}),before=id==='signal_table'?await control.getAttribute('data-signal-values-payload'):null;const field=page.locator(`#${id}-selectized`);await field.click();await field.fill(id==='signal_measure'?value.replaceAll('_',' '):value);await page.locator(`.selectize-dropdown:visible .option[data-value="${value}"]`).click();await expect(page.locator('#'+id)).toHaveValue(value);if(id==='signal_table'){await expect(page.locator('#signal_measure_identity')).toHaveValue(new RegExp(':'+value+'$'));await expect.poll(()=>control.getAttribute('data-signal-values-payload')).not.toBe(before);}await idle();}
async function download(label,name){const pending=page.waitForEvent('download',{timeout:180000});await page.getByRole('link',{name:label,exact:true}).click();const d=await pending;assert.equal(await d.failure(),null);const file=path.join(output,name);await d.saveAs(file);return file;}
async function json(label,name){return JSON.parse(await fs.readFile(await download(label,name),'utf8'));}
function csvRows(file){const result=spawnSync(path.resolve('../../work/tooling/methods-venv/Scripts/python.exe'),['-c',"import csv,json,sys;f=open(sys.argv[1],encoding='utf-8',newline='');print(json.dumps(list(csv.DictReader(f)),ensure_ascii=True))",file],{windowsHide:true,encoding:'utf8',maxBuffer:32*1024*1024});assert.equal(result.status,0,result.stderr);return JSON.parse(result.stdout);}
async function scan(label,narrow,target){await page.setViewportSize(narrow?{width:390,height:844}:{width:1440,height:1080});await idle();await target.evaluate(e=>e.scrollIntoView({block:'start',behavior:'instant'}));await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
  const axe=(await new AxeBuilder({page}).analyze()).violations,layout=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,small:[...document.querySelectorAll('#signal_plot a,.brohn-exact-values button,.brohn-exact-values a,.brohn-exact-values select')].filter(e=>{const b=e.getBoundingClientRect();return b.width&&b.height&&(b.width<43||b.height<43);}).map(e=>e.textContent)}));
  await fs.writeFile(path.join(output,label+'-axe.json'),JSON.stringify(axe,null,2));await page.screenshot({path:path.join(output,label+'.png')});
  const chart=page.locator('#signal_plot svg:visible');if(await chart.count()){await chart.screenshot({path:path.join(output,label+'-chart.png')});const geometry=await chart.evaluate(svg=>{const r=svg.getBoundingClientRect();return [...svg.querySelectorAll('text')].map(t=>{const b=t.getBoundingClientRect();return {text:t.textContent,inside:b.left>=r.left-1&&b.right<=r.right+1&&b.top>=r.top-1&&b.bottom<=r.bottom+1};});});check(geometry.every(t=>t.inside),label+': every chart axis/tick label remains inside the figure');}
  scans.push({label,violations:axe.length,...layout});check(!axe.length&&!layout.overflow&&!layout.small.length,label+': accessibility, reflow and44px actions');
}
try{
  for(const mode of ['serve','worker']){const child=spawn(r,['--vanilla',helper,mode,folder],{env,windowsHide:true});children.push(child);child.stdout.on('data',x=>log+=`${mode}: ${x}`);child.stderr.on('data',x=>log+=`${mode}: ${x}`);}
  await expect.poll(async()=>{if(children.some(c=>c.exitCode!==null))throw Error(log);try{return(await fetch(`http://127.0.0.1:${config.port}/`)).status===200;}catch{return false;}},{timeout:60000}).toBe(true);await page.goto(`http://127.0.0.1:${config.port}/`);
  const plans=[];for(const name of ['unequal-pathlength','nonpositive-splits']){const tables=config.reports[name].tables;const hbo=tables.filter(t=>t.identity.channel.endsWith(' hbo')).at(-1),hbr=tables.filter(t=>t.identity.channel.endsWith(' hbr')).at(-1);plans.push({name,table:hbo,measure:'haemoglobin_um'},{name,table:hbr,measure:'haemoglobin_um'});if(name==='unequal-pathlength')plans.push({name,table:hbo,measure:'optical_density'},{name,table:hbr,measure:'optical_density'});}
  let current=null;
  for(const [i,plan] of plans.entries()){
    const {name,table,measure}=plan,stem=`${name}-${table.table_id}-${measure}`,native=oracles[name][table.table_id],columns=native.declaration.columns,names=columns.map(c=>c.name),xi=names.indexOf('time_s'),yi=names.indexOf(measure),unit=columns[yi].unit;
    if(current!==name){await open(name);current=name;}
    const close=page.getByRole('button',{name:'Close exact values',exact:true});if(await close.count()){await close.first().click();await expect(page.locator('#signal-exact-values')).toHaveCount(0);}
    await select('signal_table',table.table_id);await select('signal_measure',measure);await page.getByLabel('Show the complete recorded range',{exact:true}).check();
    await page.getByRole('button',{name:'Show signal',exact:true}).click();await expect(page.locator('#signal_plot')).toContainText(table.table_id,{timeout:180000});await expect(page.locator('#signal_plot').getByRole('heading',{name:measure.replaceAll('_',' '),exact:true})).toBeVisible({timeout:180000});
    const view=await json('Download view + provenance',stem+'-view.json');assert.equal(view.report_id,config.reports[name].report_id);assert.equal(view.artifact_hash,config.reports[name].artifact.hash);assert.equal(view.view.selection.table_ids[0],table.table_id);assert.equal(view.view.axis.value_column,measure);assert.equal(view.view.axis.value_unit,unit);assert.equal(view.view.axis.unit,'s');
    let points=0;for(const bin of view.view.envelopes)for(const p of bin.points){const row=native.rows[p.row_index];assert.ok(row);assert.equal(p.x,row[xi]);assert.equal(p.y,row[yi]);points++;}
    check(points>0&&view.view.full_range.rows===native.rows.length,stem+': every plotted saved point equals its original typed source row');
    const svg=await fs.readFile(await download('Download chart',stem+'.svg'),'utf8');check(svg.includes('role="img"')&&svg.includes('Time (s)')&&svg.includes(unit)&&svg.includes('without joining gaps'),stem+': standalone SVG preserves accessible units and gap policy');
    await page.getByLabel('Rows per value page',{exact:true}).selectOption('25');await page.getByRole('button',{name:'Show exact values',exact:true}).click();await expect(page.locator('#signal-exact-values')).toBeVisible({timeout:180000});await expect(page.locator('#signal-exact-values')).toContainText(native.rows.length+' selected source rows');
    await page.getByRole('button',{name:'Prepare complete selected CSV',exact:true}).click();await page.getByRole('link',{name:'Download complete selected CSV',exact:true}).waitFor({timeout:300000});const csv=await download('Download complete selected CSV',stem+'.csv'),manifest=await json('Download CSV source and schema',stem+'-source.json'),rows=csvRows(csv);
    assert.equal(rows.length,native.rows.length);for(const [n,row] of rows.entries()){assert.equal(row.table_row_index,String(n));assert.equal(Number(row.coordinate),native.rows[n][xi]);assert.equal(Number(row.value),native.rows[n][yi]);assert.deepEqual(JSON.parse(row.exact_record_json),Object.fromEntries(names.map((key,j)=>[key,native.rows[n][j]])));assert.equal(row.measure_unit,unit);}
    assert.equal(createHash('sha256').update(await fs.readFile(csv)).digest('hex'),manifest.result.csv.sha256);assert.deepEqual(manifest.result.table.identity,native.declaration.identity);assert.deepEqual(manifest.result.table.coordinates,native.declaration.coordinates);assert.deepEqual(manifest.result.table.columns,native.declaration.columns);assert.deepEqual(manifest.result.table.support.parameters.ppf,[6,5]);assert.deepEqual(manifest.result.table.support.parameters.wavelengths_nm,[760,850]);assert.equal(manifest.result.table.identity.optical_density_source_channel,table.identity.optical_density_source_channel);
    check(true,stem+': complete CSV and manifest preserve every value, both wavelength/PPF declarations, source segment and original row');
    if(i===0){await scan('fnirs-hbo-desktop',false,page.locator('#signal_plot'));await scan('fnirs-hbo-390',true,page.locator('#signal_plot'));await scan('fnirs-exact-390',true,page.locator('#signal-exact-values'));await page.locator('.brohn-exact-scroll').focus();await page.keyboard.press('ArrowRight');await expect.poll(()=>page.locator('.brohn-exact-scroll').evaluate(e=>e.scrollLeft)).toBeGreaterThan(0);await page.getByRole('button',{name:'Inspect row 0',exact:true}).focus();await page.keyboard.press('Enter');await expect(page.locator('#signal_values_detail')).toContainText('haemoglobin_um');check(true,'Keyboard scrolling and row inspection expose original fNIRS typed fields');}
    if(i===3)await scan('fnirs-optical-density-390',true,page.locator('#signal_plot'));
    if(name==='nonpositive-splits'){const support=native.declaration.support.source;check(support.source_row_start>0&&native.rows[0][names.indexOf('source_sample_index')]===support.source_row_start,stem+': post-gap segment keeps original source sample indexing and clock');if(i===4)await scan('fnirs-post-gap-390',true,page.locator('#signal_plot'));}
    await page.setViewportSize({width:1440,height:1080});selections.push({name,table:table.table_id,measure,unit,rows:rows.length,plotted_points:points,view_id:view.id,csv_sha256:manifest.result.csv.sha256});
  }
  await open('unequal-pathlength');await select('signal_measure','haemoglobin_um');await page.getByRole('button',{name:'Show signal',exact:true}).click();await expect(page.locator('#signal_plot')).toContainText(plans[0].table.table_id,{timeout:180000});const reopened=await json('Download view + provenance','reopened-view.json');check(reopened.report_id===config.reports['unequal-pathlength'].report_id&&reopened.view.axis.value_column==='haemoglobin_um','Report reopen retrieves the exact original haemoglobin selection');
  runR('inspect');const inspection=JSON.parse(await fs.readFile(path.join(folder,'inspection.json'),'utf8'));for(const [name,record] of Object.entries(config.reports))assert.equal(inspection.reports[name].hash,record.report_hash);
  assert.ok(inspection.jobs.every(j=>j.status==='succeeded'));assert.deepEqual(await hashFiles(),sourceHashes);check(!errors.length,'All jobs closed successfully, source reports unchanged and no browser exceptions or source drift');
  await fs.writeFile(path.join(output,'results.json'),JSON.stringify({checks,scans,selections,jobs:inspection.jobs,sourceHashes,scope:'Original independently solved software phantom; saved visualization/export workflow, no hardware or neural response qualification'},null,2));console.log(JSON.stringify({checks:checks.length,scans:scans.length,output}));
}catch(error){await fs.writeFile(path.join(output,'failure.json'),JSON.stringify({error:error.stack,checks,scans,selections,errors,log},null,2));await fs.writeFile(path.join(output,'failure.html'),await page.content());await page.screenshot({path:path.join(output,'failure.png')});throw error;}
finally{await fs.writeFile(path.join(folder,'stop.request'),'stop');await fs.writeFile(path.join(output,'services.log'),log);await browser.close();for(const child of children){if(child.exitCode===null)await Promise.race([new Promise(resolve=>child.once('exit',resolve)),new Promise(resolve=>setTimeout(resolve,10000))]);if(child.exitCode===null)child.kill();}}
