// Independent researcher authoring/reuse journey. Original synthetic materials;
// actual Shiny + separate participant receiver; no scientific worker is started.
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';
import {spawn,spawnSync} from 'node:child_process';
import {chromium,expect} from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

const r=path.resolve('../../work/native-r/bin/x64/Rscript.exe');
const python=path.resolve('../../work/tooling/methods-venv/Scripts/python.exe');
const env={...process.env,R_LIBS_USER:path.resolve('../../work/r-library-brohn'),LC_ALL:'C',R_USER:path.resolve('../../work')};
const folder=await fs.mkdtemp(path.resolve('../../work/test-runs/brohn-maxdiff-researcher-'));
const output=path.join(folder,'evidence');await fs.mkdir(output);
function helper(mode,id){const p=spawnSync(r,['--vanilla','tests/fixtures/researcher-maxdiff.R',mode,folder,...(id?[id]:[])],{env,encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);}
helper('create');
const fixture=JSON.parse(await fs.readFile(path.join(folder,'fixture.json'),'utf8'));
const children=[],logs={};
function service(name,args){const child=spawn(r,['--vanilla',...args],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});logs[name]='';for(const stream of [child.stdout,child.stderr])stream.on('data',b=>logs[name]+=b);children.push({name,child});return child;}
const app=service('researcher',['tests/fixtures/researcher-maxdiff.R','serve',folder]);
const receiver=service('participant',['scripts/run-participant.R','--root',fixture.workspace,'--port',String(fixture.participant_port)]);
const browser=await chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1080}}),page=await context.newPage();
const checks=[],errors=[],violations=[];let activePage=page,original;
page.on('pageerror',e=>errors.push(e.message));
const check=(ok,label)=>{assert.ok(ok,label);checks.push(label);console.log(`PASS ${label}`);};
const stage=name=>page.getByRole('button',{name,exact:true}).click();
const title=`Original packaging MaxDiff ${Date.now()}`;
const itemLabels=['Refillable packaging','One-handed opening','Clear ingredient list','Compact storage'];
const framing=[
 {title:'Original packaging importance',prompt:'Which packaging feature matters most and least when you choose a household product?',best:'Matters most',worst:'Matters least',required:true},
 {title:'Original packaging preference',prompt:'Which packaging feature do you personally like most and least?',best:'Like most',worst:'Like least',required:false}
];
async function idle(){await page.waitForFunction(()=>!document.documentElement.classList.contains('shiny-busy')&&![...document.querySelectorAll('.recalculating')].some(e=>e.getClientRects().length));await expect(page.locator('.shiny-output-error:visible')).toHaveCount(0);}
async function select(id,label){const input=page.locator(`#${id}-selectized`);await input.click();await input.fill(label);await page.locator('.selectize-dropdown:visible .option').filter({hasText:label}).click();}
async function snapshot(id){helper('inspect',id);return JSON.parse(await fs.readFile(path.join(folder,'snapshot.json'),'utf8'));}
async function download(label,name){const link=page.getByRole('link',{name:label,exact:true});await expect(link).toHaveAttribute('href',/session\/.*download\//);const pending=page.waitForEvent('download');await link.click();const d=await pending;assert.equal(await d.failure(),null);const file=path.join(output,name);await d.saveAs(file);return file;}
function portable(file){const p=spawnSync(python,['-c',"import sys,zipfile;print(zipfile.ZipFile(sys.argv[1]).read('design.json').decode('utf-8'))",file],{encoding:'utf8',windowsHide:true});assert.equal(p.status,0,p.stderr);return JSON.parse(p.stdout);}
async function axe(label,narrow=false,p=page){await p.setViewportSize(narrow?{width:390,height:844}:{width:1440,height:1080});if(p===page)await idle();const a=(await new AxeBuilder({page:p}).analyze()).violations;await fs.writeFile(path.join(output,`${label}-axe.json`),JSON.stringify(a,null,2));await p.screenshot({path:path.join(output,`${label}.png`),fullPage:true});if(a.length)violations.push({label,rules:a.map(v=>v.id)});check(!a.length,`${label}: no automated accessibility violations`);check(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),`${label}: no page overflow`);await p.setViewportSize({width:1440,height:1080});}
async function structure(label){const before=Number(await page.locator('#maxdiff_structure [data-maxdiff-version]').getAttribute('data-maxdiff-version'));await stage(label);await expect(page.locator('#maxdiff_structure [data-maxdiff-version]')).toHaveAttribute('data-maxdiff-version',String(before+1));const token=await page.locator('#maxdiff_form_identity').inputValue();await expect(page.locator('#maxdiff_structure_identity')).toHaveValue(`${token}:${before+1}`);await idle();}
async function author(index){
 const f=framing[index];await stage('Add best-worst exercise');await page.getByRole('dialog',{name:'Add best-worst exercise',exact:true}).waitFor();await expect(page.locator('#maxdiff_structure_identity')).toHaveValue(/:1$/);
 await page.locator('#maxdiff_title').fill(f.title);await page.locator('#maxdiff_prompt').fill(f.prompt);await page.locator('#maxdiff_best').fill(f.best);await page.locator('#maxdiff_worst').fill(f.worst);await page.locator('#maxdiff_required').setChecked(f.required);
 for(let i=0;i<itemLabels.length;i++)await page.getByLabel(`Item ${i+1} label`,{exact:true}).fill(itemLabels[i]);
 await page.getByText('Materials and ordering',{exact:true}).click();await expect(page.locator('#maxdiff_origin')).toHaveValue('synthetic');
 await page.locator('#maxdiff_rights').fill('Original synthetic consumer feature labels authored for Brohn automated QA. No licensed questionnaire text and no participant observations.');
 await page.locator('#maxdiff_rationale').fill('Original complete four-item design: each item appears in three triples and every pair appears together twice. Saved order is deliberately fixed to verify transport; this is not a claim of an optimal field design.');
 await select('maxdiff_set_order','Fixed saved order');await select('maxdiff_item_order','Fixed saved order');
 await structure('Apply selections and labels');
 if(index===0){
  await structure('Move position 2 up in set 1');await structure('Move set 4 up');
  const identity=await page.locator('#maxdiff_structure_identity').inputValue();await stage('Remove item 1');await expect(page.locator('#platform_error')).toContainText('Remove this item from every choice set first.');await expect(page.locator('#maxdiff_structure_identity')).toHaveValue(identity);
  check(true,'Deleting an item still used by sets is rejected without replacing the current draft');
  const token=await page.locator('#maxdiff_form_identity').inputValue();await page.evaluate(token=>Shiny.setInputValue('maxdiff_structure_command',{token,version:1,action:'add_set'},{priority:'event'}),token);await expect(page.locator('#platform_error')).toContainText('Wait for the current item/set controls');await expect(page.locator('#maxdiff_structure_identity')).toHaveValue(identity);
  check(true,'A stale structural command cannot append a set after newer label/order changes');
 }
 await stage('Check design coverage');await expect(page.locator('#maxdiff_review_output')).toContainText('All items are connected in this design.');await expect(page.locator('#maxdiff_review_output')).toContainText('4 items in 4 sets.');await expect(page.locator('#maxdiff_review_output')).toContainText('do not certify an optimal design');
 if(index===0){await axe('maxdiff-authoring');await axe('maxdiff-authoring-narrow',true);}
 await stage('Save exercise');await expect(page.getByRole('dialog')).toHaveCount(0);
}
async function openOriginal(){await stage('Studies');await page.getByLabel('Search studies',{exact:true}).fill(title);await page.locator(`[data-brohn-event="brohn_open_study"][data-brohn-value='"${original.id}"']`).click();await expect(page.getByLabel('Study name',{exact:true})).toHaveValue(title);}
function graph(design){return design.maxdiff.map(e=>({title:e.title,origin:e.origin,profile:e.profile,materials_rights:e.materials_rights,seed:e.seed,settings:e.settings,labels:e.items.map(i=>i.label),sets:e.sets.map(s=>s.item_ids.map(id=>e.items.findIndex(i=>i.id===id)))}));}
function fresh(copy,source,label){assert.notEqual(copy.id,source.id);assert.deepEqual(graph(copy),graph(source));for(const [i,e]of copy.maxdiff.entries()){assert.notEqual(e.id,source.maxdiff[i].id);assert.ok(e.items.every((item,j)=>item.id!==source.maxdiff[i].items[j].id));assert.ok(e.sets.every(s=>!source.maxdiff[i].sets.some(old=>old.id===s.id)));}assert.notEqual(copy.questions[0].id,source.questions[0].id);check(true,`${label}: fresh study/exercise/item/set/question identities preserve exact framing, origin and internal set graph`);}
try{
 for(const [child,url]of [[app,`http://127.0.0.1:${fixture.port}/`],[receiver,`http://127.0.0.1:${fixture.participant_port}/api/health`]])await expect.poll(async()=>{if(child.exitCode!==null)throw new Error(JSON.stringify(logs));try{return(await fetch(url)).status===200;}catch{return false;}},{timeout:45000,intervals:[250,500,1000]}).toBe(true);
 await page.goto(`http://127.0.0.1:${fixture.port}/`);await stage('Create a study');await page.getByRole('dialog',{name:'Start a study',exact:true}).waitFor();await page.locator('#new_title').fill(title);await page.getByLabel('Blank design',{exact:true}).check();await stage('Create study');await page.getByLabel('Study name',{exact:true}).waitFor();
 await stage('Questions');await stage('Add question');await page.locator('#q_prompt_1').fill('Overall, how much do you like this packaging concept?');await select('q_scope_1','End of study');await page.locator('#q_options_1').fill('Dislike a lot | 1\nDislike | 2\nNeither | 3\nLike | 4\nLike a lot | 5');await stage('Save');await stage('Tasks');await author(0);await author(1);
 const originalFile=await download('Export design','original.brohn-study.zip');original=portable(originalFile);assert.equal(original.questions.length,1);assert.equal(original.maxdiff.length,2);assert.deepEqual(graph(original).map(e=>e.sets),[[[2,1,3],[0,2,3],[0,1,2],[0,1,3]],[[1,2,3],[0,2,3],[0,1,3],[0,1,2]]]);
 check(original.maxdiff.every((e,i)=>e.settings.prompt===framing[i].prompt&&e.settings.best_label===framing[i].best&&e.settings.worst_label===framing[i].worst&&e.settings.required===framing[i].required&&e.origin==='synthetic'),'Saved design combines explicit liking with distinct required/optional choice framing and exact edited set order');
 await page.locator('[data-brohn-event="maxdiff_edit"]').first().click();const oldToken=await page.locator('#maxdiff_form_identity').inputValue();await page.locator('#maxdiff_title').fill('Discard this title');await page.getByLabel('Item 1 label',{exact:true}).fill('Discard this label');await stage('Cancel');assert.deepEqual(portable(await download('Export design','cancelled-edit.zip')),original);check(true,'Cancel discards both framing and item edits without altering the saved design');
 await page.locator('[data-brohn-event="maxdiff_edit"]').last().click();const newToken=await page.locator('#maxdiff_form_identity').inputValue();assert.notEqual(newToken,oldToken);for(const event of ['maxdiff_save','maxdiff_cancel']){await page.evaluate(({event,token})=>Shiny.setInputValue(event,{token},{priority:'event'}),{event,token:oldToken});await expect(page.locator('#platform_error')).toContainText(/earlier best-worst editor/);await expect(page.locator('#maxdiff_form_identity')).toHaveValue(newToken);}await stage('Cancel');assert.deepEqual(portable(await download('Export design','stale-editor-rejected.zip')),original);check(true,'Prior-modal Save and Cancel cannot modify or close the newly opened exercise editor');
 await stage('Collect');await expect(page.getByText('Best-worst choices',{exact:true})).toBeVisible();await expect(page.locator('body')).toContainText('explicit choices after timed tasks');
 for(const value of ['pilot','live']){const label=value==='pilot'?'Pilot / practice':'Live study';await select('release_origin',label);await expect(page.locator('#release_origin')).toHaveValue(value);await stage('Release participant study');await expect(page.locator('#platform_error')).toContainText('Replace the example best-worst materials');const since=Date.now();await expect.poll(async()=>{assert.match(await page.locator('#platform_error').innerText(),/Replace the example best-worst materials/);return Date.now()-since;},{timeout:6500,intervals:[250]}).toBeGreaterThanOrEqual(2600);check((await snapshot(original.id)).deployments.length===0,`${value} release rejects synthetic materials without creating a participant deployment`);check(true,`${value} validation remains readable through quiet debounce and background polling`);}
 await select('release_origin','Example walkthrough (sample)');await expect(page.locator('#release_origin')).toHaveValue('sample');await page.getByLabel('Require a researcher-issued participant code to link repeat sessions',{exact:true}).check();await stage('Release participant study');await page.getByRole('link',{name:'Open participant study',exact:true}).waitFor();await expect(page.locator('#platform_error')).toBeEmpty();check(true,'A deliberate successful sample release clears the previous actionable error');const participantUrl=await page.getByRole('link',{name:'Open participant study',exact:true}).getAttribute('href');
 const released=await snapshot(original.id);assert.equal(released.deployments.length,1);assert.equal(released.deployments[0].origin,'sample');assert.deepEqual(released.selected.body,original);const choices=released.compiled.timeline.filter(s=>s.type==='maxdiff');check(choices.length===8&&choices.every(s=>s.phase==='explicit_choice')&&released.compiled.timeline.findLastIndex(s=>s.type==='maxdiff')<released.compiled.timeline.findIndex(s=>s.type==='question'),'Explicit sample release retains synthetic provenance and compiles both exercises before the final liking question');await axe('maxdiff-collection-narrow',true);
 const pc=await browser.newContext({viewport:{width:1440,height:1080}}),p=await pc.newPage();activePage=p;p.on('pageerror',e=>errors.push(e.message));await p.goto(participantUrl);await p.getByLabel('Participant alias (required)',{exact:true}).fill('ORIGINAL-MAXDIFF-RESEARCHER-QA');await p.getByLabel('I have read the study information and agree to take part.',{exact:true}).check();const pending=p.waitForResponse(r=>r.url().includes('/api/start/')&&r.request().method()==='POST');await p.getByRole('button',{name:'Start study',exact:true}).click();const start=await(await pending).json();assert.ok(start.run_id,JSON.stringify(start));assert.equal(start.protocol.design_hash,released.compiled.design_hash);await p.getByRole('button',{name:'Begin',exact:true}).click();await p.getByRole('heading',{name:framing[0].prompt,exact:true}).waitFor();await expect(p.locator('body')).toContainText(framing[0].best);await expect(p.locator('body')).toContainText(framing[0].worst);await axe('maxdiff-participant-narrow',true,p);check(true,'Actual separate participant service starts the frozen synthetic study and presents its authored choice framing');p.on('dialog',d=>d.accept());await p.getByRole('button',{name:'Stop study',exact:true}).click();await p.getByRole('heading',{name:'You have stopped the study.',exact:true}).waitFor();await pc.close();activePage=page;
 await stage('Save as template');await expect(page.locator('#platform_status')).toContainText('Design saved');const template=(await snapshot(original.id)).templates.find(t=>t.body.source_study_id===original.id||t.body.design?.id===original.id);assert.ok(template);await stage('Design library');await page.locator(`[data-brohn-event="brohn_use_template"][data-brohn-value='"${template.id}"']`).click();await page.getByLabel('Study name',{exact:true}).waitFor();const fromTemplate=portable(await download('Export design','template-copy.zip'));fresh(fromTemplate,original,'Template use');
 await openOriginal();await stage('Clone design');await page.getByLabel('Name for the new study',{exact:true}).fill(`${title} copy`);await stage('Create clone');await expect(page.getByLabel('Study name',{exact:true})).toHaveValue(`${title} copy`);const cloned=portable(await download('Export design','clone.zip'));fresh(cloned,original,'Clone');
 await stage('Design library');await page.locator('#import_design_file').setInputFiles(originalFile);await page.getByLabel('Study name',{exact:true}).waitFor();const imported=portable(await download('Export design','reimported.zip'));fresh(imported,original,'Portable reimport');
 const final=await snapshot(original.id);assert.deepEqual(final.selected.body,original);assert.equal(final.runs.length,1);assert.equal(final.runs[0].completion_status,'withdrawn');assert.equal(final.runs[0].origin,'sample');assert.equal(final.reports.length,0);assert.equal(final.jobs.length,0);check(true,'Original design/history retains the withdrawn sample visit; all reused designs carry no results, runs or participant links');
 await openOriginal();await stage('Tasks');await expect(page.getByRole('button',{name:'Edit exercise',exact:true})).toHaveCount(2);await axe('maxdiff-saved-tasks-narrow',true);check(errors.length===0&&violations.length===0,'No browser exceptions, visible R failures or automated accessibility violations');await fs.writeFile(path.join(output,'results.json'),JSON.stringify({origin:'original_synthetic',scope:'researcher_authoring_and_reuse_actual_shiny_and_receiver_no_scientific_worker',checks,fixture:folder,study_id:original.id,run_id:start.run_id,reused_study_ids:[fromTemplate.id,cloned.id,imported.id]},null,2));console.log(JSON.stringify({checks:checks.length,output}));
}catch(error){await activePage.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});await fs.writeFile(path.join(output,'failure.json'),JSON.stringify({error:error.stack,checks,errors,violations,text:await activePage.locator('body').innerText().catch(()=>'(closed)')},null,2));throw error;
}finally{await browser.close();if(app.exitCode===null){await fs.writeFile(path.join(folder,'stop.request'),'Stop this owned original MaxDiff authoring fixture.');await expect.poll(()=>app.exitCode!==null,{timeout:15000,intervals:[100,250]}).toBe(true);}if(receiver.exitCode===null&&receiver.signalCode===null){receiver.kill();await expect.poll(()=>receiver.exitCode!==null||receiver.signalCode!==null,{timeout:10000,intervals:[100,250]}).toBe(true);}for(const [name,log]of Object.entries(logs))await fs.writeFile(path.join(output,`${name}.log`),log);}
