source("R/storage.R")
local({
  directory <- tempfile("research-draft-tests-")
  dir.create(directory)
  on.exit(unlink(directory, recursive = TRUE), add = TRUE)
  path <- file.path(directory, "study.json")
  fail <- function(expr, pattern) {
    error <- tryCatch({ force(expr); NULL }, error = identity)
    expect(inherits(error, "error") && grepl(pattern, conditionMessage(error), fixed = TRUE))
  }
  original <- sample_bundle()
  receipt <- save_bundle(original, path)
  expect(file.exists(path) && identical(receipt$fingerprint, draft_fingerprint(path)))
  expect(isTRUE(all.equal(read_bundle(path), original)))
  fail(save_bundle(original, path), "Explicit overwrite")
  updated <- original; updated$study$questions[[1]]$prompt <- "How much do you like this image?"
  save_bundle(updated, path, overwrite = TRUE, expected_fingerprint = receipt$fingerprint)
  expect(isTRUE(all.equal(read_bundle(path), updated)))
  fail(save_bundle(original, path, overwrite = TRUE, expected_fingerprint = receipt$fingerprint), "changed since")
  expect(isTRUE(all.equal(read_bundle(path), updated)))
  wrong <- original; wrong$study$id <- wrong$session$study_id <- "different"
  wrong$events <- list()
  fail(save_bundle(wrong, path, overwrite = TRUE), "another study")
  invalid <- updated; invalid$events[[1]]$mode <- "live"
  fail(save_bundle(invalid, path, overwrite = TRUE), "origin/study mismatch")
  expect(isTRUE(all.equal(read_bundle(path), updated)))
  dir.create(paste0(path, ".lock"))
  fail(save_bundle(updated, path, overwrite = TRUE), "locked by another save")
  unlink(paste0(path, ".lock"), recursive = TRUE)
  fail(.atomic_draft_replace("partial", path, write_fn = function(text, temporary) {
    writeLines(text, temporary); stop("simulated interrupted write")
  }), "interrupted write")
  expect(isTRUE(all.equal(read_bundle(path), updated)))
  fail(.atomic_draft_replace("partial", path, rename_fn = function(...) FALSE), "previous file has been kept")
  expect(isTRUE(all.equal(read_bundle(path), updated)))
  expect(length(list.files(directory, pattern = "^\\.draft-", all.files = TRUE)) == 0L)
  fail(read_bundle(file.path(directory, "missing.json")), "not found")
  fail(read_bundle(path, max_bytes = 10), "size limit")
  fail(read_bundle(directory), "not found")
  fail(save_bundle(original, file.path(directory, "missing", "new.json")), "folder does not exist")
  broken <- file.path(directory, "broken.json")
  writeLines('{"incomplete":', broken)
  fail(read_bundle(broken), "Could not open this draft")
  writeLines(character(), broken)
  fail(read_bundle(broken), "empty")
  unicode <- updated; unicode$study$questions[[1]]$prompt <- "Caf\u00e9: how much do you like it?"
  save_bundle(unicode, path, overwrite = TRUE)
  expect(identical(read_bundle(path)$study$questions[[1]]$prompt, unicode$study$questions[[1]]$prompt))
  expect(!dir.exists(paste0(path, ".lock")))
})
