# Explicit inactive saved-variant-run-analysis/0.1 worker. No catalogue handle.
args <- commandArgs(trailingOnly = TRUE)
arg <- function(name) { i <- which(args == name); if (length(i) != 1L || i == length(args)) stop("Missing or repeated ", name); args[[i+1L]] }
sources <- c(
  "R/platform-core.R",
  "R/platform-question-materials.R",
  "R/platform-welcome.R",
  "R/platform-question-flow.R",
  "R/platform-analysis-plan.R",
  "R/platform-store.R",
  "R/platform-publication.R",
  "R/platform-methods.R",
  "R/platform-delivery.R",
  "R/platform-runner-assets.R",
  "R/platform-analysis.R",
  "R/platform-jobs.R",
  "R/platform-task-delivery.R",
  "R/platform-sciat-window-candidate.R",
  "R/platform-sciat-window.R",
  "R/platform-sciat-window-delivery.R",
  "R/platform-sciat-window-score.R",
  "R/platform-gnat.R",
  "R/platform-capture.R",
  "R/platform-camera-analysis.R",
  "R/platform-participant-equipment.R",
  "R/platform-scales.R",
  "R/platform-question-sections.R",
  "R/platform-question-revision.R",
  "R/platform-question-revision-delivery.R",
  "R/platform-run-evidence.R",
  "R/platform-questionnaire-artifacts.R",
  "R/platform-questionnaire-artifact-storage.R",
  "R/platform-maxdiff.R",
  "R/platform-maxdiff-platform.R",
  "R/platform-method-evidence.R",
  "R/platform-method-evidence-binding.R",
  "R/platform-method-evidence-ancestry.R",
  "R/platform-method-evidence-identity.R",
  "R/platform-method-evidence-domain.R",
  "R/platform-variant-design.R",
  "R/platform-task-protocol-history.R",
  "R/platform-method-evidence-protocol-history.R",
  "R/platform-variant-protocol-history.R",
  "R/platform-evidence-run-source.R",
  "R/platform-variant-run-source.R",
  "R/platform-variant-analysis-index.R",
  "R/platform-variant-run-reader.R",
  "R/platform-variant-analysis-values.R",
  "R/platform-variant-analysis.R",
  "R/platform-variant-analysis-identity.R"
)
# Parent transport/queue/publication bytes are pinned, never sourced in the child.
identity_paths <- c(
  "scripts/variant-analysis-worker.R",
  "R/platform-core.R",
  "R/platform-question-materials.R",
  "R/platform-welcome.R",
  "R/platform-question-flow.R",
  "R/platform-analysis-plan.R",
  "R/platform-store.R",
  "R/platform-publication.R",
  "R/platform-methods.R",
  "R/platform-delivery.R",
  "R/platform-runner-assets.R",
  "R/platform-analysis.R",
  "R/platform-jobs.R",
  "R/platform-task-delivery.R",
  "R/platform-sciat-window-candidate.R",
  "R/platform-sciat-window.R",
  "R/platform-sciat-window-delivery.R",
  "R/platform-sciat-window-score.R",
  "R/platform-gnat.R",
  "R/platform-capture.R",
  "R/platform-camera-analysis.R",
  "R/platform-participant-equipment.R",
  "R/platform-scales.R",
  "R/platform-question-sections.R",
  "R/platform-question-revision.R",
  "R/platform-question-revision-delivery.R",
  "R/platform-run-evidence.R",
  "R/platform-questionnaire-artifacts.R",
  "R/platform-questionnaire-artifact-storage.R",
  "R/platform-maxdiff.R",
  "R/platform-maxdiff-platform.R",
  "R/platform-method-evidence.R",
  "R/platform-method-evidence-binding.R",
  "R/platform-method-evidence-ancestry.R",
  "R/platform-method-evidence-identity.R",
  "R/platform-method-evidence-domain.R",
  "R/platform-variant-design.R",
  "R/platform-task-protocol-history.R",
  "R/platform-method-evidence-protocol-history.R",
  "R/platform-variant-protocol-history.R",
  "R/platform-evidence-run-source.R",
  "R/platform-variant-run-source.R",
  "R/platform-variant-analysis-index.R",
  "R/platform-variant-run-reader.R",
  "R/platform-variant-analysis-values.R",
  "R/platform-variant-analysis.R",
  "R/platform-variant-analysis-identity.R",
  "scripts/workers/publication.py",
  "src/publication_guard.c",
  "R/platform-variant-run-transport.R",
  "R/platform-variant-analysis-queue.R",
  "R/platform-variant-analysis-claim.R",
  "R/platform-variant-analysis-publication-schema.R",
  "R/platform-variant-analysis-publication.R",
  "R/platform-variant-analysis-process.R"
)
if (anyDuplicated(identity_paths) || !all(file.exists(identity_paths))) stop("The complete saved-variant worker closure is unavailable.")
hash_sources <- function(paths) setNames(lapply(paths, function(p) digest::digest(file=p, algo="sha256")), paths)
identity <- hash_sources(identity_paths)
for (path in sources) source(path, encoding="UTF-8")
brohn_require(identical(identity_paths, .brohn_vra_worker_paths()), "Variant worker and registration paths disagree.")
# Literal parsing cannot treat a corrupt input document as a file path or URL.
request_path <- arg("--request")
brohn_require(file.exists(request_path) && !dir.exists(request_path) && file.info(request_path)$size <= 16*1024^2,
  "Variant worker request is unavailable or exceeds its byte bound.")
input <- .brohn_vra_decode(readBin(request_path, "raw", n=16*1024^2+1L))
result <- brohn_analyse_variant_input(input, arg("--scratch"))
result <- brohn_pack_questionnaire_report(result, arg("--scratch"))
brohn_require(identical(identity, hash_sources(identity_paths)),
  "Saved-variant analysis implementation changed during processing. Preserve the originals and retry a stable installation.")
brohn_write_json_file(list(schema="brohn-analysis-output/1.0", analysis_profile=.brohn_vra_profile,
  code_identity=identity, report=result), arg("--output"))
