brohn_raw_gaze_settings_ui <- function(m, columns) {
  column <- function(id, label, field) shiny::selectInput(id, label,
    c("Not supplied" = "", stats::setNames(columns, columns)), brohn_default(m[[field]], ""))
  number <- function(id, label, value, min, max) shiny::numericInput(id, label, brohn_default(value, NA_real_), min = min, max = max)
  shiny::conditionalPanel("input.map_gaze_representation === 'samples'",
    shiny::h3("How gaze was recorded"),
    shiny::p("Angular velocity needs the physical size of the displayed stimulus and the eye's viewing position. Use the rendered stimulus size, which may differ from the monitor size."),
    shiny::div(class = "brohn-form-grid",
      column("map_exposure_start", "Exposure onset (optional)", "exposure_start_column"),
      column("map_exposure_end", "Exposure offset (optional)", "exposure_end_column"),
      number("map_geometry_width", "Displayed stimulus width (mm)", m$geometry$width_mm, .01, 100000),
      number("map_geometry_height", "Displayed stimulus height (mm)", m$geometry$height_mm, .01, 100000),
      number("map_geometry_distance", "Eye to stimulus plane (mm)", m$geometry$distance_mm, 1, 100000),
      number("map_geometry_x", "Stimulus centre relative to eye: horizontal (mm)", m$geometry$center_x_mm, -100000, 100000),
      number("map_geometry_y", "Stimulus centre relative to eye: vertical (mm)", m$geometry$center_y_mm, -100000, 100000)),
    shiny::textAreaInput("map_geometry_source", "Where these measurements came from", brohn_default(m$geometry_source, ""), rows = 2, width = "100%"),
    shiny::tags$details(open = NA, shiny::tags$summary("Fixation and saccade detection settings"),
      shiny::p("Brohn's adjacent-ray velocity detector produces candidate events. Record the settings chosen for your device and protocol; these fields do not imply equivalence to a manufacturer's filter."),
      shiny::div(class = "brohn-form-grid",
        number("map_gaze_velocity", "Velocity threshold (degrees / second)", m$parameters$velocity_threshold_deg_s, .01, 10000),
        number("map_gaze_fixation", "Minimum fixation duration (ms)", m$parameters$min_fixation_ms, 1, 10000),
        number("map_gaze_saccade", "Minimum saccade duration (ms)", m$parameters$min_saccade_ms, .1, 1000),
        number("map_gaze_gap", "Largest supported sample gap (ms)", m$parameters$max_gap_ms, .01, 1000)),
      shiny::textAreaInput("map_gaze_threshold_source", "Detection settings source and rationale", brohn_default(m$parameters$threshold_source, ""), width = "100%", rows = 2)),
    shiny::tags$details(shiny::tags$summary("Pupil, blink and eye availability measures"),
      shiny::div(class = "brohn-form-grid",
        column("map_pupil", "Pupil measurement", "pupil_column"), column("map_pupil_valid", "Pupil validity", "pupil_valid_column"),
        column("map_blink", "Explicit blink label", "blink_column"), column("map_left_valid", "Left-eye availability", "left_valid_column"),
        column("map_right_valid", "Right-eye availability", "right_valid_column")),
      shiny::p("Track loss is retained as missing gaze. It becomes a blink only when a separate, documented detector labels it."),
      shiny::textInput("map_blink_source", "Blink detector and source", brohn_default(m$blink_source, "")),
      shiny::conditionalPanel("input.map_pupil && input.map_pupil !== ''",
        shiny::selectInput("map_pupil_unit", "Pupil measurement unit", c("Confirm unit" = "", "Millimetres" = "mm", "Square millimetres" = "mm2", "Pixels" = "pixels", "Square pixels" = "pixels2", "Device units" = "device_units"), brohn_default(m$pupil_unit, "")),
        shiny::textInput("map_pupil_source", "Pupil source, eye and preprocessing", brohn_default(m$pupil_source, "")),
        shiny::selectInput("map_pupil_baseline_mode", "Pupil baseline correction", c("Retain original pupil values" = "none", "Subtract an explicit baseline" = "subtractive"), brohn_default(m$pupil_baseline$mode, "none")),
        shiny::conditionalPanel("input.map_pupil_baseline_mode === 'subtractive'",
          shiny::textInput("map_pupil_baseline_phase", "Baseline value in the phase column", brohn_default(m$pupil_baseline$phase_value, "")),
          shiny::selectInput("map_pupil_baseline_start", "Baseline onset column", c("Choose column" = "", columns), brohn_default(m$pupil_baseline$start_column, "")),
          shiny::selectInput("map_pupil_baseline_end", "Baseline offset column", c("Choose column" = "", columns), brohn_default(m$pupil_baseline$end_column, "")),
          number("map_pupil_baseline_coverage", "Minimum observed baseline fraction (0 to 1)", m$pupil_baseline$minimum_coverage, .01, 1),
          number("map_pupil_baseline_duration", "Minimum observed baseline duration (ms)", m$pupil_baseline$minimum_duration_ms, 1, 600000),
          shiny::textAreaInput("map_pupil_baseline_source", "Baseline policy source and rationale", brohn_default(m$pupil_baseline$source, ""), rows = 2, width = "100%")))))
}
brohn_raw_gaze_input <- function(input) {
  list(exposure_start_column = input$map_exposure_start, exposure_end_column = input$map_exposure_end,
    geometry = list(width_mm = input$map_geometry_width, height_mm = input$map_geometry_height,
      distance_mm = input$map_geometry_distance, center_x_mm = input$map_geometry_x, center_y_mm = input$map_geometry_y),
    geometry_source = input$map_geometry_source,
    parameters = list(velocity_threshold_deg_s = input$map_gaze_velocity, min_fixation_ms = input$map_gaze_fixation,
      min_saccade_ms = input$map_gaze_saccade, max_gap_ms = input$map_gaze_gap, threshold_source = input$map_gaze_threshold_source),
    pupil_column = input$map_pupil, pupil_valid_column = input$map_pupil_valid, pupil_unit = input$map_pupil_unit,
    pupil_source = input$map_pupil_source, blink_column = input$map_blink, blink_source = input$map_blink_source,
    left_valid_column = input$map_left_valid, right_valid_column = input$map_right_valid,
    pupil_baseline = if (identical(input$map_pupil_baseline_mode, "subtractive")) list(mode = "subtractive", phase_value = input$map_pupil_baseline_phase,
      start_column = input$map_pupil_baseline_start, end_column = input$map_pupil_baseline_end,
      minimum_coverage = input$map_pupil_baseline_coverage, minimum_duration_ms = input$map_pupil_baseline_duration,
      source = input$map_pupil_baseline_source) else list(mode = "none"))
}
