brohn_load <- function(envir = parent.frame(), ui = TRUE) {
  # Legacy readers retain their original validators and identifiers.
  legacy <- c("study", "comparison", "presentation", "records", "json", "storage", "drafts", "assets", "aois",
    "analysis", "sample-analysis", "gaze-import", "import-report", "protocol", "protocol-storage")
  platform <- c("core", "question-materials", "welcome", "question-flow", "analysis-plan", "store", "publication", "methods", "library", "catalog", "delivery", "portability", "analysis", "gaze", "vision", "facial-expression", "neural", "eda-events", "headers", "physiology-artifacts", "signal", "multimodal", "jobs", "runtime")
  platform <- c(platform, "runner-assets")
  if (file.exists("R/platform-task-delivery.R")) platform <- c(platform, "task-delivery")
  platform <- c(platform, "sciat-window-candidate", "sciat-window", "sciat-window-delivery", "sciat-window-score")
  if (file.exists("R/platform-backup.R")) platform <- c(platform, "backup")
  if (file.exists("R/platform-interchange.R")) platform <- c(platform, "interchange")
  if (file.exists("R/platform-capture.R")) platform <- c(platform, "capture")
  platform <- c(platform, "camera-analysis", "camera-analysis-store")
  platform <- c(platform, "collection-history", "session-resolution")
  platform <- c(platform, "participant-equipment")
  if (file.exists("R/platform-acquisition.R")) platform <- c(platform, "acquisition")
  if (file.exists("R/platform-acquisition-quality.R")) platform <- c(platform, "acquisition-quality")
  if (file.exists("R/platform-equipment-setups.R")) platform <- c(platform, "equipment-setups")
  if (file.exists("R/platform-stream-curation.R")) platform <- c(platform, "stream-curation")
  if (file.exists("R/platform-scales.R")) platform <- c(platform, "scales")
  platform <- c(platform, "peripheral", "peripheral-synthesis")
  platform <- c(platform, "ingestion")
  platform <- c(platform, "run-review", "run-catalog", "question-sections")
  platform <- c(platform, "question-revision", "question-revision-delivery")
  platform <- c(platform, "run-evidence", "questionnaire-artifacts", "questionnaire-artifact-storage")
  platform <- c(platform, "questionnaire-index", "questionnaire-explorer")
  platform <- c(platform, "answer-session")
  platform <- c(platform, "explicit-distributions")
  platform <- c(platform, "vision-explorer", "vision-frame")
  platform <- c(platform, "signal-values")
  platform <- c(platform, "linked-review")
  platform <- c(platform, "audio-review", "audio-extraction", "eda-review", "respiration-review", "emg-review", "eda-continuous-review", "hosted-profile")
  platform <- c(platform, "gaze-traces", "gaze-retention", "gaze-trace-views", "gaze-trace-jobs")
  platform <- c(platform, "signal-annotations", "signal-reuse", "cardiac-review")
  platform <- c(platform, "materials")
  platform <- c(platform, "task-import", "task-import-storage", "task-evidence")
  platform <- c(platform, "task-cohort", "task-cohort-storage", "task-plots")
  if (file.exists("R/platform-scale-comparisons.R")) platform <- c(platform, "scale-comparisons")
  platform <- c(platform, "paired-plots")
  if (file.exists("R/platform-related-catalog.R")) platform <- c(platform, "related-catalog")
  if (file.exists("R/platform-maxdiff.R")) platform <- c(platform, "maxdiff", "maxdiff-platform", "maxdiff-import")
  for (file in c(paste0("R/", legacy, ".R"), paste0("R/platform-", platform, ".R"))) source(file, local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-signal-reuse-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-cardiac-review-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-signal-value-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-gaze-trace-server.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-vision-explorer-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-collection-history-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-runner-provenance-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-session-resolution-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-explicit-distribution-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-answer-session-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-paired-plot-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-linked-review-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-audio-review-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-audio-extraction-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-eda-review-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-respiration-review-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-emg-review-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-eda-continuous-review-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-hosted-profile-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-report-coverage.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-sciat-window-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-facial-expression-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-equipment-setup-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-material-views.R", local = envir, encoding = "UTF-8")
  if (ui) source("R/platform-guidance-views.R", local = envir, encoding = "UTF-8")
  if (ui) for (name in c("shell", "aoi", "vision-views", "question-flow-views", "question-sections-views", "question-revision-views", "questionnaire-artifact-views", "questionnaire-explorer-views", "scale-views", "maxdiff-views", "maxdiff-plots", "maxdiff-import-views", "task-import-views", "task-cohort-views", "task-plot-views", "capture-views", "acquisition-views", "stream-curation-views", "collection-routes", "views", "task-views", "gaze-views", "neural-views", "neural-views-plots", "eda-events-views", "peripheral-views", "peripheral-report", "ingestion-views", "run-review-views", "data-views", "signal-views", "signal-annotations-views", "welcome-views", "gaze-report-views", "headers-views", "analysis-plan-views", "multimodal-views", "interchange-views", "app")) source(paste0("R/platform-", name, ".R"), local = envir, encoding = "UTF-8")
  invisible(TRUE)
}
